### ISSUE TITLE
error downloading daprd binary

### ISSUE THREAD

**Issue by pravpuru** [dapr/cli#1001]
In Windows 10, trying to perform 'dapr init' in Powershell in administrator mode. Everytime i try dapr init it fails. 

PS C:\Users\xxxxx> dapr init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.7.4
Downloading binaries and setting up components...
error downloading daprd binary: open C:\Users\xxxxx\.dapr\bin/daprd_windows_amd64.zip: Access is denied.

Any suggestions would be much appreciated.

**Comment by hueifeng** [comment]
@pravpuru Can you create files manually in `C:\Users` successfully

**Comment by pravpuru** [comment]
@hueifeng Yes, i'm able to create files. To be specific, in C:\Users\MyUserId\

**Comment by hueifeng** [comment]
Based on the description for this is the insufficient permissions, you can delete files in this directory?

**Comment by pravpuru** [comment]
I'm able to delete any file in the directory. So I'm wondering if the error message is misleading. 

I don't see daprd_windows_amd64.zip in the path  C:\Users\xxxxx.dapr\bin after i get this error.

**Comment by pravinpushkar** [comment]
@pravpuru Are you getting this only in 'administrator' mode ? I just tried on my local, seems to be working fine. Can you try `dapr uninstall --all` then do `dapr init`.

**Comment by pravpuru** [comment]
@pravinpushkar  I've tried that. Still no luck. Doing this worked for me. 
Downloaded the daprd_windows_amd64.zip manually and placed the extracted exe in the bin.

**Comment by pravinpushkar** [comment]
@pravpuru Any luck with this? Did you try setting the default home dir to some other folder where you have full permissions and do `dapr init`

```
set userprofile=<other directory>
dapr init
```

**Comment by pravinpushkar** [comment]
@pravpuru Did you get a chance to try above suggestion, basically by setting a different home directory ?
