### ISSUE TITLE
Enable Resiliency preview feature on Kubernetes

### ISSUE THREAD

**Issue by callebjo** [dapr/cli#1002]
## Ask your question here

Hi,

I have followed the dapr documentation to implement the resiliency feature in the DTA environment, but getting the below error after applying the component yaml.
error: unable to recognize "resiliency.yml": no matches for kind "Resiliency" in version "[dapr.io/v1alpha1](http://dapr.io/v1alpha1)"

Following are steps followed and the corresponding yaml files,
1. Enabled the resiliency feature by using the following yaml
      apiVersion: [dapr.io/v1alpha1](http://dapr.io/v1alpha1)
       kind: Configuration
       metadata:
          name: featureconfig
       spec:
          features:
            - name: Resiliency
              enabled: true

     kubectl apply -f featureconfig.yaml -n microsvc
2. Tried to deploy the component using the below configuration, but getting the above error.
     apiVersion: [dapr.io/v1alpha1](http://dapr.io/v1alpha1)
kind: Resiliency
metadata:
  name: documentconversionresiliency
scopes:
  - documentconversion
spec:
  policies:
    timeouts:
      general: 5s

    retries:
      exponentialBackoff:
        policy: exponential
        maxInterval: 5s
        maxRetries: 3

  targets:
    components:
      documentconversionstatestore:
        timeout: general
        retry: exponentialBackoff     

     kubectl apply -f resiliency.yaml -n microsvc
3. Also, added the dapr featureconfig in deploy.yaml. 
    annotations:
        build_number: build110
        [dapr.io/app-id](http://dapr.io/app-id): documentconversion
        [dapr.io/app-port](http://dapr.io/app-port): "8001"
        [dapr.io/config](http://dapr.io/config): "featureconfig"
        [dapr.io/enabled](http://dapr.io/enabled): "true"
        [dapr.io/http-max-request-size](http://dapr.io/http-max-request-size): "15"
        [dapr.io/sidecar-cpu-request](http://dapr.io/sidecar-cpu-request): 250m
        [dapr.io/sidecar-memory-request](http://dapr.io/sidecar-memory-request): 128Mi

**Comment by yaron2** [comment]
Are you running Dapr 1.7.x?

**Comment by callebjo** [comment]
Hi,

We are on dapr 1.7.0

Regards

**Comment by mukundansundar** [comment]
@callebjo Can you use 1.7.1 version of CLI? A fix was released for the resiliency CRD installation .... https://github.com/dapr/cli/releases/tag/v1.7.1

**Comment by mukundansundar** [comment]
Closing this issue for now. If it persists, please create a new issue.
