### ISSUE TITLE
`FOSSA` Abnormal state

### ISSUE THREAD

**Issue by hueifeng** [dapr/cli#1003]
## Expected Behavior

Make the state normal, solve the problem of `FOSSA`

[![FOSSA Status](https://app.fossa.com/api/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fcli.svg?type=shield)](https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fcli?ref=badge_shield)
## Steps to Reproduce the Problem

I have no permission operation. At present, our `FOSSA` is in an abnormal state and needs to be confirmed whether it can be solved.

https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fdapr%2Fcli/refs/branch/master/5121a9eb19404b97a2d157d29f63750a9d7b2175/preview

**Comment by shubham1172** [comment]
Issue due to the two false-positives
-  github.com/apache/thrift
- github.com/couchbaselabs/gojcbmock

Resolved.

**Comment by shubham1172** [comment]
Please reopen this ticket if issue persists.

**Comment by hueifeng** [comment]
close this issue.
