### ISSUE TITLE
Add support for using Mariner-based images

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/cli#1004]
## Describe the proposal

Starting with Dapr 1.8, we will have Mariner-based Docker images for Linux, whose tag ends in `-mariner` (e.g. `dapr-mariner`). Although optional, we should have a way to allow the CLI to use those images.

## Release Note

**ADD** Support for using Mariner-based Docker images

**Comment by shivamkm07** [comment]
\assign

**Comment by shivamkm07** [comment]
Since default dapr images ain't mariner, this should require adding a flag in dapr init. Something like `dapr init --mariner`. Would that be okay? 
cc @mukundansundar

**Comment by mukundansundar** [comment]
@shivamkm07 How does `dapr init --variant mariner`  sound? Will there be future variants? one for debug etc? Should CLI support those also?
@artursouza @ItalyPaleAle thoughts on this?

**Comment by shivamkm07** [comment]
> I do like `--variant mariner`. It leaves us more flexibility for the future. I don't think we have plans for a debug variant or any other at this point, but there could be in the future.

Yeah that looks good. WIll create a PR adding the flag to dapr init

**Comment by yaron2** [comment]
We should not support a non-configurable flag for images. Please choose a more descriptive name than `variant`, which to me gives associations to COVID :)

**Comment by ItalyPaleAle** [comment]
`--tag` or `--image-tag`?

**Comment by mukundansundar** [comment]
> `--tag` or `--image-tag`?

It is very easy to confuse with actual container tags. 

Whereas mariner is actually a different variant.

**Comment by shivamkm07** [comment]
Since mariner is essentially a distribution, we can use something like `--image-distribution`, but then it would only allow different distributions as it's values. 
If we want more generic flag for other variants as well, `--image-variant` seems more appropriate to me. Any other suggestions @yaron2?

**Comment by ItalyPaleAle** [comment]
I don't know how I feel about `distribution` as it's not a word commonly-used in the Docker world. Also, there's so few things inside those images that they hardly can be considered a "distribution".

`--image-variant` still seems the most appropriate imho. Just make sure we don't start publishing variants with greek letters as names 🙃
