### ISSUE TITLE
Add capability to specify a custom folder when using dapr init --slim command

### ISSUE THREAD

**Issue by GFlisch** [dapr/cli#1009]
## Describe the proposal

It is possible to install the CLI on a specific folder but not the dapr.exe.

The code uses always the DefaultConfigFilePath() which is using the  homeDir, _ := os.UserHomeDir().

I would like to have a capability to specify another "home" directory. The company where I am working we have not the right to install non signed exe anywhere and we are not admin of our pc. But we have an open door on a specific folder where we can (letting us still developing something 🙄).

Is it something you can imagine?

The work around is to temporarily change the home environment variable before running the dapr init --slim command.

func createSlimConfiguration(wg *sync.WaitGroup, errorChan chan<- error, info initInfo) {
	defer wg.Done()

	if !info.slimMode {
		return
	}

	// For --slim we pass empty string so that we do not configure zipkin.
	err := createDefaultConfiguration("", DefaultConfigFilePath())
	if err != nil {
		errorChan <- fmt.Errorf("error creating default configuration file: %w", err)
		return
	}
}

RELEASE NOTE:

ADD custom installation directory for dapr init --slim command.

**Comment by shivamkm07** [comment]
Another flag could be added to dapr init for specifying custom folder which will be used instead of HomeDir to install dapr binaries as well as config files etc. Something like `dapr init --dapr-dir <path_to_local_dir>`

**Comment by mukundansundar** [comment]
The issue here is `dapr` always looks to a particular path `~/.dapr/bin` for the `daprd` binary. If it is installed in some other location, each time `dapr` CLI is run, then it would need to know where the binary is installed at. 
This needs more discussion.

**Comment by GFlisch** [comment]
Hi @mukundansundar, could we imagine to add another environment variable only when this feature --dapr-dir is added. In this case the dapr exe can check if the environment variable exists. If not  it can take the default one ~/.dapr/bin?

**Comment by pravinpushkar** [comment]
Just looked at the code - `dapr run` command is picking the bin dir from https://github.com/dapr/cli/blob/747dc3f7aeeb525e1f71762e4986bd0e11f54442/pkg/standalone/run.go#L293

https://github.com/dapr/cli/blob/747dc3f7aeeb525e1f71762e4986bd0e11f54442/pkg/standalone/common.go#L30

So, it seems if we provide an alternate install path then dapr run should pick the binary correctly ?
