### ISSUE TITLE
CLI init command should return meaningful message instead of "exit status 1" when kubectl is not installed/configured

### ISSUE THREAD

**Issue by Haishi2016** [dapr/cli#101]
CLI init command should return meaningful message instead of "exit status 1" when kubectl is not installed/configured

**Comment by vsaroopchand** [comment]
I can work on this issue if no one has it.

**Comment by amanbha** [comment]
@Haishi2016 Does this still repros? I see a linked issue closed with a PR which hnadled multiple kubeconfigs.

**Comment by Haishi2016** [comment]
We can close this one. The error message is now surfaced.
