### ISSUE TITLE
Add missing annotations to the annotate cmd

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1018]
## Describe the proposal

Some annotations are missing in the annotate command. See https://v1-8.docs.dapr.io/reference/arguments-annotations-overview/

They need to be added to the annotate command.
|annotation|
|--|
|"dapr.io/http-read-buffer-size"
|"dapr.io/enable-api-logging"
|"dapr.io/unix-domain-socket-path"
|"dapr.io/volume-mounts"
|"dapr.io/volume-mounts-rw"
|"dapr.io/disable-builtin-k8s-secret-store"
|"dapr.io/placement-host-address"

## Release Note

RELEASE NOTE: ADD volume-mount and disable-builtin-k8s-store annotations to annotation cmd

**Comment by mukundansundar** [comment]
closed with #1020
