### ISSUE TITLE
Removed lines from Uninstall logic

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1050]
## Ask your question here

This discussion is for below change in commit[1]-
```
if uninstallPlacementContainer && !dockerInstalled {
		// if placement binary did not exist before trying to delete it and not able to connect to docker.
		return fmt.Errorf("%w \ncould not delete placement service. Either the placement binary is not found, or Docker may not be installed or running", err)
	}
```
[1] https://github.com/dapr/cli/pull/1041/commits/02bc6f43399a92c37974f5d35c2d2ddebcdcd13b 

Reason - 
1. this line is problematic, say when I ran uninstall in slim mode twice(which is the case we have in our tests - uninstall_without_install). The above if condition will evaluate to true and it will throw an error.
2. Uninstalling the containers when runtime is available/not available is handled by a logic before this one in these lines - 
```
if conatinerRuntimeAvailable {
		containerErrs = removeContainers(uninstallPlacementContainer, uninstallAll, dockerNetwork, runtimeCmd)
	}
```

**Comment by mukundansundar** [comment]
This seems ok ... The only behavioural change that I am seeing is wrt Warning messages printed out when containers do not exist ... The main thing is the binaries are removed when `/.dapr/bin` folder is removed. 
Are there any other behavioural changes that you are seeing @pravinpushkar @shubham1172 ?

**Comment by shubham1172** [comment]
Earlier it would return an error and exit with error code. Now it will just show the warning. The new behavior is consistent with other containers too. So +1 from me, thanks @pravinpushkar !

**Comment by pravinpushkar** [comment]
There is no behavioural change as such except the warning messages.
> The only behavioural change that I am seeing is wrt Warning messages printed out when containers do not exist
I think there is no point in checking whether containers exist or not when container runtime is not there(slim mode).

**Comment by mukundansundar** [comment]
@yaron2 Any issues with this change?

**Comment by yaron2** [comment]
> @yaron2 Any issues with this change?

No issues.

**Comment by mukundansundar** [comment]
closing issue ...
