### ISSUE TITLE
`dapr init` not creating the default components folder

### ISSUE THREAD

**Issue by sarsharma** [dapr/cli#1053]
## Expected Behavior

`dapr init` should create a default components folder `~/.dapr`
## Actual Behavior

The `~/.dapr` folder is not created as part of `dapr init`
Therefore `dapr run` fails with `/home/azureuser/.dapr/components: no such file or directory`

## Steps to Reproduce the Problem

OS: Linux (Ubuntu 20.04)
CLI Version: 1.8.1
Install the `dapr cli` using the script 
https://docs.dapr.io/getting-started/install-dapr-cli/
Run `dapr init`

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@sarsharma Is the `dapr init` command run as the same user as `azureuser`? Or is it run as root?

**Comment by sarsharma** [comment]
It is run as root @mukundansundar

**Comment by sarsharma** [comment]
When `dapr init` is run as root to install dapr, the `.dapr` folder is created under `/root/.dapr`
In this case, `dapr run` will not work without sudo
As a workaround, the `/root/.dapr` folder can be copied to the home directory of the user `~/.dapr` 
This allows `dapr run` to work without sudo

**Comment by shubham1172** [comment]
> When dapr init is run as root to install dapr, the .dapr folder is created under /root/.dapr

This default behavior of installing in the $HOME directory should be accepted. #1057 should solve this issue by allowing `sudo dapr init` to specify `--dapr-path` to `/home/azureuser/.dapr`.

**Comment by shubham1172** [comment]
> When dapr init is run as root to install dapr, the .dapr folder is created under /root/.dapr

#1057 should solve this issue by allowing `sudo dapr init` to specify `--dapr-path` to `/home/azureuser/.dapr`.
