### ISSUE TITLE
Custom installation directory using msi installer

### ISSUE THREAD

**Issue by shivamkm07** [dapr/cli#1079]
## Expected Behavior

At the time of installation, msi installer asks for a custom directory for installing Dapr CLI. CLI should be installed in the directory chosen by the user.

## Actual Behavior

MSI Installer always installs at `C:\dapr` irrespective of the directory chosen by the user

## Release Note

RELEASE NOTE:  **FIX** Bug in MSI Installer for CLI

**Comment by shubham1172** [comment]
Closed by #1081
