### ISSUE TITLE
how to dapr init by using a exist redis ?

### ISSUE THREAD

**Issue by bulolo** [dapr/cli#1084]
i have a redis now ,
i want run `dapr init` to use my exist redis,is there any idea?
or how to change the redis port by run dapr init?

<img width="1886" alt="image" src="https://user-images.githubusercontent.com/10026498/194732500-0a070c67-5a48-49da-a110-0e44f153f90e.png">

```
Bind for 0.0.0.0:6379 failed: port is already allocated.
```

**Comment by mukundansundar** [comment]
@bulolo As of right now you can run `dapr init --slim` to install only the binaries and basic configuration. Please make note that this also skip running zipkin and redis ... https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/#initialize-dapr-without-containers
