### ISSUE TITLE
Use fully qualified name for container images

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1090]
## Describe the proposal

Dapr CLI supports two container runtimes, Docker and Podman. For Podman to work, the fully qualified names for the container registries are required. See https://unix.stackexchange.com/questions/701784/podman-no-longer-searches-dockerhub-error-short-name-did-not-resolve-to-an

When `dapr init` is done using Podman, result: **FAILURE**

```
time="2022-10-10T16:22:58Z" level=warning msg="Falling back to --cgroup-manager=cgroupfs"

Error: error getting default registries to try: short-name "redis:6" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

When `redis` is installed with explicit `docker.io`, result: **SUCCESS**

```
podman pull docker.io/redis:6
...
Trying to pull docker.io/library/redis:6...
Getting image source signatures
Copying blob bd159e379b3b done  
Copying blob 7fade13fa484 done  
Copying blob 729b630784ac done  
Copying blob 7e8175a58591 done  
Copying blob 10a73736cdfb done  
Copying blob 065c77bf222a done  
Copying config 136fbb0456 done  
Writing manifest to image destination
...
```

## Note

This was not consistent across different Operating Systems. It worked on Windows, Mac, and Ubuntu 20, but not in vanilla Debian Linux.

I tested it on Podman v4.2.1 in Windows 11 Pro 10.0.22000 N/A Build 22000.

Also, the current workaround is to update `containers-registries.conf`
```
unqualified-search-registries = ["docker.io"]
```

## Release Note

RELEASE NOTE: **ADD**: fully qualified names for container images

**Comment by pravinpushkar** [comment]
Right, I tested with macos[brew installs v4.2.1] and Ubuntu 20[podman v3.4.2] it worked there but with podman v3.0 it did not work. IMO we can take a look at this for 1.10 as there is another way to make it work on older Podman versions as mentioned in above description.
