### ISSUE TITLE
Update redis version to `redis:6` for Github Container registry

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1094]
Make use of `redis:6` image from https://github.com/dapr/dapr/pkgs/container/3rdparty%2Fredis. This is a similar to https://github.com/dapr/cli/pull/1046 that has been done for dockerhub 
## Release Note

RELEASE NOTE: **FIXED** Update redis version to `redis:6` for Github Container registry

**Comment by mukundansundar** [comment]
closed by #1096
