### ISSUE TITLE
 No status returned. Is Dapr initialized in your cluster

### ISSUE THREAD

**Issue by isayden** [dapr/cli#1122]
## Expected Behavior

dapr installation successful

## Actual Behavior

The dapr upgrade showed success but the actual pod did not run as expected.

## Steps to Reproduce the Problem
My dapr-cli  version is 1.9.1 

1、`dapr   init  -k `
2、 view  `dapr  status -k `
3、`kubectl   get all  -n dapr-system `
![image](https://user-images.githubusercontent.com/89994987/198924078-ed47db77-cba7-4763-a864-cc4c448af04a.png)

**Comment by pravinpushkar** [comment]
@isayden By any chance, your `kubectl` pointing to a different context ?

**Comment by isayden** [comment]
@pravinpushkar   No. There is only one.  CLI installation and Helm installation will not automatically deploy pod, but also show that the installation was successful. is actually a failure

**Comment by shubham1172** [comment]
Looks like the pods are not ready and healthy, that might be a reason based on a quick look at the code. Did you try after the pods were up and available? @isayden

**Comment by isayden** [comment]
I don't understand what you are saying, no pod is generated after init initialization  @shubham1172

**Comment by shubham1172** [comment]
@isayden I meant it's likely not a `dapr status` issue, can you check `kubectl describe po`'s output?

**Comment by isayden** [comment]
@shubham1172       My cluster is fine. after init dapr, there is no pod for dapr, so there is no way to `describe`

**Comment by shubham1172** [comment]
@isayden you need to troubleshoot what's happening, `dapr init` will do a `helm install` on your cluster. You can check `kubectl get deployments` if no pods are created.
