### ISSUE TITLE
[Proposal] Enhance `dapr stop` functionality to handle stopping multiple apps

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1165]
## Describe the proposal

Related to  #1143, this proposal talks about enhancing the `dapr stop` experience to accommodate (a) stopping all apps, and (b) stopping a single app, started by the `dapr run -f` command.

1. When an application is started individually (using simple `dapr run`), `dapr stop --app-id <APP-ID>` should stop the application along with the CLI process associated with it.
1. When an application is started using `dapr run -f` (along with other apps), `dapr stop --app-id <APP-ID>` should 
    1. Warn the user that this application was started along with other apps (log the app-ids)
    1. Stop the application process
    1. If there are no other applications associated with the same CLI process that spawned this application, kill the CLI process; else, skip it.
1. When multiple applications are started with `dapr run -f dapr.yaml`, `dapr stop -f dapr.yaml` should stop all the running apps (based on app-id) along with the associated CLI process.

## Release Note

RELEASE NOTE: **ADD** support to `dapr stop` to handle applications spawned by `dapr run -f`

**Comment by pravinpushkar** [comment]
There is one edge-case with current `dapr stop <appID>` - 

If there are two apps with same app id started via `dapr run --app-id test`. Then `dapr stop test` will only stop the 1st app it founds from `dapr List` output.
 
As this is not an ideal situation for app setup, we can leave this unchanged IMO. I am also fine to change this to stop all apps with same app id. thoughts?

**Comment by shubham1172** [comment]
> If there are two apps with same app id

Two apps should not exist with the same app-id, correct?

**Comment by pravinpushkar** [comment]
It can. So, there are two main things now - 
1.  with normal `dapr stop appid` -> should we stop all apps with same appID ?
2. For `dapr stop -f <filepath>` -> For this case, just thinking if there is some way to avoid the file parsing again to obtain all `AppIDs` started by this.

It would be easier if we can include the run file path information in `dapr list` somehow.

**Comment by pravinpushkar** [comment]
the only way I think we can skip parsing the template file again is by updating the `extendedMetadata` to have another `key-value` in the form of - 
```json
{
//....
"extended": {
    "cliPID": "5699",
    "daprRuntimeVersion": "1.9.5",
    "runConfigFile": "<abs_path_for_run_file>"
  }
//....
}
```

If we have this, then we can extract out the appIds that are started via a particular runFile and cliPID.
thoughts ?

**Comment by mukundansundar** [comment]
> the only way I think we can skip parsing the template file again is by updating the `extendedMetadata` to have another `key-value` in the form of -
> 
> ```json
> {
> //....
> "extended": {
>     "cliPID": "5699",
>     "daprRuntimeVersion": "1.9.5",
>     "runConfigFile": "<abs_path_for_run_file>" // new addition
>   }
> //....
> }
> ```
> 
> If we have this, then we can extract out the appIds that are started via a particular runFile and cliPID. This will also solve #1153 thoughts ?

I think we can just have the file name displayed in the runFile field... There is a possible scenario where the location of the file is changed after apps have started. IMO having it read in as input argument to the stop command with say a flag `-f` is the best way possible.

**Comment by pravinpushkar** [comment]
> > the only way I think we can skip parsing the template file again is by updating the `extendedMetadata` to have another `key-value` in the form of -
> > ```json
> > {
> > //....
> > "extended": {
> >     "cliPID": "5699",
> >     "daprRuntimeVersion": "1.9.5",
> >     "runConfigFile": "<abs_path_for_run_file>" // new addition
> >   }
> > //....
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If we have this, then we can extract out the appIds that are started via a particular runFile and cliPID. This will also solve #1153 thoughts ?
> 
> I think we can just have the file name displayed in the runFile field... There is a possible scenario where the location of the file is changed after apps have started. IMO having it read in as input argument to the stop command with say a flag `-f` is the best way possible.

We will still take the filename as input like `dapr stop -f <filepath>`. The complete steps are as follows - 
1. dapr run -f <filepath>
> Below steps will have filepath in the form absolute path.
2. update clipid and filepath to `List` struct. `dapr list` will display the filenames used for running the apps.
3. `dapr stop -f <filepath>`. It will match the filepath to each row in `dapr list` output and gets the clipid.
4. kill the clipid to stop all apps and daprds.
