### ISSUE TITLE
Issues with dapr stop 

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1176]
#### 1. dapr stop does not stop app processes if the CLIPID is not set.
Steps to reproduce - 
1. start daprd and app separately. `dapr list` will list one entry for this.
2. run `dapr stop <appID>`. 
3. Observe only `daprd` process got killed.

It is possible that this app is configured to do some call to other dapr services and since the associated `daprd` got stop, the app will start showing logs for unable to communicate.

**Expected behavior** - app process should also get killed along with `daprd` when we execute `dapr stop <appID>`

#### 2. dapr stop hangs when only `daprd` process started
Steps to reproduce - 
1. start only `daprd` process.
2. Check `dapr list` output. Will display one entry.
3. Run `dapr stop <appID>`. Notice the process will hang and will never exit. This also happens when we just do 
<kbd>Ctrl</kbd> + c

#### 3. stop app process also with `dapr stop <appID>`
Steps to reproduce - 
1. For example, start a valid app through `dapr run` like - `dapr run --app-id test1 -- node app.js`
2. inspect the all the child processes via `ps -ef | grep <CLI PID>`
3. run `dapr stop <app id>`.
4. Notice only PID associated with `daprd` got killed and PID associated with app process is still running.

## Release Note

RELEASE NOTE: Fix dapr stop issues

**Comment by mukundansundar** [comment]
> Expected behavior - app process should also get killed along with daprd when we execute dapr stop <appID>

This is not possible since if the app is started with `dapr run` command then both daprd and app process are started by cli and cli then stores the app Pid in daprd metadata...

When app is started by user separately and daprd is directly started separately then there is no way to know what app a daprd process is referring to as app Pid will not be stored in daprd metadata.

cc @dapr/maintainers-cli

**Comment by pravinpushkar** [comment]
> > Expected behavior - app process should also get killed along with daprd when we execute dapr stop
> 
> This is not possible since if the app is started with `dapr run` command then both daprd and app process are started by cli and cli then stores the app Pid in daprd metadata...
> 
> When app is started by user separately and daprd is directly started separately then there is no way to know what app a daprd process is referring to as app Pid will not be stored in daprd metadata.
> 
> cc @dapr/maintainers-cli

yes, agree. for this scenario it seems not possible to get the associated `app pid` to kill.

For usecase # 3 above - 
> 3. stop app process also with dapr stop <appID>

We can get the associated app pid with the help of `CLIPID` and `app command`. and we can kill the app process also.

**Comment by philliphoff** [comment]
I think there's an additional case: `dapr stop <app-id>` for an app started with `dapr run -f <run file>`

Currently the `daprd` process is killed but not the command process (as the command PID is not tracked, see #1191).  The CLI process [group] cannot be killed as that would take out *all* the apps.

**Comment by pravinpushkar** [comment]
> I think there's an additional case: `dapr stop <app-id>` for an app started with `dapr run -f <run file>`
> 
> Currently the `daprd` process is killed but not the command process (as the command PID is not tracked, see #1191). The CLI process [group] cannot be killed as that would take out _all_ the apps.

yes this is the case as of now - the stop command need to be enhanced to stop app's process and subprocess also.
