### ISSUE TITLE
Dapr stales when logging large application logs

### ISSUE THREAD

**Issue by MatiKloster** [dapr/cli#1187]
DISCLAIMER= Not quite sure if this is the correct repository to report this issue.

Hi,
I was using Dapr locally to run one of our services that internally uses EF Core and somehow it staled and did not receive any incoming traffic (had to turn it off manually using ctrl+C)

I investigated the issue a bit further and I found that it was caused by a large EF.Database log (about 15000 integers). I reached this conclusion because when I turned the logging off the issue was not reproducible anymore.
I could not reproduce this issue on any of our live applications, it is happening only using self-hosted Dapr.

I could reproduce the issue in a repository test which I'm going to detail in the next sections. The repository test does not use EF so the issue doesn't have to do with it.

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

```
$ dapr -v
CLI version: 1.9.1
Runtime version: 1.9.5
```

## Expected Behavior

Dapr should not stale when logging large application logs

## Actual Behavior

If the application log is long enough, dapr stales 

## Steps to Reproduce the Problem
Within the repository is also detailed the issue

Clone this repo: `https://github.com/MatiKloster/console-logging-test`
`dapr run --app-id console-logging-test --app-port 5000 -- dotnet run --project ./ConsoleApp1/ConsoleApp1.csproj`
Check that the dapr stales

By using this test solution I found that with different values the issue behaves differently. For example:
* If the threshold is set to 12000 or lower, dapr logs the application log and it exits successfully.
* If the threshold is set to 13000 (I did not test other numbers near this value), dapr doesn't log the app log and it exits successfully.
* if the threshold is set to 14000 or higher, dapr doesn't log the app logs and it stales and never finishes.

Seems like a buffer problem?

## Release Note

RELEASE NOTE: **FIX** Bug in runtime when logging large application logs

**Comment by yaron2** [comment]
Transferred to correct repository.

**Comment by MatiKloster** [comment]
Hey, can anyone help with this issue?

**Comment by ryan-z** [comment]
@MatiKloster you're right, it does indeed seem to be a buffer problem. I think I tracked it down to the `Scan()` calls [somewhere around here](https://github.com/dapr/cli/blob/master/cmd/run.go#L774)
The default `bufio.MaxScanTokenSize` is 64 KB, which lines up with my testing above. Maybe there should be some error handling to gracefully handle anything over that?

**Comment by MatiKloster** [comment]
> @MatiKloster you're right, it does indeed seem to be a buffer problem. I think I tracked it down to the `Scan()` calls [somewhere around here](https://github.com/dapr/cli/blob/master/cmd/run.go#L774) The default `bufio.MaxScanTokenSize` is 64 KB, which lines up with my testing above. Maybe there should be some error handling to gracefully handle anything over that?

Maybe, at least it should not stale if the buffer is overflow somehow.

Can we get assistance here?

**Comment by mukundansundar** [comment]
@MatiKloster Thanks for reporting this. Will take a look at this.

**Comment by ryan-z** [comment]
I believe this is still an issue

**Comment by MatiKloster** [comment]
> 

Indeed. @mukundansundar were you be able to look into this?

**Comment by MatiKloster** [comment]
> I believe this is still an issue

Indeed. @mukundansundar were you be able to look into this?
