### ISSUE TITLE
dashboard fails to start if port 8080 in use

### ISSUE THREAD

**Issue by ryan-z** [dapr/cli#1188]
## Expected Behavior

An error message saying this port was already in use, and maybe suggest the command to resolve it (`dapr dashboard -p 9999`)

## Actual Behavior

It reports that it has started running, but then confusingly questions if dapr is installed:
```
Dapr Dashboard running on http://localhost:8080
❌  Dapr dashboard not found. Is Dapr installed?
```

## Steps to Reproduce the Problem

1. Bind anything to port 8080 (e.g. `npx serve -l 8080`)
2. Run `dapr dashboard`
3. Observe the confusing error message

## Release Note

RELEASE NOTE: **FIX** Error messaging in dashboard command.

**Comment by philliphoff** [comment]
Nice to see this was fixed!  The random port selection will help clean up logic in the VS Code extension when starting the dashboard.
