### ISSUE TITLE
Enhance `dapr run -f` to monitor started app processes

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1190]
## Describe the proposal

This issue is to enhance `dapr run -f` to monitor started app process to give an indication if an app process is stopped/crashed.

Currently if an app is stopped out of several apps started then it does not log any information regarding the activity.

Related to #1123
@mukundansundar 

## Release Note

RELEASE NOTE: **ADD** Log information for app process status on console. Rltd to `dapr run -f`

**Comment by mukundansundar** [comment]
This goes back to the proposal dapr/proposals#6 .
There it was discussed that this feature will not be monitoring the application for stops/crashes ... 
@dapr/maintainers-cli Wdyt?
