### ISSUE TITLE
Prefix appID and suffix timestamps to log files from `dapr run -f`

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1195]
## Describe the proposal

`dapr run -f` generates multiple log files for daprd and apps inside `.dapr/logs` folder. 

1. Adding app_id prefix will make it easy to identify the logs based on app, useful when same app_dir is used to spawn multiple app_ids
1. Adding timestamp to the log files as a suffix won't overwrite the log files during subsequent runs. 

## Release Note

RELEASE NOTE: **ADD** timestamp suffix to log files from `dapr run -f`

**Comment by mukundansundar** [comment]
closed by #1196
