### ISSUE TITLE
Add option to install scripts to select a specific version of the Dapr CLI

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/cli#1214]
## Describe the proposal

Would be nice to add an option to the install.sh scripts to select a specific version of the Dapr CLI. This would make it easier, for example, to install pre-releases (RCs)

## Release Note

RELEASE NOTE: **ADD** Allow specifying the version of the Dapr CLI to install with the install.sh script

**Comment by mukundansundar** [comment]
Have you tried https://github.com/dapr/cli/tree/master/install#get-the-specific-version-1 ?

**Comment by ItalyPaleAle** [comment]
Thanks, I missed that :)

**Comment by berndverst** [comment]
https://github.com/dapr/docs/pull/3163 made this docs PR

**Comment by berndverst** [comment]
Somebody else will have to figure out the powershell instructions to document.
