### ISSUE TITLE
Add support for Windows for dapr multi-app run

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1220]
## Describe the proposal
Add Windows support for dapr multi-app run `dapr run -f`
Make sure existing E2E works and runs automatically against Windows slim mode execution.

## Release Note

RELEASE NOTE:

**Comment by tastyeggs** [comment]
Is there a planned milestone for this feature? Are there any known blockers that make this difficult on Windows as opposed to Linux/MacOS?

**Comment by onionhammer** [comment]
Huge functionality gap here left by Tye, I would love if dapr could fill it..

**Comment by pravinpushkar** [comment]
@onionhammer There is already a PR to add a support for this on windows.

**Comment by mukundansundar** [comment]
closed by #1315
