### ISSUE TITLE
`dapr list` display the paths to the application and daprd logs in multi-app run

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#1228]
## Describe the proposal

When using a run file (i.e. `dapr run -f <file>`), Dapr CLI redirects the application and Dapr logs of each application to its own file (under `<appDirPath>/.dapr/logs`).  Subsequent runs will create new log files to ensure that developers can go back to previous logs for analysis, with each log filename containing a "timestamp" of its first creation.  This is great but, after a while, these logs can accumulate and make it difficult for the the user to pick out the *right* log (e.g. the log that's currently being written to).  Tooling can help, by automating the process of finding the "latest" logs and opening those (e.g. in the current editor).  However, that automation (based on filenames) is not entirely certain; there will always be a chance some combination of files in the directory disrupts any filename timestamp sort.

Tooling is likely to care mostly about the logs being written to *right now*, and this is information that the Dapr CLI has. I propose that the Dapr CLI expose that information in the `dapr list` command.  This will provide a more deterministic means to obtain the paths to application logs (and avoid having tooling care about Dapr log naming conventions).

For example:

```json
[
  {
    "appId": "vscode-test",
    "httpPort": 64040,
    "grpcPort": 64041,
    "appPort": 3000,
    "metricsEnabled": true,
    "command": "node ./bin/www",
    "age": "7s",
    "created": "2023-01-30 10:32.27",
    "daprdPid": 18398,
    "cliPid": 18392,
    "commandPid": 18399,
    "maxRequestBodySize": -1,
    "httpReadBufferSize": -1,
    "runTemplatePath": "/Users/phoff/Source/scratch/vscode-test/dapr.yaml",
    # New path to the application log file
    "appLogPath": "/Users/phoff/Source/scratch/vscode-test/app-one/.dapr/logs/app-one_app_20230202160305.log", 
    # New path to the daprd log file
    "daprdLogPath": "/Users/phoff/Source/scratch/vscode-test/app-one/.dapr/logs/app-one_daprd_20230202160305.log" 
  }
]
```

## Release Note

RELEASE NOTE:

**Comment by shivam-51** [comment]
Hi team, I am working on this!

**Comment by mukundansundar** [comment]
> Hi team, I am working on this!

Please use /assign to assign this issue you yourself.
