### ISSUE TITLE
Use GH CLI for publishing release artifacts to github

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1230]
## Describe the proposal
Instead of github-release-cli, use official GH cli to publish artifacts to github.

## Release Note

RELEASE NOTE:

**Comment by shubham1172** [comment]
Can we also mark this as a good first issue?

**Comment by letmerecall** [comment]
Would appreciate some more context.

So we are talking about not using `github-release` tool here:

https://github.com/dapr/cli/blob/45dcd5813de12e8c99fe3b5d45995b5e1c0bcd5e/.github/workflows/dapr_cli.yaml#L169-L186

And instead use `gh release` for this step?

https://cli.github.com/manual/gh_release

**Comment by shubham1172** [comment]
> And instead use gh release for this step?

Yes, @mukundansundar can you confirm?
