### ISSUE TITLE
Feature Request: DAPR CLI – Support Rancher Desktop

### ISSUE THREAD

**Issue by yoshua0x** [dapr/cli#1242]
## In what area(s)?
area runtime

## Describe the feature
Rancher Desktop is an open source implementation of Docker Desktop which supports the dockerd runtime. The industry is moving towards using Rancher Desktop due to the Docker Oct 22 pricing changes forcing business to now pay for Docker Desktop. 

In its current state, `dapr init` fails the container runtime check. I have created symbolic links on the socket – which worked for most use cases – without success with DAPR. I imagine there are some additional checks that I am not wary of.  

https://github.com/rancher-sandbox/rancher-desktop

## Release Note
RELEASE NOTE: Add CLI support for Rancher Desktop

**Comment by pravinpushkar** [comment]
@yoshua0x What exact issue you are encountering ? When you install rancher-desktop and enable dockerd container engine, `dapr init` should work by default and there should be no need to provide `--container-runtime` flag.

**Comment by mukundansundar** [comment]
@yoshua0x could you provide some more information as requested above?

**Comment by yoshua0x** [comment]
Apologies for the delay as I was off the grid. The issue was related to `unix:///var/run/docker.sock` being unavailable. 

The `Container Engine` was set to to `dockerd` in the Rancher preferences, however, I believe this happened due to Rancher Desktop not running in admin / administrative mode, therefore making the docker socket unavailable.

By explicitly running Rancher Desktop in admin mode, the socket is available and dapr CLI is functioning as expected. 

Thank you @pravinpushkar @mukundansundar

**Comment by kevin-fog** [comment]
Thank you kindly @yoshua0x, this fixed it for me too.
