### ISSUE TITLE
Include a schema for the multi-app run template file

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1270]
## Describe the proposal
Since the multi-app run is a feature dependent on a template file, it would help users/dev tool builders if a schema is provided defining what are the format of the template, types associated with each field and any restrictions placed on those values. 

Ideally the schema of the template file needs to be in sync with the actual fields supported by the template itself. 
This also helps in providing validations for the template. 

For Yaml Schema, we should follow the [JSON Schema](https://json-schema.org/) specs.

## Release Note

RELEASE NOTE:

**Comment by philliphoff** [comment]
Additional notes: the VS Code Dapr extension currently ships a JSON Schema definition for the multi-app template files:

https://github.com/microsoft/vscode-dapr/blob/main/assets/schemas/dapr.io/dapr/cli/run-file.json

While the extension needs to ship with (a copy of) the definition to allow for scenarios where the internet is not available, there's no specific reason why the extension needs to own the definition.  It might make sense for it to be owned by the Dapr CLI and have the extension pull down a copy during its package build process and/or dynamically download the latest (or a Dapr version-specific) version.  (This would be similar to how the Dapr runtime owns the pluggable components `.proto` files and each SDK pulls down their version during build.)
