### ISSUE TITLE
`dapr uninstall --all` should warn if container runtime is not running

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1288]
## Expected Behavior

When Docker (or any container runtime) is not running, `dapr uninstall --all` should throw a warning since placement, redis, and zipkin containers won't be removed.

## Actual Behavior

`dapr uninstall --all` exits with success status code and no warning.

## Steps to Reproduce the Problem

Ensure that docker is not running.

```
>> dapr uninstall --all
ℹ️  Removing Dapr from your machine...
ℹ️  Removing directory: /Users/shubham1172/.dapr/bin
ℹ️  Removing directory: /Users/shubham1172/.dapr
✅  Dapr has been removed successfully
```

## Release Note

RELEASE NOTE: **FIX** dapr uninstall --all to throw warning if Docker is not running

**Comment by mcaupybugs** [comment]
Hi based on the description of the bug I can see that adding an `else if` condition and checking if `uninstallPlacementContainer` or `uninstallAll` variable is set to true and giving warning should be the solution. 
```
containerRuntimeAvailable := false
	containerRuntimeAvailable = utils.IsDockerInstalled() || utils.IsPodmanInstalled()
	if containerRuntimeAvailable {
		containerErrs = removeContainers(uninstallPlacementContainer, uninstallAll, dockerNetwork, runtimeCmd)
	}
```

If this solution works, Can I contribute to this? Or please let me know if i am missing something.
