### ISSUE TITLE
Default components not being installed

### ISSUE THREAD

**Issue by NiloDrumond** [dapr/cli#1291]
CLI: 1.10.0
Runtime: 1.10.7

## Expected Behavior

As step 5 of the [getting started](https://docs.dapr.io/getting-started/install-dapr-selfhost/) tutorial describes, a folder .dapr should be in my Home directory with the default components.

## Actual Behavior

The default components folder is not being created when I run `sudo dapr init`:
```
➜ ~ ls $HOME/.dapr
ls: cannot access '/home/nilo/.dapr': No such file or directory
```

When I run `sudo dapr run --app-id myapp --dapr-http-port 3500` (which is the next step on the getting started tutorial) I get the following output:
```
INFO[0000] loading components                            app_id=myapp instance=nilo-eesd scope=dapr.runtime type=log ver=1.10.7
WARN[0005] error processing component, daprd process will exit gracefully  app_id=myapp instance=nilo-eesd scope=dapr.runtime type=log ver=1.10.7
FATA[0005] process component pubsub error: [INIT_COMPONENT_FAILURE]: initialization error occurred for pubsub (pubsub.redis/v1): init timeout for component pubsub exceeded after 5s  app_id=myapp instance=nilo-eesd scope=dapr.runtime type=log ver=1.10.7
❌  The daprd process exited with error code: exit status 1
```

Which may or may not be related.

If I run `run` without sudo I get:
```
WARNING: no application command found.
❌  error validating resources path "/home/nilo/.dapr/components" : stat /home/nilo/.dapr/components: no such file or directory
```

It's also important to notice that running `sudo dapr init` gave no errors. Output:

```
➜ ~ sudo dapr init
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
ℹ️  Installing runtime version 1.10.7
←  Downloading binaries and setting up components...
Dapr runtime installed to /root/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/root/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /root/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
```

Running `sudo docker ps` also successfully listed the expected containers.

## Steps to Reproduce the Problem

Environment: 
- Docker version 23.0.6, build ef23cbc431
- OS: 6.3.2-arch1-1

All I did was follow the getting started tutorial for local development:
- `wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash`
- `sudo dapr init`

## Release Note

RELEASE NOTE:

**Comment by shubham1172** [comment]
> sudo dapr init

Since you are running the command as sudo, your user's $HOME directory won't have `.dapr`.

I would recommend
- `sudo dapr uninstall --all`
- `dapr init`

Then try running the same commands. It is clear that in case of `dapr run`, it cannot find the `.dapr` directory (as expected).
