### ISSUE TITLE
Need to have Troubleshooting Section for common issues and resolutions

### ISSUE THREAD

**Issue by shalabhms** [dapr/cli#130]
Need to address common issues and resolutions:
For Example:

 **First Issue** :  On Windows, while building cli "mingw32-make.exe build"
if you see the below error 
"
process_begin: CreateProcess(NULL, uname -m, ...) failed.
mingw32-make.exe: Makefile:25: pipe: No error
'head' is not recognized as an internal or external command,
operable program or batch file.
'head' is not recognized as an internal or external command,
operable program or batch file.
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make.exe: Makefile:37: pipe: Bad file descriptor
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build  -ldflags "-X main.version=edge -X main.apiVersion=1.0" -mod=vendor \
-o ./dist/windows_amd64/release/dapr.exe;
'CGO_ENABLED' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe: *** [Makefile:81: dapr] Error 1"

**Resolution**   Check if the Git bin path is existing in the Path variable.

You can run this command which will update the git and add the paths in the Path variable.

choco install git.install --params "/GitAndUnixToolsOnPath /NoGitLfs /SChannel /NoAutoCrlf"

**Comment by amanbha** [comment]
@orizohar @msfussell its enchancing the docs by adding a troubleshooting section to cli.
