### ISSUE TITLE
Runtime upgrade is failing with new cli

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1347]
## Expected Behavior

Upgrade should pass

## Actual Behavior

Upgrade fails with dapr-operator in crashloopbackoff

## Steps to Reproduce the Problem

1. Install previous stable version of cli
2. Install previous stable version of runtime
3. Upgrade CLI to use latest RC
4. Try upgrading dapr with `latest_cli upgrade -k --runtime-version 1.12.0-rc.3`

## Release Note

RELEASE NOTE:

**Comment by pravinpushkar** [comment]
<img width="1717" alt="Screenshot 2023-09-22 at 9 51 12 PM" src="https://github.com/dapr/cli/assets/33649292/879b4858-2600-4cc9-8bc6-97654a7f44fc">

**Comment by mukundansundar** [comment]
Not able to reproduce this with 1.11 CLI or 1.12 RC CLI.

**Comment by pravinpushkar** [comment]
Closing this, as now I am not able to repro this on my local kind cluster.
