### ISSUE TITLE
Mutli-app-run should monitor processes and close on exit

### ISSUE THREAD

**Issue by paulyuk** [dapr/cli#1354]
## Describe the proposal
Today if you do the multi app run, e.g. on Workflow quickstart, it has some unexpected behaviors where the dapr console apps all complete and exit, but dapr run keeps running.  It looks like dapr run never will exit which is unexpected, and you have to force exit with CTL C etc.

The mainline proposal is we should add process monitoring and by default exit dapr run when *all dapr app processes have exited.  

There is also a case where some but not all dapr processes exit.  My suggestion and leaning is we do not exit dapr in this case, because there might be valid reasons for a job to exit, but keep the services alive.  We could however add a user config with a short circuit where if any processes exit, the whole dapr run exits. 

## Release Note

Multi-app-run now monitors processes and exits when dapr applications exit/stop.

**Comment by pravinpushkar** [comment]
This got closed as stale.
