### ISSUE TITLE
dapr uninstall -k --dev does not remove the list of registered components and configurations

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#1367]
After you run `dapr uninstall -k --dev` this should not only remove the container image for redis from the cluster, but it should also remove them as listed components.
 If you run `dapr components -k` after the uninstall command, you still see statestore and pubsub components listed 
It should also remove all application configuration files, at least the default appconfig one.

**Comment by mukundansundar** [comment]
This is by design, the components and configurations should ideally be removed only when you have `dapr uninstall -k --dev --all` IMO. Similar to removing all components and configurations that are removed when normal `dapr uninstall -k --all` is run and not when `dapr uninstall -k` is run.
