### ISSUE TITLE
Successful `dapr init` provides an aka.ms link

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/cli#1407]
Output for a successful `dapr init` ends with an `aka.ms` link, which is MSFT-specific. Should probably change to a bitly link?

**Output:**
> ✅  Downloading binaries and setting up components...  
✅  Downloaded binaries and completed components set up. 
ℹ️  daprd binary has been installed to /Users/user/.dapr/bin.  
ℹ️  dapr_placement container is running.  
ℹ️  dapr_redis container is running.  
ℹ️  dapr_zipkin container is running.  
ℹ️  Use docker ps to check running containers.  
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

**Comment by yaron2** [comment]
This was fixed in 1.14
