### ISSUE TITLE
dapr init -k --dev is in crash loop on redis init, failing redis component load

### ISSUE THREAD

**Issue by paulyuk** [dapr/cli#1436]
## Actual 
This quickstart repro's the issue.  
![image](https://github.com/user-attachments/assets/d801dae0-2a52-4fb8-b4b1-fd6a4793f74e)

This appears to only happen in the GH action runner, and not on my local kind installations.
https://github.com/dapr/quickstarts/actions/runs/9702023201/job/26776912327#step:18:82

## Expected
It should look like this fully passing
![image](https://github.com/user-attachments/assets/34a9bb8a-4ee6-4bba-9ca8-dac2ddc6e3e6)

## Release Note

RELEASE NOTE:

**Comment by antontroshin** [comment]
@paulyuk I've tested this locally and see that it works in the GH runners now, can we consider it fixed?
