### ISSUE TITLE
Segmentation violation on dapr init --slim

### ISSUE THREAD

**Issue by erkzswe** [dapr/cli#1471]
> /area runtime
Running into segmentation violation error on dapr init --slim command. Happens on two machines + bucket-pipelines build. Macos Sonoma 14.7.1 chip Apple m1 pro and docker image based on https://github.com/docker-library/python/blob/37a6827e0b7a9ef099cfdec5de305e3d4cea7331/3.11/bookworm/Dockerfile 

## What version of Dapr?
CLI version: 1.14.1
Runtime version: 1.14.4

## Expected Behavior
dapr init finishes correctly

## Actual Behavior
Running into error after initiating dapr with --slim flag.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10390c614]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
	/Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x34
github.com/hashicorp/go-version.(*Version).Compare(0x0, 0x14000472000)
	/Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x24
github.com/hashicorp/go-version.(*Version).GreaterThan(...)
	/Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub.func1({0x14001006000, 0x35bebe, 0x41e000})
	/Users/runner/work/cli/cli/pkg/version/version.go:124 +0x1cc
github.com/dapr/cli/pkg/version.GetVersionFromURL({0x140000581b0, 0x2f}, 0x1046f1480)
	/Users/runner/work/cli/cli/pkg/version/version.go:102 +0x254
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub({0x140000581b0?, 0x2b?})
	/Users/runner/work/cli/cli/pkg/version/version.go:107 +0x28
github.com/dapr/cli/pkg/version.GetDaprVersion()
	/Users/runner/work/cli/cli/pkg/version/version.go:63 +0x68
github.com/dapr/cli/pkg/standalone.Init({0x103d2871f, 0x6}, {0x103d2871f, 0x6}, {0x0, 0x0}, 0x1, {0x0, 0x0}, {0x0, ...}, ...)
	/Users/runner/work/cli/cli/pkg/standalone/standalone.go:215 +0x1b8
github.com/dapr/cli/cmd.glob..func11(0x14000694900?, {0x103d258f4?, 0x4?, 0x103d259c0?})
	/Users/runner/work/cli/cli/cmd/init.go:174 +0x2e8
github.com/spf13/cobra.(*Command).execute(0x1059a9600, {0x14000689460, 0x1, 0x1})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1059a70a0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/dapr/cli/cmd.Execute({0x104099988?, 0x102510430?}, {0x104099984?, 0x140000021a0?})
	/Users/runner/work/cli/cli/cmd/dapr.go:78 +0x164
main.main()
	/Users/runner/work/cli/cli/main.go:27 +0x3c
```

## Steps to Reproduce the Problem

run 
wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
dapr init --slim

**Comment by yaron2** [comment]
Can you try again now?

**Comment by erkzswe** [comment]
Resolved already

**Comment by vamsitp** [comment]
This issue has reappeared...
```md
Run dapr init
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x[19](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:20)60d33]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x33
github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc00042c000)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x25
github.com/hashicorp/go-version.(*Version).GreaterThan(...)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub.func1({0xc000b00000, 0x35fbdb, 0x41e000})
	/home/runner/work/cli/cli/pkg/version/version.go:124 +0x1d4
github.com/dapr/cli/pkg/version.GetVersionFromURL({0xc000256060, 0x2f}, 0x251aae8)
	/home/runner/work/cli/cli/pkg/version/version.go:102 +0x2b5
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub({0xc000256060?, 0x2b?})
	/home/runner/work/cli/cli/pkg/version/version.go:107 +0x1f
github.com/dapr/cli/pkg/version.GetDaprVersion()
	/home/runner/work/cli/cli/pkg/version/version.go:63 +0x6a
github.com/dapr/cli/pkg/standalone.Init({0x23dd9c1, 0x6}, {0x23dd9c1, 0x6}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}, ...)
	/home/runner/work/cli/cli/pkg/standalone/standalone.go:185 +0x21c
github.com/dapr/cli/cmd.glob..func11(0xc0006eb600?, {0x23dab80?, 0x4?, 0x23dac48?})
	/home/runner/work/cli/cli/cmd/init.go:173 +0x2e5
github.com/spf13/cobra.(*Command).execute(0x3a7c660, {0x3addd[20](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:21), 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x3a7a100)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/dapr/cli/cmd.Execute({0x[27](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:28)5432c?, 0x398a7a0?}, {0x2754328?, 0xc0000061a0?})
	/home/runner/work/cli/cli/cmd/dapr.go:78 +0x159
main.main()
	/home/runner/work/cli/cli/main.go:27 +0x2f
Error: Process completed with exit code 2.
```

**Comment by yaron2** [comment]
> This issue has reappeared...
> 
> ```
> Run dapr init
> ⌛  Making the jump to hyperspace...
> ℹ️  Container images will be pulled from Docker Hub
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x[19](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:20)60d33]
> 
> goroutine 1 [running]:
> github.com/hashicorp/go-version.(*Version).String(0x0)
> 	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x33
> github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc00042c000)
> 	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x25
> github.com/hashicorp/go-version.(*Version).GreaterThan(...)
> 	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298
> github.com/dapr/cli/pkg/version.GetLatestReleaseGithub.func1({0xc000b00000, 0x35fbdb, 0x41e000})
> 	/home/runner/work/cli/cli/pkg/version/version.go:124 +0x1d4
> github.com/dapr/cli/pkg/version.GetVersionFromURL({0xc000256060, 0x2f}, 0x251aae8)
> 	/home/runner/work/cli/cli/pkg/version/version.go:102 +0x2b5
> github.com/dapr/cli/pkg/version.GetLatestReleaseGithub({0xc000256060?, 0x2b?})
> 	/home/runner/work/cli/cli/pkg/version/version.go:107 +0x1f
> github.com/dapr/cli/pkg/version.GetDaprVersion()
> 	/home/runner/work/cli/cli/pkg/version/version.go:63 +0x6a
> github.com/dapr/cli/pkg/standalone.Init({0x23dd9c1, 0x6}, {0x23dd9c1, 0x6}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}, ...)
> 	/home/runner/work/cli/cli/pkg/standalone/standalone.go:185 +0x21c
> github.com/dapr/cli/cmd.glob..func11(0xc0006eb600?, {0x23dab80?, 0x4?, 0x23dac48?})
> 	/home/runner/work/cli/cli/cmd/init.go:173 +0x2e5
> github.com/spf13/cobra.(*Command).execute(0x3a7c660, {0x3addd[20](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:21), 0x0, 0x0})
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
> github.com/spf13/cobra.(*Command).ExecuteC(0x3a7a100)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/dapr/cli/cmd.Execute({0x[27](https://github.com/edgegrid/edgegrid/actions/runs/12102761515/job/33744876793#step:7:28)5432c?, 0x398a7a0?}, {0x2754328?, 0xc0000061a0?})
> 	/home/runner/work/cli/cli/cmd/dapr.go:78 +0x159
> main.main()
> 	/home/runner/work/cli/cli/main.go:27 +0x2f
> Error: Process completed with exit code 2.
> ```

Should be fixed now, a nightly build was released. We will fix that
