### ISSUE TITLE
Issue Running Hello World on Windows

### ISSUE THREAD

**Issue by awright18** [dapr/cli#164]
In step 3. of the 1. Hello-World sample. 
I execute this command 
 dapr run --app-id mynode --app-port 3000 --port 3500 node app.js 

## Expected Behavior
Starting Dapr with id mynode on port 3500
You're up and running! Both Dapr and your app logs will appear here.
...
## Actual Behavior
I get this output. 

Starting Dapr with id mynode. HTTP Port: 3500. gRPC Port: 60854
exec: "daprd.exe": executable file not found in %!P(MISSING)ATH%!(NOVERB)

## Steps to Reproduce the Problem
Prerequisites
Use Windows
Install dapr and its node v8+ dependency
Make sure c:\dapr is on your PATH
1. Download the samples repository
2.  Navigate to samples\1.hello-world 
3. execute dapr run --app-id mynode --app-port 3000 --port 3500 node app.js 

I suspect it has to do with either the exe trying to be executed is named incorrectly or the reference to the exe in these lines is incorrectly named.  https://github.com/dapr/cli/blob/3c6f2d0cb3a879cc5764a06ab66eb39726b0a55f/pkg/standalone/run.go#L94
On disk the exe is named dapr.exe

**Comment by awright18** [comment]
Thank you @LMWF, I guess I missed that step in the instructions, after double checking of course its there.

**Comment by Antaris** [comment]
@awright18 

I followed the instructions at https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-on-a-kubernetes-cluster for using Dapr locally with minikube.

Minikube is installed, and I can see my pods:

![image](https://user-images.githubusercontent.com/255906/69610747-58a07800-1024-11ea-8daf-7574a6d8487f.png)

However, `daprd.exe` still doesn't exist:

![image](https://user-images.githubusercontent.com/255906/69610792-6ce47500-1024-11ea-9759-8b862ab8aea5.png)

**Comment by LMWF** [comment]
@Antaris - have you run a `dapr init`?  If so is daprd.exe in c:\dapr?

**Comment by Antaris** [comment]
Hi,

Now, as per '', I am running `dapr init --kubernetes` as I am running this in minikube. Do you need to perform both `dapr init` and `dapr init --kubernetes`, because the docs do not suggest this.

`dapr init` fails as I don't have docker installed, just minikube. Do you require both?

**Comment by artursouza** [comment]
You don't need to do both. `dapr init` is to run locally and Docker is needed in the local machine. `dapr init --kubernetes` is to run on a Kubernetes cluster. The hello-world example has been updated recently.

To install on Windows and include daprd, the cli must be installed using the script below in an Admin PowerShell.
`powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"`

**Comment by n-ate** [comment]
I am encountering the missing executable too. I tried running the suggested script to no avail. I then uninstalled dapr and tried again (pictured below). Any advice on getting this executable properly setup and extant would be appreciated.

![image](https://user-images.githubusercontent.com/31741696/92957800-01865b00-f41e-11ea-8b30-4bf5c060412b.png)

**Comment by artursouza** [comment]
Please, add c:\dapr to your PATH env variable.

**Comment by n-ate** [comment]
That's not the problem. It is looking for daprd, which does not exist.
