### ISSUE TITLE
On Linux, permission denied even if docker is in sudoers.

### ISSUE THREAD

**Issue by chess-equality** [dapr/cli#168]
## Expected Behavior

`dapr init` should push through successfully.

In the documentation, only use `sudo dapr init` if you are using `sudo docker...`.

## Actual Behavior

Running `dapr init` I get:

`Error moving dapr binary to path: open /usr/local/bin/daprd: permission denied`

## Steps to Reproduce the Problem

You are using `docker...` commands and not `sudo docker...`.

Install Dapr as per Linux doc, then run `dapr init`.

**Comment by psibernetic** [comment]
I ran into this issue on Solus 4 since it does not ship with a /usr/local/bin directory.

I created the directory and then granted rwx permissions to the bin.

```bash
sudo chmod ugo+rwx bin
```

It worked fine after that, does that help?

**Comment by gazzu** [comment]
create a file
`sudo vim /usr/local/bin/daprd`
give the right permissions
`sudo chown <user>:<group> /usr/local/bin/daprd`
and then
`dapr init`

**Comment by chess-equality** [comment]
It's all good guys, I also did that.

But the point of this issue is all of that should be automated.

**Comment by LMWF** [comment]
If you install to the default /usr/local/bin, then `dapr init` must be run with sudo.  You can now specify alternate install paths if that works better instead: https://github.com/dapr/cli/pull/213

This change documents the new `install-path` arg:
https://github.com/dapr/docs/pull/262
