### ISSUE TITLE
Create Homebrew package for macOS

### ISSUE THREAD

**Issue by andmos** [dapr/cli#171]
## Describe the proposal
👋 Hi guys, 
Creating a formula for [homebrew](https://docs.brew.sh/Formula-Cookbook) would be nice, so the CLI package can be easily kept up-to-date with `brew upgrade`, and the installer itself as easy as `brew install dapr-cli` 👍

**Comment by yaron2** [comment]
Indeed!

**Comment by amanbha** [comment]
On the similar lines, I would like to suggest chocolatey for Windows and Snap for Linux.

**Comment by yaron2** [comment]
Yep, agreed.

**Comment by andmos** [comment]
Ok so I ran
`brew create https://github.com/dapr/cli/releases/download/v0.3.0/dapr_darwin_amd64.tar.gz --set-name dapr-cli`

And got this formula generated as `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dapr-cli.rb`.

```ruby
class DaprCli < Formula
  desc ""
  homepage "https://dapr.io/"
  url "https://github.com/dapr/cli/releases/download/v0.3.0/dapr_darwin_amd64.tar.gz"
  sha256 "c79fd18ca04059e2c65621d9db1cc102004e3f3a4f05af96004e8da3f7634332"

  def install
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
  end

  test do

    system "false"
  end
end
```

Running it in the interactive sandbox, the binary was there and functional. Anywhere I should PR this to, or is the information enough for someone on the team to get started?

**Comment by yaron2** [comment]
> Ok so I ran
> `brew create https://github.com/dapr/cli/releases/download/v0.3.0/dapr_darwin_amd64.tar.gz --set-name dapr-cli`
> 
> And got this formula generated as `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dapr-cli.rb`.
> 
> ```ruby
> class DaprCli < Formula
>   desc ""
>   homepage "https://dapr.io/"
>   url "https://github.com/dapr/cli/releases/download/v0.3.0/dapr_darwin_amd64.tar.gz"
>   sha256 "c79fd18ca04059e2c65621d9db1cc102004e3f3a4f05af96004e8da3f7634332"
> 
>   def install
>     system "./configure", "--disable-debug",
>                           "--disable-dependency-tracking",
>                           "--disable-silent-rules",
>                           "--prefix=#{prefix}"
>   end
> 
>   test do
> 
>     system "false"
>   end
> end
> ```
> 
> Running it in the interactive sandbox, the binary was there and functional. Anywhere I should PR this to, or is the information enough for someone on the team to get started?

This is great, thank you. We can use this to upload a brew package.

**Comment by andmos** [comment]
Should be quite easy to integrate with the [workflow](https://github.com/dapr/cli/blob/master/.github/workflows/dapr_cli.yaml) with some action for homebrew taps, like [this one](https://github.com/izumin5210/action-homebrew-tap).
