### ISSUE TITLE
standalone mode daprd and app startup coordination issue

### ISSUE THREAD

**Issue by yglcode** [dapr/cli#174]
## Expected Behavior
run go-sdk example client & caller according to Readme; with only exception of compiling code to binaries first.
expect caller will return logs about successful invoke, get, set etc..

## Actual Behavior
many times, caller will fail with "connection refused".

Since dapr fork two processes to run daprd and app (caller,client) concurrently, it happened that caller app starts up faster and try to connect before daprd listens at http & grpc service ports.
Use some hacking code here (https://github.com/yglcode/cli/blob/545558060b5a331050e9d639e3491505098af6ac/cmd/run.go#L107-L144) to verify/fix this scenario.

Need coordination between daprd & app startup sequence?

## Steps to Reproduce the Problem
at ubuntu18.04
check out github.com/dapr/go-sdk
compile example caller client first:
go build -mod=vendor ./example/caller
go build -mod=vendor ./example/client

run example client and caller according to Readme:
dapr run --app-id client --protocol grpc --app-port 4000 ./client
dapr run --app-id caller ./caller

**Comment by yaron2** [comment]
Hey yglcode, thanks for reporting.

We'll get that issue worked out this week.

**Comment by yaron2** [comment]
Actually, I've looked at your code. Do you want to PR this?

**Comment by yglcode** [comment]
Sure, i can add a PR. the current change is only hack fix for standalone mode. Could the issue exist for dapr sidecar and app container in pod? Should i  just PR this change for startup? since my branch has other code for installing dapr locally at linux without sudo.

**Comment by LMWF** [comment]
@yglcode - Thanks for the contribution.  I approved your linked PR for standalone.  Yes the issue could still happen in k8s because the start of containers within the same pod may be different every time.  

The best solution would be for the app to handle and retry appropriate errors.  However, `caller` here is a sample and we want to keep the same code relatively small and clear.

**Comment by mukundansundar** [comment]
@yaron2 is this issue still relevant?

**Comment by mukundansundar** [comment]
@yaron2
