### ISSUE TITLE
Improve uninstall command to clean up all docker images

### ISSUE THREAD

**Issue by youngbupark** [dapr/cli#176]
## Describe the proposal

This is the issue to track the [Gitter conversation](https://gitter.im/Dapr/community?at=5daa6b57dd688b6b67f4a1c6)
Improve uninstall command to clean up all docker images.

- [ ] Delete docker container, placement and redis, by cli uninstall option
- [ ] Provide the manual uninstall instruction

**Comment by youngbupark** [comment]
cc/ @chess-equality

**Comment by chess-equality** [comment]
Thanks @youngbupark @LMWF , will watch this space.

**Comment by hobpet** [comment]
@LMWF I think you closed both #686 and #176 issues as duplicate that were pointing to each other. One of them shall be reopened I think.

**Comment by LMWF** [comment]
@hobpet - these were both fixed by the PR above - https://github.com/dapr/cli/pull/184.  Is there some other issue you are seeing?

**Comment by hobpet** [comment]
Interesting, see this:
```
c:\dapr>dapr --version
cli version: 0.2.0
runtime version: 0.2.0

c:\dapr>docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
072eb72af52d        daprio/dapr         "./placement"            16 minutes ago      Up 16 minutes       0.0.0.0:6050->50005/tcp   dapr_placement
8724aa90b0d8        redis               "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes       0.0.0.0:6379->6379/tcp    dapr_redis

c:\dapr>dapr uninstall
Removing Dapr from your cluster...
Dapr has been removed successfully

c:\dapr>docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8724aa90b0d8        redis               "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes       0.0.0.0:6379->6379/tcp   dapr_redis

```
Shall I open a new issue?

**Comment by yaron2** [comment]
> Interesting, see this:
> 
> ```
> c:\dapr>dapr --version
> cli version: 0.2.0
> runtime version: 0.2.0
> 
> c:\dapr>docker ps
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
> 072eb72af52d        daprio/dapr         "./placement"            16 minutes ago      Up 16 minutes       0.0.0.0:6050->50005/tcp   dapr_placement
> 8724aa90b0d8        redis               "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes       0.0.0.0:6379->6379/tcp    dapr_redis
> 
> c:\dapr>dapr uninstall
> Removing Dapr from your cluster...
> Dapr has been removed successfully
> 
> c:\dapr>docker ps
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
> 8724aa90b0d8        redis               "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes       0.0.0.0:6379->6379/tcp   dapr_redis
> ```
> 
> Shall I open a new issue?

Try `dapr uninstall --all`

**Comment by LMWF** [comment]
Yeah please try yaron2's suggestion.  Redis is not removed on `dapr uninstall` by because users may want to keep the state.  `dapr uninstall --all` will remove it.

**Comment by hobpet** [comment]
Thanks, sorry for the confusion! RTFM as usual :)

```
c:\dapr>dapr uninstall --help
removes a dapr installation

Usage:
  dapr uninstall [flags]

Flags:
      --all              Remove Redis container in addition to actor placement container
  -h, --help             help for uninstall
      --kubernetes       Uninstall Dapr from a Kubernetes cluster
      --network string   The Docker network from which to remove the Dapr runtime
```
