### ISSUE TITLE
Docker processes still running after exited

### ISSUE THREAD

**Issue by sayboras** [dapr/cli#178]
## Expected Behavior
Docker processes must be stopped/killed once darp and app exited successfully

## Actual Behavior
Darp and App exited successfully, however docker processes are still running

## Steps to Reproduce the Problem
Run samples 1 `hello-world` and then send terminate signal

```bash
terminated signal received: shutting down
== DAPR == time="2019-10-22T21:37:32+11:00" level=info msg="dapr shutting down. Waiting 5 seconds to finish outstanding operations"
== DAPR == time="2019-10-22T21:37:32+11:00" level=info msg="stop command issued. Shutting down all operations"
✅  Exited Dapr successfully
✅  Exited App successfully

docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
9d6616adcd23        daprio/dapr         "./placement"            4 days ago          Up 8 hours          0.0.0.0:50005->50005/tcp   dapr_placement
0a47863f673c        redis               "docker-entrypoint.s…"   4 days ago          Up 8 hours          0.0.0.0:6379->6379/tcp     lucid_black
```

**Comment by amanbha** [comment]
@sayboras thats not a big, placement and redis containers are started when you do Dapr init. These 2 containers are needed for  local development with Dapr. Redis container is needed for providing state, pub sub capabilities out of box in Dev environment. Placement service container provides distribution of actors.
