### ISSUE TITLE
Dapr cli goes out of sync with the instances of dapr running.

### ISSUE THREAD

**Issue by amanbha** [dapr/cli#186]
Currently the info about running dapr isntances is stored by dapr cli in %temp%\dapr-run-data.ldj. 
This gets out of sync with actual instances which are running.
Change the cli so that when it reads the info from the file, it checks if the process is actutally running and if the process is not running. remove it from the file and continue.

**Comment by youngbupark** [comment]
@amanbha / looks like https://github.com/dapr/cli/pull/65/files already fixed this issue. Do you still see the same problem?

cc/ @yaron2

**Comment by amanbha** [comment]
I haven't seen it recently, it can be closed

**Comment by youngbupark** [comment]
Closing with #65
