### ISSUE TITLE
Proposal: dapr cli to fetch the logs of a running pod.

### ISSUE THREAD

**Issue by rajibmitra** [dapr/cli#189]
## Describe the proposal
Proposal: dapr cli to fetch the logs of a running pod.
As we discussed on the community call , we have decidede to open this issue and track the work from here. 
@youngbupark @msfussell

**Comment by yaron2** [comment]
What do you envision this to look like?

How about `dapr logs <app-id>`?

**Comment by rajibmitra** [comment]
Yes , this would be great. 
`dapr logs <app-id>`

**Comment by rajibmitra** [comment]
@yaron2 if its ok, I would like to implement that .

**Comment by yaron2** [comment]
That's more than OK, its even better :)

**Comment by RicardoNiepel** [comment]
It would be great if
`dapr logs <app-id>`
could be extended with an option to fetch logs only from the app, only from the dapr sidecar or from both

**Comment by yaron2** [comment]
@rajibmitra, any updates?

**Comment by yaron2** [comment]
Thanks!
