### ISSUE TITLE
Dapr CLI should exit when the application it runs exits

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#190]
## Expected Behavior

When the application run by the Dapr CLI exits, the Dapr CLI itself should exit.

## Actual Behavior

When the application run by the Dapr CLI exits, the Dapr CLI continues to execute until Ctrl+C is pressed.

## Steps to Reproduce the Problem

1. Create a (e.g. Express) Node.js application that immediately throws an exception
1. Run the application: `dapr run --app-id test-app node ./bin/www`
1. Note that the Dapr CLI reports the error but continues to run.

**Comment by yaron2** [comment]
There are some situations where you want to test new changes in your app, and would only want to issue one command to restart your app instead of restarting your app and relaunching the `dapr run` command.. WDYT?

**Comment by philliphoff** [comment]
Many development stacks already have a "watch" feature that can be layered with Dapr, so I'm not sure it's absolutely necessary.  You can already launch `daprd` on its own, which gives you the flexibility of starting the application separately--I do that when debugging the .NET Core service--so I don't think it's absolutely necessary to offer that via the Dapr CLI as well (though it might simplify the command line you currently have to pass to `daprd`).

For example, with .NET Core I could:

`dapr run --app-id <id> --app-port <port> dotnet run` to just run the application with Dapr, with the expectation that Dapr runs until the application exits.

`dapr run --app-id <id> --app-port <port> dotnet watch run` to run the application with Dapr, with the expectation that the stack's watch feature restarts the application on changes to its source, and Dapr runs until quit by the user.  The one downside to this approach is that Dapr doesn't know the application has been restarted, so it won't do things such as re-query for the list of subscribed topics.

I could see having a `dapr run` option like `--restart` that automatically restarts the application if it fails (rather than having the Dapr CLI also exit), but I don't know whether it's something I would personally use; typically I want to know that the application failed so that I can immediately go and diagnose/fix the issue, not just blindly restart the application.

In the case where the Dapr is running parallel to the application (whether started via the Dapr CLI, or otherwise), is there a way for the application to indicate something's changed (which would then trigger Dapr to re-query for subscriptions, re-query for actor registration, etc.)?  That might be useful for applications using their own "watch" features so help indicate to Dapr when they've restarted the application due to changes, and therefore prevent having to kill the Dapr CLI (or `daprd`)?

**Comment by aronchick** [comment]
Was a workaround established for solving for this now?

I'm doing this in Python3 and would love to have dapr exit when I do exit() in the script.

**Comment by WhoAteDaCake** [comment]
Agreed, it would be a very useful feature, as the moment it just treats it as 500 error, retries few times, then just stops. So if the sidecar is run within a docker container (I use it as a workaround for docker swarm), the container stays alive, even though the app has died.
