### ISSUE TITLE
Support tab completion

### ISSUE THREAD

**Issue by yanxinyuan** [dapr/cli#197]
## Describe the proposal
Dapr cli support tab completion.

**Comment by sravan-pallamreddy** [comment]
@yanxinyuan , @msfussell @amanbha , could you please elaborate the feature. I would like to try this.

**Comment by amanbha** [comment]
@yanxinyuan Could you please add more description to the issue?

**Comment by msfussell** [comment]
I thinkt @yanxinyuan is referring to auto-command completion of dapr CLI command using the Tab key. For example "dapr con" ->Tab would result in "dapr configurations" command
