### ISSUE TITLE
`dapr run` fails if `components` directory does not yet exist

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#198]
## Expected Behavior

In a folder without an existing `components` folder, `dapr run ...` starts the application, writing the Redis store YAML to a newly-created `components` directory.

## Actual Behavior

`dapr run` fails with the following error: `open /<path>/components: no such file or directory`

This appears due to [this line](https://github.com/dapr/cli/blob/master/vendor/github.com/dapr/dapr/pkg/components/standalone_loader.go#L33), which attempts to read a list of files without first verifying that the directory exists.

## Steps to Reproduce the Problem

Run `dapr run --app-id dapr-test --app-port 5000 dotnet run` in a folder without an existing `components` folder.

> The arguments passed to `dapr run` are immaterial as the error happens before Dapr ever attempts to do anything.

**Comment by yaron2** [comment]
This occuring with the master branch version, and not the latest binaries, correct?

**Comment by philliphoff** [comment]
@yaron2 Yes, sorry, when building from the `master` branch.  The `0.1.0` release binary works fine.

**Comment by yaron2** [comment]
Fixed, thanks for reporting this..

**Comment by akolliy1** [comment]
I am having a similar problem running dapr with Docker

## Steps to reproduce
an express-generator would give the exact source code. Then add the script below to a Docker file in the root directory of the project created with express-generator

## Actual Behavior
Running the command on the terminal works. Here is the CMD `dapr run --app-id nodeapp --app-port 4500 node ./src/bin/www`

But with the Docker file, I got an error `stat /root/.dapr/components: no such file or directory

Here is my docker file

```
FROM node:16
RUN npm install -g -f yarn

# Install dapr CLI
RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

# Install daprd
ARG DAPR_BUILD_DIR
COPY $DAPR_BUILD_DIR /opt/dapr
ENV PATH="/opt/dapr/:${PATH}"

WORKDIR /usr/awesome-project

COPY package*.json ./

RUN yarn

COPY . .

RUN yarn run babel ./src/ -d ./dist

# EXPOSE 4500
# CMD [ "node", "app.js" ]

# CMD ["node", "./src/bin/www-prod"]

# RUN dapr init

ENTRYPOINT ["dapr"]

CMD ["run", "--app-id", "nodeapp", "--app-port", "4500", "node", "./src/bin/www-prod"]
```
