### ISSUE TITLE
Simplify development and debugging setup using a dev container.

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#202]
For the relatively inexperienced Go developer (like me!), getting a development environment setup to build the Dapr CLI is non-trivial.  Making debugging work (in VS Code) is yet another not-so-straightforward task, even given the repository's [development guide](https://github.com/dapr/cli/blob/master/docs/development/development.md).  This setup also varies depending upon the platform.

If the developer is already using VS Code for editing, then one might make use of it's Dev Containers capability to open the repository within a Dev Container that has been pre-setup for building and debugging the Dapr CLI.  This could considerably reduce the barrier to entry for developers wishing to make a contribution but put off by having to first get a working build and debug environment.

**Comment by mukundansundar** [comment]
@philliphoff Is this issue still relevant considering there are docs for debugging in VS Code and dev container builds and such. If not can this be closed?

**Comment by philliphoff** [comment]
I think it's still relevant.  There have been Dev Container definitions created for other Dapr repos (e.g. [dapr/dapr](https://github.com/dapr/dapr/tree/master/.devcontainer)).  The idea was to encourage contributions by minimizing the setup required by new developers to get a build/run/test state.

**Comment by mukundansundar** [comment]
Ok ... so this issue is for dev container definitions for dapr/cli?

**Comment by philliphoff** [comment]
Yes, specifically for this repo.
