### ISSUE TITLE
`dapr list` does not include independent `daprd` instances

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#220]
## Expected Behavior

With 0.3.0 of the CLI and runtime:

1. Start `daprd` independently (e.g. `daprd --app-port 3000 ...`)
1. Start your application
1. Run `dapr list`

The `daprd` instance should be in the list returned by `dapr list`.

## Actual Behavior

The `daprd` instance is not in the list returned by `dapr list` (i.e. only instances started via `dapr run` are listed).

## Steps to Reproduce the Problem

See the expected behavior.

**Comment by sk593** [comment]
Just wanted to see if there was any progress on this issue. 

The Dapr VSCode extension (which helps users integrate Dapr into their applications by providing debugging capabilities, interaction with the Dapr runtime, etc) starts applications by invoking an instance of `daprd` directly and these running applications also do not show up in `dapr list`. The Tye extension also starts applications with a direct `daprd` call which yields similar results when running a `dapr list` command.

**Comment by orizohar** [comment]
@wcs1only @mukundansundar @yaron2 - addressing this issue will really help with some tooling issues that have been prioritized for the VS Code extension. Can this be given higher priority?

**Comment by AaronCrawfis** [comment]
Issue is when parsing the arguments starting at https://github.com/dapr/cli/blob/0a37376658ef83e8a1b49178cf4e6f1c93eb1dfc/pkg/standalone/list.go#L87

If an argument doesn't exist the entire process is dropped from the list instead of it displaying the process without the argument

**Comment by AaronCrawfis** [comment]
Also, once all parameters are set correctly, it fails when resolving cliPIDString: https://github.com/dapr/cli/blob/0a37376658ef83e8a1b49178cf4e6f1c93eb1dfc/pkg/standalone/list.go#L117

![image](https://user-images.githubusercontent.com/54363786/124179667-0200e880-da68-11eb-8e27-e985b7bcd319.png)

**Comment by AaronCrawfis** [comment]
And now realizing we pull the cli process as the list to return, not the daprd process https://github.com/dapr/cli/blob/0a37376658ef83e8a1b49178cf4e6f1c93eb1dfc/pkg/standalone/list.go#L144

We need to update the logic to include daprd instances without CLI processes.
