### ISSUE TITLE
Dapr CLI Stop command is not working.

### ISSUE THREAD

**Issue by MIKEPArA** [dapr/cli#223]
## Expected Behavior

running dapr stop --app-id [appId] from powershell command line should stop the working dapr application.

## Actual Behavior

When running the command I am receiving the following: 
failed to stop app id [appId]: exit status 1

## Steps to Reproduce the Problem

I am running the application via dapr CLI locally through powershell. Been doing it all week. It would terminate fine previously however now it is returning exit status 1 code. 

running dapr list command show the application:
 APP ID     HTTP    PORT    GRPC PORT  APP PORT COMMAND  AGE   CREATED                      PID
 [appId]    61476   61477   5001             dotnet run                     1d      2019-12-16 08:19.55   20548

**Comment by youngbupark** [comment]
dupe #222.
