### ISSUE TITLE
Can't seem to use invoke command to perform GET request

### ISSUE THREAD

**Issue by ryanvolum** [dapr/cli#224]
## Expected Behavior

Expect to be specify a GET endpoint when using invoke. For example, I currently cannot run: ```dapr invoke --app-id js -m randomNumber```, where `randomNumber` is the name of a GET endpoint (in this case in a Node app):

```js
app.get('/randomNumber', (_req, res) => {
    res.status(200).send({
        randomNumber: Math.ceil(Math.random() * 100)
    });
});
```

## Actual Behavior

I get an error indicating that it cannot find a POST endpoint by this name: 

```cmd
dapr invoke --app-id js -m randomNumber
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /randomNumber</pre>
</body>
</html>

App invoked successfully
```

**Comment by vsaroopchand** [comment]
Currently it only supports POST operations. Adding GET seems doable however the existing flag 'method' would need to accept the desired HTTP methods, not the actual API action. This of course poses a breaking change. I am happy to send a PR with suggestions on the desired behavior to minimize impact.

**Comment by yaron2** [comment]
> Currently it only supports POST operations. Adding GET seems doable however the existing flag 'method' would need to accept the desired HTTP methods, not the actual API action. This of course poses a breaking change. I am happy to send a PR with suggestions on the desired behavior to minimize impact.

Feel free to propose a PR for this.

**Comment by vsaroopchand** [comment]
You got it, I'll work on this.

**Comment by vsaroopchand** [comment]
With GET added, should I also add DELETE? What about PUT & PATCH?

**Comment by yaron2** [comment]
> With GET added, should I also add DELETE? What about PUT & PATCH?

Delete and Put are required, yes.

Patch is not used.

**Comment by vsaroopchand** [comment]
Ok, I will send a separate PR for Delete and Put.
