### ISSUE TITLE
multiple kube config files causes error on init

### ISSUE THREAD

**Issue by adhurwit** [dapr/cli#228]
## Expected Behavior
should be able to handle multiple kube config files. I had the default one .kube/config but also another .kube/microk8s.config

## Actual Behavior
error when running init --kubernetes

## Steps to Reproduce the Problem
Just have two different config files listed in KUBECONFIG env var in a path list (:)

This is pretty minor, edge. Looks like a decent amount of stuff to pull in from k8s client.. would have been good to have better error info issue #101 or maybe ability to specify config file to use.

**Comment by youngbupark** [comment]
Closing with #242
