### ISSUE TITLE
dapr uninstall did NOT remove installed redis container

### ISSUE THREAD

**Issue by Colstuwjx** [dapr/cli#232]
## Expected Behavior

We have been installed redis container when we typed `dapr init`, equally, we should also remove this redis container while typed `dapr uninstall`, BTW, `init` and `uninstall` seems not  be a pair words, I suggest change to sth like `init` and `destroy`.

## Actual Behavior

I typed `dapr uninstall`, and CLI prompt:

```
➜ dapr uninstall
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully
```

But the redis container is still running:

```
➜ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
d34dbc561646        redis               "docker-entrypoint.s…"   43 hours ago        Up About a minute   0.0.0.0:6379->6379/tcp              dapr_redis
```

## Steps to Reproduce the Problem

Try `dapr init` and `dapr uninstall`, you should see the same result.

**Comment by yaron2** [comment]
Like the docs mention, you should use `dapr uninstall --all`.

**Comment by Colstuwjx** [comment]
Little tricky for newbies, as it already works, I'd like to close this issue. Feel free to reopen this issue if we plan to change this behavior or tweak the words for cli using.

Thanks.
