### ISSUE TITLE
Dapr CLI command to create default standalone configuration files

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#234]
On the first invocation of `dapr run ...` in standalone mode, the CLI will generate a default set of configuration files (e.g. `redis.yaml` and `redis_messagebus.yaml`.  Certain tooling scenarios require invoking `daprd` directly, which require those configuration files.  There is currently no way to scaffold those files apart from `dapr run ...`.

Rather than fake an invocation of `dapr run` for the purposes of creating those files, or duplicating the scaffolding code within tooling, it would great if the CLI offered a command that would create/re-create those files, which could then be called by tooling.

E.g. something like:

`dapr create-config --output-path "./components"`

**Comment by mukundansundar** [comment]
@philliphoff Closing this since config file creation has moved to dapr init command. Please open a new/reopen this issue if this is still needed.
