### ISSUE TITLE
dapr stop should have a better error message 

### ISSUE THREAD

**Issue by LMWF** [dapr/cli#247]
`dapr stop` should give a better error message when --app-id is not provided.  Here is an example:

```
$ dapr stop nodeapp
failed to stop app id : couldn't find app id
```

The issue is that it expects `dapr stop --app-id nodeapp`.  

Making `dapr stop nodeapp` without including `--app-id` would help as well.

**Comment by akansh97531** [comment]
Hi @LMWF, I would like to work on this issue

**Comment by akansh97531** [comment]
Isn't it good to support stopping of multiple app instances by providing multiple appIDs?

For example  is nodeApp and pythonApp exists but javaApp doesn't
and if pythonApp coudn't be stopped for some reason.
The output would be like this -
``` 
$ dapr stop nodeApp javaApp pythonApp
stopping app.. : nodeApp
✅ nodeApp stopped successfully
stopping app.. : javaApp
❌ couldn't find app: javaApp
```
failed to stop app id : couldn't find app id

**Comment by amanbha** [comment]
@akansh97531 Are you planning to work on it?

**Comment by LMWF** [comment]
> Isn't it good to support stopping of multiple app instances by providing multiple appIDs?

Yes, I agree it would be good to allow the user to specify multiple apps to stop in one line.

**Comment by LMWF** [comment]
@akansh97531 - are you planning to work on this?
