### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/cli#249]
## Expected Behavior

No dapr app zombi processes should exist and the usage of dapr-cli should be predictable.

## Actual Behavior

Sometimes some zombie processes seem to be there but not shown and coming up at a later stage.

Also the usage of ```dapr list``` returns different results without scheduling something new.

## Steps to Reproduce the Problem

There was no other terminal or process open, running ```dapr``` cli calls or something else.

As you can see ```dapr list``` does not show up the app *subscriber* and I have not scheduled it.

```ps
PS C:\Sources\dapr-java-azure-sample> dapr list
No Dapr instances found.

PS C:\Sources\dapr-java-azure-sample> dapr run --app-id invokedemo --app-port 3000 --port 3005 -- mvn exec:java -Dexec.mainClass=com.dapr.azure.sample.invoke.DemoService -Dexec.args="-p 3000"
there's already a Dapr instance running with http port 3005

PS C:\Sources\dapr-java-azure-sample> dapr list
  APP ID      HTTP PORT  GRPC PORT  APP PORT  COMMAND               AGE  CREATED              PID   
  subscriber  3005       56464      3000      mvn exec:java -D ...  1d   2020-02-05 14:17.56  9412  

PS C:\Sources\dapr-java-azure-sample> dapr stop --app-id subscriber
app stopped successfully

PS C:\Sources\dapr-java-azure-sample> dapr list
No Dapr instances found.

PS C:\Sources\dapr-java-azure-sample> dapr --version
CLI version: 0.3.0 
Runtime version: 0.3.0
```

**Comment by yaron2** [comment]
Looking at the logs, this seems to work as expected.

The fact you were able to stop the Dapr app and then didn't see it on list means there was an instance running. This might happen if you close the terminal window without exiting properly, and is why we have the stop command there.

If you were unable to stop the app due to it not running but showing up in the list, then I'd say this is a zombie process.

**Comment by yaron2** [comment]
Can you reproduce this on every try?

If so, can you try it with a non Java app (like one of our J's samples)?

**Comment by RicardoNiepel** [comment]
@yaron2 no - it comes up unpredictable, do we have any log switch for the cli I can enable on each call for getting more information when it happens?

**Comment by LMWF** [comment]
There's no switch today for the CLI process' logging, but there ought to be.  If you see it again before we have a fix can you paste the contents of %temp%\dapr-run-data.ldj ?

**Comment by RicardoNiepel** [comment]
Here it is
```
{"DaprRunId":"8b5deb06-8bcb-4d5b-a35c-10a9c5f1999f","DaprHTTPPort":3005,"DaprGRPCPort":5001,"AppId":"hellogrpc","AppPort":5000,"Command":"waitfor FOREVER","Created":"2020-02-05T13:56:36.5999811+01:00","PID":30216}
{"DaprRunId":"fd7c92ec-4809-4f67-a028-d9fcd06a8e34","DaprHTTPPort":3005,"DaprGRPCPort":56464,"AppId":"subscriber","AppPort":3000,"Command":"mvn exec:java -D exec.mainClass=io.dapr.examples.pubsub.http.Subscriber -D exec.args=-p 3000","Created":"2020-02-05T14:17:56.591279+01:00","PID":9412}
{"DaprRunId":"6da4edb8-dc9c-4459-87ca-1f27cd8ea426","DaprHTTPPort":3006,"DaprGRPCPort":60228,"AppId":"publisher","AppPort":-1,"Command":"mvn exec:java -D exec.mainClass=io.dapr.examples.pubsub.http.Publisher","Created":"2020-02-05T14:19:41.2910305+01:00","PID":14796}
{"DaprRunId":"32c0679b-c478-444a-9c2e-47577b19543f","DaprHTTPPort":3005,"DaprGRPCPort":5001,"AppId":"subscriber","AppPort":3000,"Command":"waitfor FOREVER","Created":"2020-02-05T14:24:23.4108595+01:00","PID":36892}
{"DaprRunId":"2804fd00-cabf-42ed-b26c-4ae469c27b27","DaprHTTPPort":3005,"DaprGRPCPort":5001,"AppId":"inputbinding","AppPort":3000,"Command":"waitfor FOREVER","Created":"2020-02-05T14:54:19.7976314+01:00","PID":28108}
{"DaprRunId":"d066e59d-8cc8-482b-851d-805a222c86c1","DaprHTTPPort":3005,"DaprGRPCPort":5001,"AppId":"demoactorservice","AppPort":3000,"Command":"waitfor FOREVER","Created":"2020-02-05T15:07:02.2951281+01:00","PID":37208}
{"DaprRunId":"4a450c0e-b6a0-4e3c-9388-591ae816f53b","DaprHTTPPort":3006,"DaprGRPCPort":59283,"AppId":"demoactorclient","AppPort":-1,"Command":"mvn exec:java -D exec.mainClass=io.dapr.examples.actors.http.DemoActorClient","Created":"2020-02-05T15:08:18.4432132+01:00","PID":37544}
{"DaprRunId":"63e1cdc1-9b45-4370-838c-0773223e3ed9","DaprHTTPPort":3005,"DaprGRPCPort":5001,"AppId":"demoactorservice","AppPort":3000,"Command":"waitfor FOREVER","Created":"2020-02-05T15:09:21.3199781+01:00","PID":38512}
{"DaprRunId":"461eb562-a7f2-4ae0-82db-d17ac8e56afb","DaprHTTPPort":3006,"DaprGRPCPort":59508,"AppId":"demoactorclient","AppPort":-1,"Command":"mvn exec:java -D exec.mainClass=io.dapr.examples.actors.http.DemoActorClient","Created":"2020-02-05T15:10:14.8396275+01:00","PID":17124}
{"DaprRunId":"216d6a14-9b2f-48bf-b0c3-e4dd422e1393","DaprHTTPPort":3005,"DaprGRPCPort":61181,"AppId":"invokedemo","AppPort":3000,"Command":"mvn exec:java -pl=examples -D exec.mainClass=com.dapr.azure.sample.invoke.DemoService -D exec.args=-p 3000","Created":"2020-02-07T14:01:56.72064+01:00","PID":6088}
{"DaprRunId":"5591c1bf-000d-43a9-9053-3c73791bc72c","DaprHTTPPort":3006,"DaprGRPCPort":64170,"AppId":"Gazellegarnet-Quester","AppPort":-1,"Command":"mvn exec:java -pl=examples -D exec.mainClass=com.dapr.azure.sample.invoke.InvokeClient -D exec.args='message one' 'message two'","Created":"2020-02-07T14:02:05.4031139+01:00","PID":23900}
{"DaprRunId":"98bdf752-5436-4ea2-9d9e-785f80df0821","DaprHTTPPort":3005,"DaprGRPCPort":51848,"AppId":"invokedemo","AppPort":3000,"Command":"mvn exec:java -D start-class=com.dapr.azure.sample.invoke.DemoService -D exec.args=-p 3000","Created":"2020-02-07T14:45:38.4068419+01:00","PID":21728}
```

**Comment by LMWF** [comment]
Thanks for the file.  There's a lot of stale entries there for runs which aren't running anymore (lines with the same port or same app id's.

It looks like the problem is that when the `dapr stop` is used on windows it doesn't clean up this file.  Today this sends a taskkill to the instance of the CLI corresponding to the app we want to stop, but we don't have an additional handler so the file is not cleaned up.

A workaround today is to ctrl+c the CLI instead of using `dapr stop`.

**Comment by RicardoNiepel** [comment]
For reference:
I've only used dapr stop for the zombie, at normal development, I just ctrl+c.

Sometimes I just kill the terminal without ctrl+c before.
But even if this does not stops dapr, I would expect to see it with dapr list.

As you can see at the top, the first list doesn't show anything, the second shows something without started anything.

**Comment by LMWF** [comment]
> Sometimes I just kill the terminal without ctrl+c before.

Yes killing the terminal itself will cause this too.

**Comment by youngbupark** [comment]
@RicardoNiepel  Please try to run the install script to download 0.4.0-rc.0 version cli. This issue should be resolved.
