### ISSUE TITLE
Components folder is not only searched for yaml files

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/cli#250]
## Expected Behavior

I can add some other files, like ```readme.md``` into the *components/* folder.

In addition, if any file is corrupt, the error message should show the filename.

## Actual Behavior

```dapr run``` tries to read all files in the *components/* folder, even if these files are not ending with *.yaml*

Error message without indicating the filename:
```
time="2020-02-07T14:15:50+01:00" level=warning msg="error parsing file: error unmarshaling JSON: json: cannot unmarshal string into Go value of type v1alpha1.Component"
```

## Steps to Reproduce the Problem

Put a ```readme.md``` file into the *components/* folder.

**Comment by amanbha** [comment]
It should fixed by this PR https://github.com/dapr/dapr/pull/1299/files as it only looks for yaml files.
