### ISSUE TITLE
Add `dapr clear-events` command

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#252]
The `dapr` CLI currently has a `publish` command that sends an event to Dapr application subscribed to that event.  This is helpful when implementing/debugging/testing Dapr applications.  If the application fails to process the event, the event will be resent the next time the application starts.  (This makes sense in general, as Dapr is trying to accomplish at-least-once successful delivery.) During development, however, it's likely that the event format or event handling logic will not allow an event to ever be successfully processed.  These events will continue to pile up and can interfere with testing when those events are no longer applicable.

It would be nice to have a `dapr clear-events` command that will empty the standalone event queue, either as a whole or based on an individual topic.  Alternatively, perhaps an option on `dapr publish` for indicating that Dapr should simply attempt to deliver the message at most once and ignore failures (e.g. `--try`).

**Comment by mukundansundar** [comment]
@philliphoff Is this issue still relevant?
