### ISSUE TITLE
During dapr init, only installDaprBinary if it's actually necessary

### ISSUE THREAD

**Issue by bureado** [dapr/cli#255]
## Describe the proposal

In `Init()`, the `initSteps` always include `installDaprBinary`, and the logic of `installDaprBinary()` will almost always involve some form of privilege escalation in Linux since it involves creating, replacing or making `daprd` executable in a traditionally protected path such as `/usr/local/bin`.

This seems excessive, particularly for repeated executions of `dapr init`. It also prods the user to run `sudo dapr init` which in turn can trigger issues with some other commands that run during `Init()`.

The desired behavior would be for `installDaprBinary` to only be in `initSteps` if `daprd` doesn't exist or a new release is found, and `sudo` to be used only for the needed operations.

(For further details, if I switch from `docker` to `podman` and I hit this issue, then my `conmon` processes all run as `root`, even though they are perfectly capable not to.)

**Comment by yaron2** [comment]
This is undocumented (will fix that soon), but there's an optional `install-path` flag to `dapr init` to have the `daprd` binary be installed to a custom location.

In any case, it would be preferable to only install the binary if its a newer version or its a first time install.

**Comment by LMWF** [comment]
`--install-path` was supposed to be documented with 0.3 in https://github.com/dapr/docs/pull/262, but I accidentally closed it instead of merging it and didn't realize until now.  Reopening..
