### ISSUE TITLE
Is 0777 necessary for daprd?

### ISSUE THREAD

**Issue by bureado** [dapr/cli#256]
## Ask your question here

When `dapr init` fetches `daprd`, it installs it locally with permissions 0777. Wouldn't 0755 be sufficient? Trying to understand the logic here.

Perhaps the intent was to allow successive `dapr init` runs to allow patching the `daprd` binary in future releases?

See https://github.com/dapr/cli/blob/master/pkg/standalone/standalone.go#L312

Relates to #255

**Comment by yaron2** [comment]
In `makeExecutable` the permission can probably be relaxed to 0755.

**Comment by amanbha** [comment]
@bureado Does 0755 works in your branch, if yes, can we merge it back to this repo.
