### ISSUE TITLE
Local components files are overwritten

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/cli#262]
## Current situation

Dapr CLI reads all components from the directory and looks, if a ```state``` and a ```pubsub``` are defined ([SourceRef](https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L301)).
If not, it writes the default "messagebus.yaml" and "statestore.yaml" files - even if these files are already existing.

## Challenge

Because "messagebus.yaml" does not really indicate, if this is a ```pubsub``` component or maybe a ```binding``` component for Kafka/EventHub, the developer can easily choose to change the content of "messagebus.yaml" for configuring a ```binding``` component.

> Doing so will be overwritten each time Dapr CLI runs

## Describe the proposal

1. Using a better name for the default ```pubsub``` component, like "pubsub.yaml"
2. (in addition) The Dapr CLI should mention inside the log, that 
  "a ```state``` and/or ```pubsub``` component could not be found, and the default ones are created - existing files are overwritten"

**Comment by LMWF** [comment]
> If not, it writes the default "messagebus.yaml" and "statestore.yaml" files - even if these files are already existing.

To check - component files should not be overwritten by the CLI if they already exist in `/components`, are you observing otherwise?

**Comment by RicardoNiepel** [comment]
Yes - they are overwritten - as you can see at the referenced [sourcecode](https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L301) the file itself is not enough - it needs to be a pubsub component in it.
And this can be very confusing (details above)

**Comment by yaron2** [comment]
I just checked this and double validated: if `statestore.yaml` and `messagebus.yaml` are present, they will not get rewritten.

**Comment by yaron2** [comment]
The name of the file should probably change to `pubsub.yaml`

**Comment by RicardoNiepel** [comment]
@yaron2 please test the following:
1. change the ```pubsub.redis``` inside "messagebus.yaml" to ```bindings.redis```
2. execute Dapr CLI one more time

file gets overwritten for me and puts ```pubsub.redis``` back

**Comment by yaron2** [comment]
> @yaron2 please test the following:
> 
> 1. change the `pubsub.redis` inside "messagebus.yaml" to `bindings.redis`
> 2. execute Dapr CLI one more time
> 
> file gets overwritten for me and puts `pubsub.redis` back

The `type` field gets overwritten, yes. This is because the CLI is trying to ensure that a Redis pubsub and state store are present. The actual `.metadata` isn't getting rewritten.

**Comment by RicardoNiepel** [comment]
Have you changed it to something different from the defaults?
Looking at https://github.com/dapr/cli/blob/master/pkg/standalone/run.go#L230 I cannot find any diff/merge - it just writes the whole file.

As I stated at the beginng, I fully understand, why this file get's overwritten (=no default pubsub available), I still think
1. Using a better name for the default pubsub component, like "pubsub.yaml"
(in addition)
2. The Dapr CLI should mention inside the log, that
"a state and/or pubsub component could not be found, and the default ones are created - existing files are overwritten"

would be an improvement (from what I observed today with multiple people trying it out the first time)

**Comment by yaron2** [comment]
Agree, we'll push those changes.

**Comment by artursouza** [comment]
Working on this.

**Comment by artursouza** [comment]
This work has been completed and merge into master. It will be included in the next milestone: 0.5
