### ISSUE TITLE
Add -k for short notation when using dapr init

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#267]
There need to be -k for kubernetes

Usage:
  dapr init [flags]

Flags:
  -h, --help                     help for init
      --install-path string      The optional location to install Dapr to.  The default is /usr/local/bin for Linux/Mac and C:\dapr for Windows
      --kubernetes               Deploy Dapr to a Kubernetes cluster
      --network string           The Docker network on which to deploy the Dapr runtime
      --runtime-version string   The version of the Dapr runtime to install. for example: v0.1.0-alpha (default "latest")

**Comment by yaron2** [comment]
Closed with #282
