### ISSUE TITLE
dapr init --kubernetes for linux arm cluster doesn't work

### ISSUE THREAD

**Issue by youngbupark** [dapr/cli#271]
## Expected Behavior

1. can install dapr on linux arm cluster without any issue.

## Actual Behavior

1. failling to install dapr because dapr cli uses amd64 image on arm cluster

## Steps to Reproduce the Problem

1. dapr init --kubernetes on raspberry pi cluster

**Comment by youngbupark** [comment]
Switching multi-platform image is the best option - https://github.com/dapr/dapr/issues/1057

**Comment by yaron2** [comment]
Closing due to fix in https://github.com/dapr/dapr/issues/1057
