### ISSUE TITLE
Assign free port for metrics when in standalone mode

### ISSUE THREAD

**Issue by jjcollinge** [dapr/cli#275]
Once the [metrics PR](https://github.com/dapr/dapr/pull/1064/files) has been merged, we need to add behaviour to set the metrics port dynamically when running in standalone mode similar to how the HTTP and gRPC ports are handled: https://github.com/dapr/cli/blob/359e2eb8e36f7a5446af1a4569c94ddf2c30764b/pkg/standalone/run.go#L79

I think this is preferable to disabling the metrics as people can do that using `--enable-metrics false` easily enough and there will be scenarios where people want to use metrics for standalone deployments (even just for development purposes).

**Comment by artursouza** [comment]
See my PR. It solves it by simply using a random port.
