### ISSUE TITLE
Problem with dapr kubernetes and config when delimiter found in OS path

### ISSUE THREAD

**Issue by CarlosLanderas** [dapr/cli#277]
## Expected Behavior

Executing the command:

dapr list --kubernetes

Should list dapr instances in kubernetes

## Actual Behavior

`multiple kubeconfigs in KUBECONFIG environment variable - C:\Users\Carlos Landeras\.kube\config
`

## Steps to Reproduce the Problem

After debugging the CLI, it looks the **:** delimiter used is the one causing the problem. This demiliter is thought to split different kube config files but Windows hard drive paths are not compatible in it's current form:

![image](https://user-images.githubusercontent.com/16475649/75016484-62067880-548b-11ea-886b-60b7f42076bc.png)

**Comment by yaron2** [comment]
Closed with #279
