### ISSUE TITLE
Ability to define namespace to deploy dapr on init

### ISSUE THREAD

**Issue by jeffhollan** [dapr/cli#281]
## Describe the proposal

Today when you run `dapr init --kubernetes` it installs the operator in the default namespace. Would be nice if you could also pass in some flag to define another namespace.  `dapr init --kubernetes --namespace dapr`

**Comment by yaron2** [comment]
Yeah we get that a lot.

Do you think maybe we should have Helm be the only way to install and remove the init for Kubernetes?

**Comment by jeffhollan** [comment]
Yeah I think that'd work and likely scale better as more features are added cause folks can pass in values.  For me it's the same as I have helm3 so either are as easy.

**Comment by abhirockzz** [comment]
> Yeah we get that a lot.
> 
> Do you think maybe we should have Helm be the only way to install and remove the init for Kubernetes?

IMO, `dapr init --kubernetes` simplifies the "getting started" experience and should not be removed. Cases such as these (`default` namespace) can be clearly documented as constraints (although it is relatively simple to implement). Just my 2 cents

**Comment by yaron2** [comment]
> > Yeah we get that a lot.
> > Do you think maybe we should have Helm be the only way to install and remove the init for Kubernetes?
> 
> IMO, `dapr init --kubernetes` simplifies the "getting started" experience and should not be removed. Cases such as these (`default` namespace) can be clearly documented as constraints (although it is relatively simple to implement). Just my 2 cents

It's already documented as constraints, yes. But that still causes some anguish. I think we'll start by enabling non-default namespaces and take it from there.
