### ISSUE TITLE
Dapr init modifies a lot of path environment variables in Windows 10 1909

### ISSUE THREAD

**Issue by nicro950** [dapr/cli#286]
## Expected Behavior

I expected when running dapr init from the command line to not edit any of the path environment variables. Maybe just add one to the dapr location

## Actual Behavior

dapr init removes some path, duplicate others and moves them arround. Almost looks like it takes some of the ones from the system environment vairables and mixes them with user environment variables.

## Steps to Reproduce the Problem
* Have dapr sit in a folder which is in the path variable but not the c:\dapr directory
* Run dapr init when c:\dapr is not in the environment vairables

**Comment by youngbupark** [comment]
@nicro950 Thanks for the report. We will fix in the next version.

I just want to make sure that the user path environment variable is changed by [one liner script](https://github.com/dapr/cli/blob/82520e0df8ef21c76087b9bde1fc1a432a88f764/install/install.ps1#L86-L95) instead of `dapr init`. Isn't your path environment variable changed when you run the script?

**Comment by nicro950** [comment]
I never ran the script since i have configured a local folder in the path variables where i have all such tools, to keep them in one place. I think i also tested with having C:/dapr in the path variable but it still changed the local user environment variables when i ran dapr init

**Comment by youngbupark** [comment]
> I never ran the script since i have configured a local folder in the path variables where i have all such tools, to keep them in one place. I think i also tested with having C:/dapr in the path variable but it still changed the local user environment variables when i ran dapr init. @youngbupark

Thanks for the clarification. We will fix this bug in the next release.

**Comment by vinayada1** [comment]
@nicro950 - I tried to reproduce this issue. I saved the output of set and env commands before I ran dapr init and after I ran dapr init with installPath: c:\tools\dapr

The only diff I see is below which is related to the current working dir:-
C:\Tools\dapr>cd \temp

C:\Temp>diff env1.txt env3.txt
1c1
< !C:=C:\Tools\dapr
---
> !C:=C:\Temp

C:\Temp>diff set1.txt set3.txt

Could you please give detailed steps to repro the issue? Also, would help if you could point to the env variables you see are being modified

**Comment by nicro950** [comment]
Hi @vinayada1 The original issue was using the dapr 0.4.1 dapr cli version, but i am still able to reproduce it with the dapr 0.7.0 cli. I also managed to reproduce this issue on multiple computers. It is only the Path environment variable I see is changed, and I noised it because the commands I normally uses was suddenly not available anymore. 

The first thing I did was installing docker desktop for windows. The I created a folder named bin within the user home directory. Then I added this new folder to the user environment variable named path like `{other paths...};%USERPROFILE%\bin`, to make it available from the command line. Then I restarted windows explorer to make it pick up the path changes. I then started cmd and executed `echo %PATH%`, and made sure there was no reference to `C:\dapr`. Then I executed `dapr init` from a random location, in my case it was the user home directory, since that is the default start position from CMD.

dapr then produces the following output:

```
Making the jump to hyperspace...
WARNING: could not delete run data file
Downloading binaries and setting up components...
Installing Dapr to c:\dapr
Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
```

Now the Path variable under User variables contains a lot of different paths, which should not be there. 

From my point of view it looks like the following is happening:

On windows the %PATH% and $env:Path is a concatenation of the path variable found under the user and system variables in `Windows system properties > environment Variables...` . Then when dapr init is running and detecting that `c:/dapr` is not in the path environment variables, then it takes the output of `%PATH%`, appends `;c:/dapr` and sets the `%PATH%` variable again. This results in windows setting the User Variable Path, with the complete content of both the system and user variables. It also looks like there is a 1024 byte limit some place on this string, since the new content of the PATH variable is only 1024 characters long and then a hard stop. 

It looks like something like this is happening https://stackoverflow.com/a/26947177 and the truncation: https://stackoverflow.com/a/10411111

**Comment by nicro950** [comment]
If i should make a wild guess, then this is the problematic code:
https://github.com/dapr/cli/blob/6c89df56f72b9ce235721be8459a1c4762c5869f/pkg/standalone/standalone.go#L534

**Comment by vinayada1** [comment]
Hi, I am still unable to reproduce the issue. Would help if you could add the following details:-
1. What Windows version are you using?
2. Could you add a console log which shows the output of echo %PATH%/$env.Path, run DAPR init and then echo %PATH% command again. (When I run these steps, I only see the dapr path gets appended. I even tried making my path very long and I do not even see the truncation that you mentioned.
PS C:\Users\vinayada> echo $env:Path | Measure-Object -Character
Lines Words Characters Property
----- ----- ---------- --------
                  2777

**Comment by nicro950** [comment]
I Am using windows 19.09 and here is a screen shot of the problem. As you can see from the screen shot i had to open a new powershell window to load the new path values, but the output increased with over 500 characters before and after dapr init.

![image](https://user-images.githubusercontent.com/1964338/83619084-a5dd4380-a58b-11ea-96f3-e2aa3514b654.png)

**Comment by vinayada1** [comment]
Thanks! I was able to repro the path truncation issue and have submitted a PR to fix it. However, I am unable to repro the unwanted path variables part of the issue.
