### ISSUE TITLE
`dapr` should be able to indicate whether the runtime has been initialized

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#290]
The CLI does not have a means to indicate that Dapr has been initialized (in standalone mode).  `dapr --version` will show the same value both before and after `dapr init` as well as after `dapr uninstall`.  It would be useful (e.g. for tooling troubleshooting purposes), if there was a programmatic way to verify that `dapr init` has been run and that Dapr appears to be in a good state.

Some options:

 - `dapr --version`:  returns both the CLI and runtime versions as well as a flag that indicates the runtime has been initialized.
 - `dapr [init] --verify`: returns a flag that indicates that the runtime has been initialized

**Comment by mukundansundar** [comment]
@philliphoff After Uninstall the output is as follows 
```
$ dapr --version
CLI version: 0.11.0
Runtime version: n/a
```

After the init 
```
 $ dapr --version
CLI version: 0.11.0
Runtime version: 0.11.2
```

Can you verify? Does that solve this issue?

**Comment by mukundansundar** [comment]
@philliphoff any update on this? Can this be closed if it is resolved?

**Comment by KoditkarVedant** [comment]
Just add to the point - I was getting started with dapr. When I ran the `dapr init` it failed with some network error.

```
PS C:\Users\Vedant> dapr init
Making the jump to hyperspace...
Downloading binaries and setting up components...
error downloading daprd binary: stream error: stream ID 3; PROTOCOL_ERROR
```

when I ran the `dapr --version` it was showing the CLI version but the Runtime version was `n/a`. Which I feel fine.

But I did not find any way to verify if the initialization was correct. and running the `dapr init` doesn't initialize if the environment is not already initialized.

I had to `dapr uninstall` and `dapr init` which fixed fixed the issue.

**Comment by herowk** [comment]
Someone like me may use `sudo dapr init`,the Runtime version also showing `n/a`. Do this after init:`sudo cp -r /root/.dapr /home/herowk` then we got this:
`herowk@debian:~$ dapr --version
CLI version: 1.1.0-rc.1 
Runtime version: 1.1.2
`.
Done!

**Comment by philliphoff** [comment]
I think the current behavior now meets my needs, so we can close this.  Of course, it'd be better if the output was in JSON so as to be more consumable.  :-)
