### ISSUE TITLE
Get the manifest file dapr-operator.yaml from releases

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/cli#292]
## Describe the proposal

Right now the dapr-operator.yaml file is getting pulled in from https://daprreleases.blob.core.windows.net/manifest/dapr-operator.yaml

In order to allow different manifest files for different release versions it's decided to place the file in release assets as discussed in this [thread](https://github.com/dapr/cli/pull/291). To work along with the proposed change the CLI has to be updated to pull from correct location.

**Comment by yaron2** [comment]
lgtm
