### ISSUE TITLE
Improve the error message and make uninstall work when Docker is not running

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#300]
Docker was not running on my machine and I went to uninstall Dapr and got this confusing error message.
C:\MVP\daprapp>dapr uninstall
Removing Dapr from your cluster...
WARNING: could not delete run data file
Error removing Dapr: could not delete (dapr_placement,daprio/dapr)

 Either 
1) Provide a hint that Docker should be enabled to uninstall Dapr (like the init command below) or
2) Can you remove Dapr's containers when docker is not running (probably not)

C:\MVP\daprapp>dapr init
Making the jump to hyperspace...
WARNING: could not delete run data file
could not connect to Docker. Docker may not be installed or running

**Comment by artursouza** [comment]
Alternative 1 can be added to the error message.
Alternative 2 (I assume you mean not to try to delete containers) should remain as is. The user might not be aware that docker is not running and the uninstallation would give the impression of success if we skip the container removal. Giving a clear error message (alternative 1) seems to be a better message to customers.

**Comment by ksashikumar** [comment]
@msfussell @artursouza  This seems to be related to https://github.com/dapr/cli/issues/330. As I've worked on the issue, I've raised another PR for this. Could you please review? 🙂

**Comment by pruthvidhodda** [comment]
Thanks for your contribution @ksashikumar :)
