### ISSUE TITLE
dapr init - separate dapr binary installation and dev env setup

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#301]
Today `dapr init` performs two main actions:
1. Install latest dapr binaries on the local machine
2. Sets up an environment for a dev to work on a local machine with docker containers (redis and placement)

Not all dapr standalone scenarios are dev environments - if a user chooses to run dapr on a bare metal or virtual machine and would like to incorporate dapr installation in a bootstrap script such as cloud-init they don't require the installations that occur in step (2) above.

The proposal:
`dapr init` installs binaries only [(1) above]
`dapr init --dev-env` installs binaries and spins up necessary containers for a local dev env [(1)+(2) as today]

In the future we might want to provide the user with more nuanced control on which local components are used for local dev env (memcache instead of redis as well as other variants of other components)

**Comment by msfussell** [comment]
You may want to consider flags the other way around to prevent breaking change.

**Comment by amanbha** [comment]
> You may want to consider flags the other way around to prevent breaking change.

Yes, mostly developers use cli to get started on dev machines so by default it should setup containers as well.

**Comment by orizohar** [comment]
I've been thinking of this further and I think this could actually help with handling the feedback we are getting about the perceived dependency between dapr and docker. If you think of the funnel of how a newcomer discovers and tries dapr for the first time `dapr init` is the first command they run and it fails if they don't have docker. The causal user who doesn't deep dive into our docs or just skims it will deduce there is a dependency there.

I would actually go further and remove the dev env setup from dapr init altogether and instead add a docker-compose file ensuring users run a separate flow to setup the dev env. This would make this more explicit.

@yaron2  - you and I discussed this a little. Your thoughts?

**Comment by subesokun** [comment]
I think the VS Code dev container setup would also benefit from this. It feels quite strange that it spins up Docker containers on my host that are living outside of the dev container's docker-compose context.

At least this would significantly decrease the complexity of the Dockerfile. Instead, it'd be great if you can add the Redis and dapr placement service as part of the docker-compose service definition (no need for docker-in-docker anymore) or just use an existing remote service in the dev container (like a redis and a placement service that is already running somewhere on the host)

**Comment by orizohar** [comment]
This issue will be addressed by the planned epic for developer experience updates https://github.com/dapr/cli/issues/343
Note the current decision is to leave the default behavior and add a flag that will allow skipping Docker steps in `dapr init`

**Comment by amanbha** [comment]
closing this as epic for developer experience updates #343 is completed
