### ISSUE TITLE
Support `--log-as-json` though cli

### ISSUE THREAD

**Issue by LMWF** [dapr/cli#308]
Support `--log-as-json` though cli.  Currently this only works in kubernetes.

**Comment by lgmorand** [comment]
@youngbupark  is it not linked to #515 and thus included in 1.0.0RC2 ?

**Comment by youngbupark** [comment]
> @youngbupark is it not linked to #515 and thus included in 1.0.0RC2 ?

looks like it is dupe. @mukundansundar @yaron2

**Comment by youngbupark** [comment]
@lgmorand #515  will be included in rc3.
