### ISSUE TITLE
'make lint' fails with error - no such linter "gomnd"        

### ISSUE THREAD

**Issue by abhirockzz** [dapr/cli#310]
## Expected Behavior

`make lint` to work

## Actual Behavior

(go version - `go version go1.13.8 darwin/amd64`)

Results in this error

```
golangci-lint run --fix
ERRO Running error: no such linter "gomnd"        
make: *** [lint] Error 3
```

## Steps to Reproduce the Problem

- Clone `https://github.com/dapr/cli` to `$GOPATH`
- cd `$GOPATH/github.com/dapr/cli`
- run `make lint`

**Comment by youngbupark** [comment]
you may not install the latest go(1.14) and golinterci :) please install the latest version

**Comment by abhirockzz** [comment]
I have it installed already - https://github.com/golangci/golangci-lint Just  upgraded to go 1.14 as well - same issue

Would be great to have it documented as pre-requisites here - https://github.com/dapr/cli/blob/master/docs/development/development.md#prerequisites

**Comment by abhirockzz** [comment]
FYI, just updated the `golangci-lint` version (to `1.23.8`) and `make lint` worked fine. Thank you! @youngbupark 

```
golangci-lint version
golangci-lint has version 1.23.8 built from 76a82c6 on 2020-03-04T14:27:24Z
```

**Comment by youngbupark** [comment]
> FYI, just updated the `golangci-lint` version (to `1.23.8`) and `make lint` worked fine. Thank you! @youngbupark
> 
> ```
> golangci-lint version
> golangci-lint has version 1.23.8 built from 76a82c6 on 2020-03-04T14:27:24Z
> ```

Thanks for the update!
