### ISSUE TITLE
Failed to compress with wget command

### ISSUE THREAD

**Issue by SnowflyW** [dapr/cli#318]
https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
Extraction command extraction in install.sh is missing parameters

installFile() {
    **tar xf "$ARTIFACT_TMP_FILE" -C "$DAPR_TMP_ROOT"**
    local tmp_root_dapr_cli="$DAPR_TMP_ROOT/$DAPR_CLI_FILENAME"

    if [ ! -f "$tmp_root_dapr_cli" ]; then
        echo "Failed to unpack Dapr CLI executable."
        exit 1
    fi

    chmod o+x $tmp_root_dapr_cli
    runAsRoot cp "$tmp_root_dapr_cli" "$DAPR_INSTALL_DIR"

    if [ -f "$DAPR_CLI_FILE" ]; then
        echo "$DAPR_CLI_FILENAME installed into $DAPR_INSTALL_DIR successfully."

        $DAPR_CLI_FILE --version
    else 
        echo "Failed to install $DAPR_CLI_FILENAME"
        exit 1
    fi
}

**Comment by SnowflyW** [comment]
> > 正在下载https://github.com/dapr/cli/releases/download//dapr_linux_amd64.tar.gz ...
> 
> @SnowflyW似乎未检测到发行版本。需要以下信息来进一步调查此问题：
> 
> 1. 这个问题经常发生吗？
> 2. 以下命令的输出：
> 
> ```shell
> curl -s https://api.github.com/repos/dapr/cli/releases   | grep \“ tag_name \”  | grep -v rc | AWK ' NR == 1 {打印$ 2} '  |   SED -n ' S / \ “\（。* \）\”/ \ 1 / P '
> ```
> 
> 1. 以下命令的输出：
> 
> ```shell
> wget -q --header = “接受：application / json ” -O-https : //api.github.com/repos/dapr/cli/releases | grep \“ tag_name \”  | grep -v rc | AWK ' NR == 1 {打印$ 2} '  |   SED -n ' S / \ “\（。* \）\”/ \ 1 / P '
> ```

I haven't succeeded in using WGet on the center since I paid attention to dapr. All of them are manually downloading the tar.gz package for installation

**Comment by SnowflyW** [comment]
> @SnowflyW Ah I see. we will look at the wget option and then fix add the option. Thanks for this report.
> 
> cc/ @pruthvidhodda

👌

**Comment by Haishi2016** [comment]
@SnowflyW 是这样的，我们的脚本通过以下命令来寻找最新版本信息：

> curl -s https://api.github.com/repos/dapr/cli/releases  | grep \"tag_name\" | grep -v rc | awk 'NR==1{print $2}' |  sed -n 's/\"\(.*\)\",/\1/p'

这个命令读取https://api.github.com/repos/dapr/cli/releases页面然后搜索带tag_name的行进行解析。 @pruthvidhodda 的意思是上述命令行在您的环境中似乎运行失败了，所以想看看你如果单独运行这个命令的输出是什么。

我怀疑是不是api.github.com无法访问的问题。请您单独运行一下上述命令并报告运行结果， 谢谢！

**Comment by pruthvidhodda** [comment]
@SnowflyW  any update?

**Comment by SnowflyW** [comment]
@pruthvidhodda Wait for 0.7.0 to be officially released

**Comment by pruthvidhodda** [comment]
Closing this for now. @SnowflyW feel free to open this if you are still facing the issue.
