### ISSUE TITLE
[Proposal] Add flag to provide custom components directory path for `dapr run`

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#321]
Today, `dapr run` looks for a `components` folder in its current directory and if it does not exist it creates it in the current path. There may be scenarios (e.g. CSE Icebreaker challenge) where a developer has a components directory with yaml files they would like to reuse in a different path. 
This would just be exposing the `daprd` equivalent flag in the CLI.

Proposed addiitonal flag to `dapr run`:
```bash
--components-path <Path to components directory>
```

**Comment by ksashikumar** [comment]
@orizohar I'm getting started with contributing to Dapr. This issue looks like a good one to start with. I've raised PR for this. Could you please review? Thanks 🙂

**Comment by amanbha** [comment]
Thanks for the contribution @ksashikumar, will review it

**Comment by orizohar** [comment]
Thanks for picking this up @ksashikumar !

**Comment by LMWF** [comment]
Looks like #225 is related.

**Comment by orizohar** [comment]
> Looks like #225 is related.

Yes, thanks for linking this. I think the issue described there of not creating the components folder by default is still worth considering.

**Comment by ksashikumar** [comment]
Issue #225 makes sense to me. I'd like to work on that as well, but should I work on the same PR ?

**Comment by LMWF** [comment]
I think separate PRs would be better, but it doesn't matter too much.

**Comment by amanbha** [comment]
Yes, lets do the changes in separate pr.
