### ISSUE TITLE
Add namespace column to config cmd output

### ISSUE THREAD

**Issue by shalabhms** [dapr/cli#325]
When fetching the default configuration using the below command :

dapr configurations --kubernetes

Getting the 2 entries of default config, as shown in screen shot.

![image](https://user-images.githubusercontent.com/29718984/80851393-55fb0d80-8bd6-11ea-8ba3-df52cd394cb4.png)

> /area runtime

**Comment by mukundansundar** [comment]
With the changes done in https://github.com/dapr/cli/issues/487, I think this issue has been addressed in a different way. Please reopen a new issue if this is still needed.
