### ISSUE TITLE
Webhook to trigger Homebrew release

### ISSUE THREAD

**Issue by artursouza** [dapr/cli#328]
Homebrew release for Dapr CLI is 100% automated as of now. On the other hand, it "wakes up" every 5 minutes to check for the latest Dapr CLI release to determine if a new release is needed. Instead of this busy waiting solution, use a webhook instead. Changes:

1. Change Homebrew repo (dapr/homebrew-tap) for Dapr CLI to trigger on a webhook instead of cron.
2. Change Dapr CLI release to trigger the webhook above as the last step, using the Dapr Bot GitHub Token.

**Comment by youngbupark** [comment]
@artursouza we can use [repository_dispatch](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch) event in homebrew-tap workflow.

dapr-bot uses this way to trigger e2e test :) I thought it is working only for the same repo. but we can trigger the event to the other repos :)

1. trigger code - https://github.com/dapr/dapr/blob/876298f7b5673ce89c8d4f38fa4e809d18b18e0c/.github/workflows/dapr-bot.yml#L87-L92
2. event trigger in e2e test work flow - https://github.com/dapr/dapr/blob/876298f7b5673ce89c8d4f38fa4e809d18b18e0c/.github/workflows/dapr-test.yml#L11

We can also use deployment event but it seems more complicated.
