### ISSUE TITLE
Cannot run dapr init - redis container port already in use

### ISSUE THREAD

**Issue by maiorfi** [dapr/cli#329]
I upgraded dapr cli and runtime to 0.7 and pruned all docker stuff (docker system prune -a) in order to pull brand new images.

Whenever I do __dapr init__ I get:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint dapr_redis (e0b00920a18f320d9d3f18f742079997c12018e0897f16271b4b9b8992976481): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use.
```

With __dapr uninstall --all__:
```
ℹ️  Removing Dapr from your cluster...
WARNING: could not delete run data file
❌  Error removing Dapr: could not delete (dapr_placement)
```

Any suggestion?

Thanks!

**Comment by yaron2** [comment]
Can you run docker ps and see if you have Redis running? If so, remove that container and run init again.

**Comment by maiorfi** [comment]
I tried, but the weird fact is that if I run a _docker ps_ (as well as _docker ps -a_) before running _dapr init_ I do not have any container running.
After having run _dapr init_ with aforementioned response (i.e. "...listen tcp 0.0.0.0:6379: bind: address already in use...", running _docker ps_ still does not list any running container BUT a _docker ps -a_ shows:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
3bfe423c2694        redis               "docker-entrypoint.s…"   5 seconds ago       Created                                 dapr_redis
```
It seems that dapr is trying to run same container twice or so.

What about error returned by _dapr uninstall --all_ ?

Thanks!

**Comment by LMWF** [comment]
Can you clarify which OS this is?

>What about error returned by dapr uninstall --all ?

This message:
>❌  Error removing Dapr: could not delete (dapr_placement)

is coming from:

``` 
docker rm --force dapr_placement
```

Can you run that command after a `dapr init` and paste the output?  And when you run `dapr init`, are you specifying any additional args?

Also opened #330.

**Comment by maiorfi** [comment]
I'm working on ElementaryOS (based on Ubuntu 18.04). Preliminary tests made with first 2 tutorials worked fine with previous (i.e. 0.6) dapr version.

Running _docker rm --force dapr_placement_ returns:
```
Error: No such container: dapr_placement
``` 
I'm running _dapr init_ without any other parameter.

Thanks.

**Comment by maiorfi** [comment]
I completely removed docker, then I reinstalled it. After doing that, running dapr init didn't return any error and I was able to run "hello world" dapr sample again without issues. Meanwhile, I spotted dapr runtime was updated to 0.7.1, although I don't think this is so relevant for issue solving.

**Comment by anubhuti24** [comment]
> I completely removed docker, then I reinstalled it. After doing that, running dapr init didn't return any error and I was able to run "hello world" dapr sample again without issues. Meanwhile, I spotted dapr runtime was updated to 0.7.1, although I don't think this is so relevant for issue solving.

This doesn't work for me. I removed my docker completely still after running dapr init command  their is an issue and address is already in use.

**Comment by alikleit** [comment]
Shouldn't there be a way to set the Redis port? Having a running Redis with that port and deleting or stopping it is not a solution.. @maiorfi  @yaron2
