### ISSUE TITLE
dapr run for Java application allows to specify the JRE location to use

### ISSUE THREAD

**Issue by JMayrbaeurl** [dapr/cli#331]
## Describe the proposal
Provide the possiblity to specify the JRE that should be used to run a Java application by offering a command line parameter to specify the JRE location

**Comment by mukundansundar** [comment]
@JMayrbaeurl I feel that being able to specify a particular JRE location is outside the scope of `dapr` CLI. In addition it can be done by setting/modifying an env var just before executing the `dapr` cli command. 

@yaron2 thoughts?
