### ISSUE TITLE
CLI install path hard coded  + dapr init failing

### ISSUE THREAD

**Issue by lgmorand** [dapr/cli#335]
## Expected Behavior
There are two parts where install path is hardcode

1- The powershell [install script](https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1) is hard coded to C:/dapr

`powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"`

This command line may fail is C:/ does not exist (yeah, it happens :))

2- dapr init (in [standalone pkg](https://github.com/dapr/cli/blob/master/pkg/standalone/standalone.go)), will also fail even with --install-path given, because parameter is ignored at some point (see comment 3)

## Idea
1- Add a parameter to the script to specify the path
2- Fix dapr init

**Comment by lgmorand** [comment]
Basically, the script just need to be modified like this (see below). I wanted to do a PR, but I don't find the correct way to pass as parameters using IWR + IEX. whatever I tried, it refused the parameter, but calling the script itself with parameter works fine

`powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"`


Script modified
`param ($path)

$ErrorActionPreference = 'stop'
$DaprRoot="c:\dapr"
if (![string]::IsNullOrWhiteSpace($path)) {
    $DaprRoot = $path
}
$DaprCliFileName = "dapr.exe"
$DaprCliFilePath = "${DaprRoot}\${DaprCliFileName}"`

**Comment by lgmorand** [comment]
Ok, that's worse than I thought. 
The dapr init command fails because it seems that path is also hard coded
"mkdir c:: The system cannot find the path specified."

Even with **dapr init --install-path "f:\dapr"** parameter, same error.
Within standalone.Init( ), I found this code. could this cause my error ?
```
if runtime.GOOS == daprWindowsOS {
		p = path_filepath.FromSlash("c:/dapr")
	}
```

**Comment by LMWF** [comment]
I have a fix for 2, but not 1.

**Comment by LMWF** [comment]
@lgmorand thanks for reporting, we've fixed the 2 problems.

**Comment by lgmorand** [comment]
@vinayada1 I see you have fixed the path in the powershell file (and I learnt a new way to declare parameter thx :D)
but could you update the readme please (https://github.com/dapr/cli/tree/master/install)
I don't know how to pass the parameter, with the given powershell command. Everytime "path" parameter not found.

thanks
