### ISSUE TITLE
dapr uninstall leaves redis container behind

### ISSUE THREAD

**Issue by trondhindenes** [dapr/cli#336]
## Expected Behavior
I would expect `dapr init && dapr uninstall` not to leave any containers behind, or at least tell me what to do in order to clean up completely.

## Actual Behavior
Redis container is left behind

## Steps to Reproduce the Problem
See "expected behavior".

**Comment by yaron2** [comment]
This is documented on the CLI page:

dapr uninstall --all

Closing for now, feel free to open again if needed.
