### ISSUE TITLE
Create components folder on dapr init

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#340]
This is part of developer experience improvements to main CLI flows

- [ ] `dapr init` creates the default `components` folder in the dapr installation path with default yaml files as created today by `dapr run` when not found.

- [ ] `dapr run` no longer creates `components` folder and instead looks for a components folder in the installation directory

- [ ] A user who wants to use a different path can do so via `--components-path` flag per https://github.com/dapr/cli/issues/321 

- [ ] `dapr uninstall` should remove the default `components` directory

**Comment by amanbha** [comment]
This would need updates to samples which use non-default component yamls.

**Comment by vinayada1** [comment]
@orizohar : Slight change in the implementation to what you have mentioned. 
1. A hidden components folder will be created during "dapr init" under install path and the default yaml files will be placed here.
2. If the user specifies a different --components-path during "dapr run", that will override the default path.
3. The hidden path is to hide the default behavior of adding files to the components folder from the user

**Comment by orizohar** [comment]
> @orizohar : Slight change in the implementation to what you have mentioned.
> 
> 1. A hidden components folder will be created during "dapr init" under install path and the default yaml files will be placed here.
> 2. If the user specifies a different --components-path during "dapr run", that will override the default path.
> 3. The hidden path is to hide the default behavior of adding files to the components folder from the user

Thanks @vinayada1. What is the location of the hidden path? is it different for different OS?
Regarding bullet (3) - I think it would be good if a user knows where these are in case they want to edit the default yamls but that can be handled by documentation.
Also, as per the issue description uninstall should remove the hidden folder even without a --all flag since the user may not be aware it was created on init

**Comment by vinayada1** [comment]
@orizohar : Creating the hidden components folder under the install directory makes sense to me.

**Comment by LMWF** [comment]
Sounds good to me.  

Clarification on item 2: if the user is using a components folder outside of the one inside the install path it will not get deleted by an uninstall, correct?

**Comment by vinayada1** [comment]
No, I think only the default one should get deleted upon uninstall because the user is not even aware it exists.

**Comment by LMWF** [comment]
Ok.

**Comment by orizohar** [comment]
> No, I think only the default one should get deleted upon uninstall because the user is not even aware it exists.

Correct. `uninstall` should undo what is done in `init`. if during `dapr run` a user uses their own components directory that is unrelated to init/uninstall flow

**Comment by vinayada1** [comment]
- Discussed this further and will create the default components folder under ~/.dapr or %HOMEPATH%/.dapr following what tools such as docker, kubectl are doing. Following from the same, not marking the attribute for the components folder hidden on Windows
