### ISSUE TITLE
New CLI command `dashboard`

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#341]
Add a `dapr dashboard` command that spins up the dapr dashboard:
https://github.com/dapr/dashboard

**Comment by gdhuper** [comment]
If this issue is still up for grabs, I'd like to take a stab at it. Thanks

**Comment by orizohar** [comment]
> If this issue is still up for grabs, I'd like to take a stab at it. Thanks

Thanks @gdhuper for jumping on this! Can I assign this to you so we can keep track on who is working on this?

**Comment by gdhuper** [comment]
Np. Yes, you can go ahead and assign this to me.

**Comment by yaron2** [comment]
Thanks @gdhuper for jumping on this.

Essentially we'd like to do what the linkerd CLI does with `linkerd dashboard`, so it might be worth while to get a pointer from them :)

**Comment by yaron2** [comment]
Reference: https://github.com/linkerd/linkerd2/blob/master/cli/cmd/dashboard.go

**Comment by gdhuper** [comment]
Thanks for the link @yaron2. This is a great starting point. I will post questions / discussions as I develop a better understanding of this issue/cli code.

**Comment by gdhuper** [comment]
@yaron2  @orizohar @youngbupark Here is a draft of what the help prompt might look like for `dapr dashboard -h`: 
```bash
$ dapr dashboard -h
Launches Dapr dashboard service to view information about running applications

Usage:
  dapr dashboard [flags]

Flags:
  -a, --address string   the address at which to serve the dashboard (default "127.0.0.1")
  -h, --help             help for dashboard
  -o, --open             opens dashboard in the browser
  -p, --port int         the HTTP port for the dashboard to listen on (default 8080)

```
After doing initial research on `linkerd dashboard` and `kubectl proxy`, these were some of the common flags provided with the dashboard command. However, if I am not mistaken dapr/dashboard does not currently support --port or --address. So I was wondering what flags do we wanna support for the first iteration or if there are any plans to extend dapr/dashboard to allow configuring port and address?

**Comment by orizohar** [comment]
Thanks for doing this research @gdhuper . I think for this initial implementation of the command we can stick to what is already supported (default port and address). Moving forward if we need to ad additional functionality to the dashboard we can do so.

**Comment by gdhuper** [comment]
> Thanks for doing this research @gdhuper . I think for this initial implementation of the command we can stick to what is already supported (default port and address). Moving forward if we need to ad additional functionality to the dashboard we can do so.

Gotcha! How does this look for first iteration?
```
$ dapr dashboard -h
Runs the Dapr dashboard on local machine or on a Kubernetes cluster

Usage:
  dapr dashboard [flags]

Flags:
  -h, --help         help for dashboard
  -k, --kubernetes   Deploy Dapr dashboard to a Kubernetes cluster
  -o, --open         Open Dapr dashboard in a browser
```

**Comment by gdhuper** [comment]
@yaron2 In this [issue](https://github.com/dapr/dashboard/issues/13)  you mentioned that `dapr dashboard` would spin up dashboard dockerless, does that mean we wanna download dashboard binaries with `dapr dashboard` and spin it up? If thats the case, how would that work for kubernetes?

**Comment by yaron2** [comment]
> @yaron2 In this [issue](https://github.com/dapr/dashboard/issues/13) you mentioned that `dapr dashboard` would spin up dashboard dockerless, does that mean we wanna download dashboard binaries with `dapr dashboard` and spin it up? If thats the case, how would that work for kubernetes?

@gdhuper  For k8s we should port-forward, for local mode we might probably want to download a zip to a local dir and open it from there.
As discussed, lets tackle Kubernetes first.

Any updates there?

**Comment by gdhuper** [comment]
> @gdhuper For k8s we should port-forward, for local mode we might probably want to download a zip to a local dir and open it from there.
> As discussed, lets tackle Kubernetes first.
> 
> Any updates there?

Yes, so I've got the dashboard deployment working on k8s, working on port-forwarding right now. Should be a PR up soon this week for review. 

Question in general, for k8s operations such as port-forwarding, is it recommended to use client API or `kubectl`? Thanks

**Comment by orizohar** [comment]
> > @gdhuper For k8s we should port-forward, for local mode we might probably want to download a zip to a local dir and open it from there.
> > As discussed, lets tackle Kubernetes first.
> > Any updates there?
> 
> Yes, so I've got the dashboard deployment working on k8s, working on port-forwarding right now. Should be a PR up soon this week for review.
> 
> Question in general, for k8s operations such as port-forwarding, is it recommended to use client API or `kubectl`? Thanks

Yes. This is what we are doing for Zipkin 
https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/zipkin.md#viewing-tracing-data

**Comment by orizohar** [comment]
Looks like this can make the v0.9.0 release. Tagging it so we track it as such
