### ISSUE TITLE
Spin up Zipkin container on dapr init

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#342]
Add Zipkin as a container that is setup as part of the dapr local dev environment when running `dapr init` to allow users to easily do tracing locally.
See https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/zipkin.md

**Comment by mukundansundar** [comment]
@orizohar As seen in https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/zipkin.md, does this also involve creating the component `zipkin.yaml` and the configuration `tracing.yaml` files when `dapr run` is called similar to the redis configurations created  apart from creating/downloading the zipkin docker container on `dapr init`? 

If so would it make sense to create a `deploy` directory under which the `tracing.yaml` configuration can be stored?

**Comment by orizohar** [comment]
> @orizohar As seen in https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/zipkin.md, does this also involve creating the component `zipkin.yaml` and the configuration `tracing.yaml` files when `dapr run` is called similar to the redis configurations created apart from creating/downloading the zipkin docker container on `dapr init`?
> 
> If so would it make sense to create a `deploy` directory under which the `tracing.yaml` configuration can be stored?

Yes, if we are spinning up this by default, yaml files need to be created during `dapr init`. Please note the default directory for such files is being changed per  https://github.com/dapr/cli/issues/340 so please connect with @vinayada1 to ensure your work aligns with hers

**Comment by mukundansundar** [comment]
@orizohar  @yaron2 @youngbupark @msfussell These are my thoughts on enabling spinning up Zipkin on `dapr init`. 

Use the `~/.dapr/components` to create the `zipkin.yaml` file on init. 
Create a new folder `~/.dapr/config` for the configuration file `tracing.yaml`
Spin up `openzipkin/zipkin` container on `dapr/init`

My question now is: do we need to create the `tracing.yaml` file in the `dapr` config folder? 
Current process for config I can see specifically for tracing is to disable sampling by default. 

Is the idea here to enable tracing on standalone dapr run by default? That would involve a change where in on `dapr run` the default tracing config file path will be passed and if the user overrides it with a `--config` flag, then the default path is replaced. 

Is that the intended behavior for this change?

**Comment by yaron2** [comment]
IMO yes, that is the expected behavior.

So to put this in explicit terms:

We enable tracing by default for every `dapr run` command.
If the user wants to change the tracing component and/or tracing config, they override with `--components-path` and `--config` to specify their custom tracing component and custom config file.

**Comment by amanbha** [comment]
> > @mukundansundar In addition to proposed changes above, This config folder will follow the logic of components, created with dapr init and removed with dapr uninstall?
> 
> Created with init, yes, and the entire .dapr root dir should be removed with uninstall.

Yes, sounds good!

**Comment by mukundansundar** [comment]
@yaron2 @amanbha @orizohar 
We will need to specify the host for zipkin or else hardcode it in the configuration file. For this either we can add a flag for the run command 
`--exporters-zipkin-host` or `--zipkin-host` similar to `--redis-host` or have to hardcode to localhost. 
I would prefer to add the flag for the run command. Any suggestions on the naming?

**Comment by mukundansundar** [comment]
Is the default behavior supposed to remove the default components folder, `dap_placement` and `dapr_redis` containers on `dapr init`?

https://github.com/dapr/cli/blob/master/cmd/init.go#L42

**Comment by orizohar** [comment]
> @yaron2 @amanbha @orizohar
> We will need to specify the host for zipkin or else hardcode it in the configuration file. For this either we can add a flag for the run command
> `--exporters-zipkin-host` or `--zipkin-host` similar to `--redis-host` or have to hardcode to localhost.
> I would prefer to add the flag for the run command. Any suggestions on the naming?

Seeing as this is meant for helping with local development scenarios, my position is to just use `localhost` I'm not sure we need to add a flag. For other scenarios the developer can create their own components folder and make their own custom configuration

**Comment by yaron2** [comment]
> > @yaron2 @amanbha @orizohar
> > We will need to specify the host for zipkin or else hardcode it in the configuration file. For this either we can add a flag for the run command
> > `--exporters-zipkin-host` or `--zipkin-host` similar to `--redis-host` or have to hardcode to localhost.
> > I would prefer to add the flag for the run command. Any suggestions on the naming?
> 
> Seeing as this is meant for helping with local development scenarios, my position is to just use `localhost` I'm not sure we need to add a flag. For other scenarios the developer can create their own components folder and make their own custom configuration

No flags, please.

Th address is specified in the component YAML and can be changed by the user if needed. By default should be localhost, the same as with Redis.

**Comment by mukundansundar** [comment]
> Is the default behavior supposed to remove the default components folder, `dap_placement` and `dapr_redis` containers on `dapr init` in standalone mode ?
> 
> https://github.com/dapr/cli/blob/master/cmd/init.go#L42

@yaron2

**Comment by mukundansundar** [comment]
> > Is the default behavior supposed to remove the default components folder, `dap_placement` and `dapr_redis` containers on `dapr init` in standalone mode ?
> > https://github.com/dapr/cli/blob/master/cmd/init.go#L42
> 
> @yaron2

Created a separate issue to discuss https://github.com/dapr/cli/issues/380
