### ISSUE TITLE
Support to load components from URL in addition to local path 

### ISSUE THREAD

**Issue by mchmarny** [dapr/cli#351]
Dapr already supports path argument for location of the components directory. Adding support for URL would enable loading components from remote bucket/share

**Comment by mchmarny** [comment]
The area to review: https://github.com/dapr/cli/blob/e498de9f7dd92c30aa592d6e6761dc924bb53cc2/pkg/standalone/run.go#L297-L305

**Comment by orizohar** [comment]
@mchmarny, the initial issue opened for this (https://github.com/dapr/dapr/issues/1587) was marked as P2 for 0.9 does that triage still apply?

**Comment by mchmarny** [comment]
Yes. With v0.8 we have the `--components-path` flag on CLI but when running daprd directly in environments where volume mounts are antipattern its helpful to be able to load the file from remote object store or even github repo
