### ISSUE TITLE
Dapr cli looking for components folder in the wrong path

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#361]
## Expected Behavior

The application successfully persists the state.

## Actual Behavior
Getting the following logs : 
== APP == Got a new order! Order ID: 41

== APP == Failed to persist state.

Additionally when the app is run seeing the following error logged as a warning

== DAPR == time="2020-06-05T16:05:34.860674-07:00" level=warning msg="failed to load components: open ./components: no such file or directory" app_id=nodeapp instance=MININT-9H9J6NC.europe.corp.microsoft.com scope=dapr.runtime type=log ver=0.8.0-rc.0

## Steps to Reproduce the Problem

download the 0.8.0-rc.0 version of cli and runtime 
Follow the samples/1.hello-world sample from master branch https://github.com/dapr/samples/tree/master/1.hello-world

The RC cli is looking for `./components` by default when the default path has been modified to `~/.dapr/components`

**Comment by mukundansundar** [comment]
Copying the `components` folder back inside the `samples/1.hello-world` folder works

**Comment by pruthvidhodda** [comment]
Closing this as it's tracked here: https://github.com/dapr/dapr/issues/1655
