### ISSUE TITLE
cli should pass components-path to daprd.

### ISSUE THREAD

**Issue by amanbha** [dapr/cli#366]

**Comment by mukundansundar** [comment]
Would it make sense here to pass the argument all the time from the cli to runtime or only when it is overridden by the user?

**Comment by amanbha** [comment]
> Would it make sense here to pass the argument all the time from the cli to runtime or only when it is overridden by the user?

it will be all the time.

**Comment by yaron2** [comment]
It needs to pass the default path every time and override it with the user supplied path. That's what we also discussed on the other issue.
