### ISSUE TITLE
Hide components directory from users for dapr run

### ISSUE THREAD

**Issue by yaron2** [dapr/cli#38]
Use temp dirs.

**Comment by akansh97531** [comment]
Hi @amanbha , @yaron2 
Would it be possible for you to elaborate a bit more.

**Comment by amanbha** [comment]
@akansh97531 I believe that this would not be an issue which we want to fix now as users have become accustomed to having a components folder when using cli and thats where they put their additional components file. Moving it to a temp folder will make it tricky for users to find a components folder and files to it on a per app basis.  I think this [issue](https://github.com/dapr/cli/issues/225) is more relevant, @yaron2  What do you think?

**Comment by msfussell** [comment]
Fixed. The default components folder is now under $HOME/.dapr/ folder on Linux and similar for Windows
