### ISSUE TITLE
Standalone dapr init calls uninstall first. Uninstall should remove .dapr folder and daprd

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#380]
This issue has two parts: 

Part 1

As it exists now when `dapr init` is called, the uninstall all code is also run first before dapr is initialized in standalone mode. 

https://github.com/dapr/cli/blob/master/cmd/init.go#L42

Is this the expected behavior as this removes all component configurations previously saved by the user in the default components folder every time dapr init is called. 

This also has the effect of removing the `dapr_redis` container and recreating it on dapr init. 

Shouldn't the user make the decision to call `dapr uninstall --all` or `dapr uninstall` before running `dapr init` making sure that necessary configurations are backed up or to make sure dapr redis is not uninstalled.

Part 2

On running `dapr uninstall --all` for the standalone mode, the behavior now is to remove the components folder, placement container and redis container. 

Shouldn't it also remove the `daprd`. binary and also the `.dapr` folder leaving only the `dapr`cli remaining?

**Comment by pruthvidhodda** [comment]
> Part 2
> 
> On running `dapr uninstall --all` for the standalone mode, the behavior now is to remove the components folder, placement container and redis container.
> 
> Shouldn't it also remove the `daprd`. binary and also the `.dapr` folder leaving only the `dapr`cli remaining?

We don't mention that `dapr uninstall` removes the daprd binaries anywhere in docs - it just says that it removes placement service.

But ideally I prefer that it removes the binary and .dapr folder as well - just something to discuss.

**Comment by LMWF** [comment]
Yes `dapr uninstall` should reverse everything dapr init did.  Really the only thing left afterwards ought to be the cli and maybe redis if `--all` was not specified.

`--all` exists to make deletion of redis explicit in case the user was using it for something else as well - to not surprise them.

**Comment by youngbupark** [comment]
> Yes `dapr uninstall` should reverse everything dapr init did. Really the only thing left afterwards ought to be the cli and maybe redis if `--all` was not specified.
> 
> `--all` exists to make deletion of redis explicit in case the user was using it for something else as well - to not surprise them.

I agree on deleting daprd when running `dapr uninstall` without `--all` option.

But `.dapr` directory in user home would not be deleted without `--all` because users can put their own configurations into `.dapr`. They would be unhappy if they own custom configurations are gone. 

So deleting `.dapr` with --all option makes more sense to me. 

cc/ @orizohar @msfussell @yaron2 @amanbha

**Comment by yaron2** [comment]
> > Yes `dapr uninstall` should reverse everything dapr init did. Really the only thing left afterwards ought to be the cli and maybe redis if `--all` was not specified.
> > `--all` exists to make deletion of redis explicit in case the user was using it for something else as well - to not surprise them.
> 
> I agree on deleting daprd when running `dapr uninstall` without `--all` option.
> 
> But `.dapr` directory in user home would not be deleted without `--all` because users can put their own configurations into `.dapr`. They would be unhappy if they own custom configurations are gone.
> 
> So deleting `.dapr` with --all option makes more sense to me.
> 
> cc/ @orizohar @msfussell @yaron2 @amanbha

lgtm

**Comment by amanbha** [comment]
> But `.dapr` directory in user home would not be deleted without `--all` because users can put their own configurations into `.dapr`. They would be unhappy if they own custom configurations are gone.

This looks good, lets explore this option a little bit more. What will be dapr init behavior if .dapr already exists? Would it not create files in .dapr or would it still go and create(and update) the default files.

**Comment by LMWF** [comment]
I think we should be more explicit about what .dapr is for.  It could be:

1. this is the default and read-only and the user should not modify it.  If they want to they should copy it, make changes, and point to the changes using --component path
2. it's the default but we let the user do what they want with it, including overwriting it.

2 is easier and more resembles the behavior today, but is more error prone.  1. is cleaner (you always have a copy of the default) but it may take more effort from the user if they want to copy from it/modify/and point.

When we started discussing .dapr, I thought the behavior would be 1.

**Comment by amanbha** [comment]
Yes, lets keep .dapr for the default ones. If user wants custom one, he uses --components-path and we direct users towards it.
Users can put in .dapr (as we cant stop it), but it will be cleaned on dapr uninstall.

**Comment by mukundansundar** [comment]
> Part 1
> 
> As it exists now when `dapr init` is called, the uninstall all code is also run first before dapr is initialized in standalone mode.
> 
> https://github.com/dapr/cli/blob/master/cmd/init.go#L42
> 
> Is this the expected behavior as this removes all component configurations previously saved by the user in the default components folder every time dapr init is called.
> 
> This also has the effect of removing the `dapr_redis` container and recreating it on dapr init.
> 
> Shouldn't the user make the decision to call `dapr uninstall --all` or `dapr uninstall` before running `dapr init` making sure that necessary configurations are backed up or to make sure dapr redis is not uninstalled.

@amanbha @LMWF @msfussell @yaron2 
Any thoughts on this one? 

Leaving the user to manually call `dapr uninstall --all` before calling `dapr init` and failing if there are issues makes it more explicit than implicitly deleting the `redis` container and `.dapr` or `./dapr/components` folder.

**Comment by LMWF** [comment]
Yes, fail dapr init if dapr is already installed and print a message with actionable instructions or a prompt to uninstall for them.

**Comment by mukundansundar** [comment]
Based on the discussions in this thread, 

My proposal is this: 
1. We remove the call yo uninstall on init. https://github.com/dapr/cli/blob/master/cmd/init.go#L42 
If we find a previous version of `daprd` already installed or the folder `.dapr` already available, we error out asking user to run `dapr uninstall --all` before running `dapr init` for standalone installation. 
2. Also on `dapr uninstall --all` we would remove the `daprd` binary also. We will update the docs to make note of this behavior. 

Does that seem an ok? @amanbha @LMWF @msfussell @yaron2

**Comment by amanbha** [comment]
yes, that seems fine to me.

**Comment by msfussell** [comment]
Yes. Look good to me.
