### ISSUE TITLE
Dapr uninstall command should take --runtime-version flag to get correct versioned operator yaml

### ISSUE THREAD

**Issue by youngbupark** [dapr/cli#395]
The root cause of the issue is that Dapr uninstall command is not currently taking --runtime-version flag to specifically find the right versioned operator.yaml, due to which uninstallation is failing to remove dashboard which is added in the current RC release.

## Expected Behavior

No Error message.

## Actual Behavior

```
youngp@MININT-Q8GQR8F dapr % dapr uninstall --kubernetes
ℹ️  Removing Dapr from your cluster...
❌  Error removing Dapr: is Dapr running? uninstall does not remove Dapr when installed via Helm
```

Additionally the dapr-dashboard deployment is not removed on uninstall from the cluster.

## Steps to Reproduce the Problem

1. install dapr to k8s via cli
```
dapr init --runtime-version=v0.9.0-rc.0 -k
```

2. uninstall 
```
dapr uninstall --kubernetes
```

**Comment by mukundansundar** [comment]
@youngbupark Additionally the `dapr-dashboard` deployment is not removed on uninstall from the cluster.
