### ISSUE TITLE
Provide version flag for uninstall command in standalone mode

### ISSUE THREAD

**Issue by shalabhms** [dapr/cli#399]
Provide --runtime-version flag for `dapr uninstall` command in standalone mode

**Comment by pruthvidhodda** [comment]
Just trying to understand the use case. We can only have one daprd binary in a path so what is the use of this flag in standalone mode?

**Comment by shalabhms** [comment]
@pruthvidhodda , you are right. I opened this issue to track for standalone while we were making fix for Kubernetes mode.
But looks like this is not needed. Closing the issue.
