### ISSUE TITLE
Change default behavior of dapr uninstall -k

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/cli#403]
## Describe the proposal

Right now `dapr uninstall -k` tries to uninstall dapr using the dapr-operator.yaml from latest release. Instead the **default** behavior should be to find the installed dapr version using kube client and use the dapr-operator.yaml from that specific release to uninstall dapr.

**Comment by mukundansundar** [comment]
@yaron2 Is this issue still relevant? Kubernetes install and uninstall using Dapr CLI now uses the helm charts and a release name `dapr`.

**Comment by msfussell** [comment]
@yaron2

**Comment by yaron2** [comment]
No, this can be closed. we are no longer using a template file.
