### ISSUE TITLE
Prefix placement binary with dapr

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#406]
## Describe the proposal
In the `dapr init --slim` mode and during `dapr uninstall`, there is a possibility that the name `placement` for Linux/MacOS might conflict with an existing binary named placement. 
To alleviate this concern, we can prefix the service with `dapr-` to make sure there will be no naming conflicts.

**Comment by gdhuper** [comment]
@mukundansundar I'll take this on. Thanks

**Comment by amanbha** [comment]
@mukundansundar This will be a change in dapr/dapr also and then update the helmcharts to use new binary name. I think this change is not needed. cc @yaron2 @orizohar @msfussell

**Comment by mukundansundar** [comment]
@gdhuper Thanks for the interest. I will get back to you on this issue once we have considered it across, runtime and helm charts. In the meantime would you be interested to look at https://github.com/dapr/cli/issues/401?

**Comment by gdhuper** [comment]
> @gdhuper Thanks for the interest. I will get back to you on this issue once we have considered it across, runtime and helm charts. In the meantime would you be interested to look at #401?

Sure thing.

**Comment by mukundansundar** [comment]
Handled in another issue. For now closing this.
