### ISSUE TITLE
Change init and uninstall behavior for self hosted mode

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#411]
Right now in Windows we create the folder `%USERPROFILE%\.dapr` and in Linux/MacOS we create `$HOME/.dapr`. Refer to these paths as `<HOME>/.dapr` in this issue. 

The proposal here is to move daprd (and placement on slim init) to the `<HOME>/.dapr` folder on calling `dapr init` or `dapr init --slim`. **Also the `dapr` cli on any calls must execute the `daprd` from this path.**
- This solves the potential naming conflicts that might arise with `daprd` and `placement` binaries. 
- Additionally since `dapr` cli always calls `daprd` from the `<HOME>/.dapr` folder, there is no need to modify path for binary installation.
- This makes sure that we do not require sudo for init or uninstall (unless docker commands are protected by sudo)

Additionally we will deprecate/remove the `--install-path` flag from the CLI and we will only support initializing inside the `.dapr` folder. 

`dapr init` will install `daprd` binary in the `<HOME>/.dapr` path. 
`dapr init --slim` will install `daprd`, `placement` binaries in the `<HOME>/.dapr` path. 
`dapr uninstall` should still only remove the `daprd` binary (and `placement` if exists) and the placement service if exists. 
`dapr uninstall --all` will remove the `.dapr` folder, all the other containers (placement, redis and zipkin)

Changes needed: 
- [ ] Update the decision record in [here](https://github.com/dapr/dapr/blob/master/docs/decision_records/cli/CLI-002-self-hosted-init-and-uninstall-behaviors.md) for 0.10.0 release.
- [ ] Remove `--install-path` flag support
- [ ] Change init and uninstall code for dapr self-hosted mode
- [ ] Make sure that `dapr` executes `daprd` from the `.dapr` folder on any further calls
- [ ] Change docs to reflect the changes in init (both slim init and default init)

**The CLI installation scripts will have no change. `dapr` cli will still be installed in the location it is installed now.**

**Comment by LMWF** [comment]
Is it unusual having a cli in a machine global location, but the entity the cli controls (daprd) in a user-specific location?

**Comment by amanbha** [comment]
> Is it unusual to have a cli in a machine global location, but the entity the cli controls (daprd) in a user-specific location?

User can download cli binary at any location.

**Comment by amanbha** [comment]
@mukundansundar Could you please update decision record for this.
