### ISSUE TITLE
Dapr Uninstall Fails with Dapr: cannot get the manifest file: https://api.github.com/repos/dapr/dapr/releases - 403 rate limit exceeded

### ISSUE THREAD

**Issue by dkapellusch** [dapr/cli#415]
Hi all, I am opening this bug to report an issue I experienced when trying to update dapr on MacOS.
## Expected Behavior
`dapr uninstall --kubernetes` should uninstall dapr from the current Kubernetes cluster.

## Actual Behavior
dapr cli fails to uninstall with error 

> Dapr: cannot get the manifest file: https://api.github.com/repos/dapr/dapr/releases - 403 rate limit exceeded

## Steps to Reproduce the Problem
Install dapr-cli version 0.9.0
Run `dapr uninstall --kubernetes` and observe the error in the terminal output
> Dapr: cannot get the manifest file: https://api.github.com/repos/dapr/dapr/releases - 403 rate limit exceeded

**Comment by yaron2** [comment]
that's probably due to Github API rate limiting and should go away if you retry.

Can you try again and confirm it's working?

**Comment by dkapellusch** [comment]
I have tried it a handful of times, including just now. I am still getting the same result.

**Comment by yaron2** [comment]
Ok. 

the workaround is to go [here](https://github.com/dapr/dapr/releases) and find the version of Dapr you want to uninstall.
Click `assets` on the release, download `dapr-operator.yaml` locally and run `kubectl delete -f dapr-operator.yaml`.

**Comment by dkapellusch** [comment]
Thank you, that does work. Do you happen to have the manual install steps as well? A simple `kubectl apply -f dapr-operator.yaml` is failing with the error 

> configurations.dapr.io \"daprsystem\" not found

**Comment by dkapellusch** [comment]
I was able to install the new version via helm. Thanks for providing the workaround, unfortunate that the api has been rate limited for this long, I am still getting 403s when I attempt to use it now.

**Comment by yaron2** [comment]
Yeah so that's weird, I've been doing several installs/uninstalls for the past 30 minutes and wasn't hitting it.

We'll look into it though.

> kubectl apply -f dapr-operator.yaml

Yeah that won't work, there's a configuration object that the CLI creates.

**Comment by 1046102779** [comment]
you may change method GetLatestRelease return "v0.3.0" or other tags in **github.com/dapr/cli/pkg/version/version.go:26**

and go build to get cli binary file, excute ./cli init , you will pass and show the bellow output:

![image](https://user-images.githubusercontent.com/20457624/99258158-1d114600-2853-11eb-8a0b-4354ec050248.png)

OR you can get info from the **https://api.github.com/repos/dapr/dashboard/releases?access_token=** url;

The access_token is in the url:  **https://github.com/settings/tokens**

**Comment by Betula-L** [comment]
`dapr init`

**Comment by Betula-L** [comment]
I tried to bypass request `api.github.com` by assigned `--runtime-version`. However, it still do not work because hardcode dashboardLatestVersion.

https://github.com/dapr/cli/blob/378e047addfdfad48d2cdc26c6632eb015e6209b/pkg/standalone/standalone.go#L155

**Comment by sjwl** [comment]
this workaround allowed `dapr init` to use my personal github credentials, which avoided the rate limitation.

1. create `~/.netrc` file
2. populate with the following
```
machine github.com
login <your username>
password <your password>
```
3. `chmod 600 ~/.netrc`
