### ISSUE TITLE
CLI install fails for arm64 platforms; dapr_linux_arm64.tar.gz is missing

### ISSUE THREAD

**Issue by raykpontimax** [dapr/cli#426]
## Expected Behavior

Install script works; i.e. it downloads the platform-specific compressed installation file and does the installation per the documentation.

## Actual Behavior

Install script correctly id's platform as linux_arm64 but apparently fails to retrieve the required installation file: dapr_linux_arm64.tar.gz

Using the script-generated download reference, a separate wget https://github.com/dapr/cli/releases/download/v0.9.0/dapr_linux_arm64.tar.gz
returns a 404 Not Found.

## Steps to Reproduce the Problem

Run the Linux install script on an ARM64 platform or simply look in that github location to see if the dapr_linux_arm64.tar.gz is in fact missing.

**Comment by youngbupark** [comment]
We will release arm64 binaries from 0.11.0 release. https://github.com/dapr/dapr/releases/tag/v0.11.0-rc.4

closing with https://github.com/dapr/dapr/issues/2107
