### ISSUE TITLE
CLI build Makefile selects incorrect (default) architecture of AMD64

### ISSUE THREAD

**Issue by raykpontimax** [dapr/cli#429]
## Expected Behavior

Makefile logic should set the TARGET_ARCH_LOCAL to "arm64" for platforms on which "uname -m"
returns either "aarch64" or "arm64"; see https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64

## Actual Behavior

The LOCAL_ARCH variable is first set by the output of the "uname -m" (Makefile, line 30).
A set of "ifeq" statements then set the TARGET_ARCH_LOCAL to a specific architecture value, based on the first five characters of the string value returned by the uname invocation.  If the uname provided architecture value isn't matched to the existing set of "ifeq" cases, the TARGET_ARCH_LOCAL variable is set to "AMD64". 

On the Dapr installation target platform (a Nvidia Xavier NX), uname -m returns "aarch64" for which there isn't a "ifeq" case for a LOCAL_ARCH of "aarch64" so the TARGET_ARCH_LOCAL is set to an (incorrect) default of "amd64".

# Steps to Reproduce the Problem
To reproduce the problem, run the CLI "make build" on a platform for which the "uname -m"
returns "aarch64".

**Comment by youngbupark** [comment]
Thanks for the report. We have not released arm64 binaries so that we set amd64 as a fallback. We will fix it soon,.
