### ISSUE TITLE
dapr cli is broken

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/cli#438]
In Ubuntu 18.04

## Expected Behavior

dapr cli should be able to initialize runtime

## Actual Behavior

dapr init is giving segmentation fault and no other  commands like init and options like --version, --help is not working

## Steps to Reproduce the Problem

Download the latest rc version dapr cli from [here](https://github.com/dapr/cli/releases/tag/v0.10.0-rc.0)

Run `dapr init`

```bash
$ dapr init
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

**Comment by amanbha** [comment]
Closing this one as downloaded binary from 0.10.0-rc release is working fine on ubuntu.
