### ISSUE TITLE
"dapr init -k -n my-namespace" This command doesn't work !! Or Does it? If yes then how?

### ISSUE THREAD

**Issue by divyeshBhartiya** [dapr/cli#450]
This Command doesn't work.

C:\Windows\system32>dapr init -k -n default
Error: unknown shorthand flag: 'n' in -n
Usage:
  dapr init [flags]

Flags:
  -h, --help                     help for init
      --install-path string      The optional location to install Daprd binary to.  The default is /usr/local/bin for Linux/Mac and C:\dapr for Windows
  -k, --kubernetes               Deploy Dapr to a Kubernetes cluster
      --network string           The Docker network on which to deploy the Dapr runtime
      --redis-host string        The host on which the Redis service resides (default "localhost")
      --runtime-version string   The version of the Dapr runtime to install. for example: v0.1.0 (default "latest")
  -s, --slim                     Initialize dapr in self-hosted mode without placement, redis and zipkin containers.

unknown shorthand flag: 'n' in -n

**Comment by yaron2** [comment]
Have you made sure you're using version 0.10.0 of the CLI?

**Comment by divyeshBhartiya** [comment]
No...let me check on that. Thanks for your help.
