### ISSUE TITLE
Improve documentation for dapr init --slim

### ISSUE THREAD

**Issue by amanbha** [dapr/cli#452]
Improve documentation for dapr init --slim, the documentation should include how to configure components and run placement service. Without this documentation its difficult for users to setup correct dev env and they run into issues like [this](https://github.com/dapr/dotnet-sdk/issues/380)

**Comment by mukundansundar** [comment]
@amanbha There is part about enabling actors in the Howto for self-hosted Dapr without docker containers. https://github.com/dapr/docs/tree/master/howto/self-hosted-no-docker#enabling-actors

If needed we might need to improve the docs more. I would probably move this to the docs repo with a Note to add a link in CLI's Readme.

**Comment by amanbha** [comment]
Thats great @mukundansundar yes making it more discoverable from cli would be good here.

**Comment by mukundansundar** [comment]
Closing this issue for now as there is documentation available here -> https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/
