### ISSUE TITLE
When running docker rootless, result is a bad error message

### ISSUE THREAD

**Issue by aronchick** [dapr/cli#457]
I'm using docker rootlessly (https://docs.docker.com/engine/security/rootless/), which means that many of the standard expectations aren't there. Specifically, when suggesting I need to do something with 'sudo' this will not work by default, because DOCKER_HOST is unpopulated (and the user's environment variables don't carry through).

When running rootlessly, you need to set the following in your .bashrc:
`export DOCKER_HOST=unix:///run/user/1000/docker.sock`

You can see that docker is running fine either when you run `docker` or `sudo docker`, but only when you:
```
sudo su
dapr init
```
does it actually work.

## Expected Behavior
Ideally, it would 'just work' since docker is there and running fine, but, if not, it'd be great to check for DOCKER_HOST in the bash script (or notify the user).

## Actual Behavior
```
❯ sudo dapr init
⌛  Making the jump to hyperspace...
❌  could not connect to Docker. Docker may not be installed or running
```

## Steps to Reproduce the Problem
1. Install docker rootlessly
2. Download dapr
3. Try to do dapr init.

**Comment by mhoad** [comment]
Seems like this is likely related to how dapr is currently checking for Docker also covered in Issue https://github.com/dapr/cli/issues/257
