### ISSUE TITLE
Unable to publish event from cli

### ISSUE THREAD

**Issue by NitishGawde** [dapr/cli#458]
**I am using flowing Dotnet Sample**

[https://github.com/dapr/dotnet-sdk/tree/master/samples/AspNetCore/ControllerSample
](https://github.com/dapr/dotnet-sdk/tree/master/samples/AspNetCore/ControllerSample)

**I change the Dapr pubsub component to Kafka please check the screenshot.**

![image](https://user-images.githubusercontent.com/65772350/91854913-1165a880-ec82-11ea-8731-23294759067b.png)

----------------------------------------------------------------------------------------------------------------------------------------

**I am able to publish the event.**

![image](https://user-images.githubusercontent.com/65772350/91854134-e7f84d00-ec80-11ea-9b79-8bac58302bff.png)

----------------------------------------------------------------------------------------------------------------------------------------

**Kafka receives the message but using the above sample I am unable to subscribe to the event.** 

![image](https://user-images.githubusercontent.com/65772350/91854826-eda26280-ec81-11ea-8b21-4ae7846cc6cb.png)

----------------------------------------------------------------------------------------------------------------------------------------

**is this behavior bug or I have to do some different configuration??**

Edit: The buggy behavior is that when the dapr dashboard is running and user tried to publish a message using cli command (dapr publish ...) the following error message is observed and dapr cli fails to publish the message:

```bash
Error publishing topic A: Post "http://localhost:0/v1.0/publish/pubsub/A": dial tcp 127.0.0.1:0: connect: connection refused
```

Probable cause is that dapr publish is using the same port as the one used by dashboard.

**Comment by amanbha** [comment]
@NitishGawde Were there other leftover daprd processes running on your machine.. If yes, could you try killing them, then run the app using `dapr run` and publish using `dapr publish`

**Comment by NitishGawde** [comment]
I stop dapr and uninstall and started again but the error was kept coming.
In the end, I restart my system and now it works completely fine.

**Comment by NitishGawde** [comment]
@pruthvidhodda Whenever dapr Dashboard is running I am unable to publish event.

**Comment by pruthvidhodda** [comment]
> @pruthvidhodda Whenever dapr Dashboard is running I am unable to publish event.

I just verified - unable to publish when dashboard is running. We will work on this @NitishGawde
