### ISSUE TITLE
Update Dapr CLI logging to better show errors and warnings

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/cli#484]
Currently the Dapr CLI logging output is much more difficult to read and quickly pinpoint errors/issues compared to the logging output from daprd. I would like to propose that we retool logging output to be similar to daprd instead. I've attached screenshots for comparison. Notice how much more difficult it is to even find the log level in the dapr cli logs.

Dapr CLI log example:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2810722/95518020-cf6a0980-0987-11eb-9229-8f89278abda9.png)

Daprd log example:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2810722/95518028-d3962700-0987-11eb-9929-acb0e3ef8251.png)

/cc
@youngbupark

**Comment by kendallroden** [comment]
Totally agree on this- good idea, Lynn!

**Comment by yaron2** [comment]
To be clear: the CLI is outputting logs from both `daprd` and the app. you are talking about changing the `daprd` outputs of the CLI to match with `daprd`, correct?

**Comment by lynn-orrell** [comment]
> To be clear: the CLI is outputting logs from both `daprd` and the app. you are talking about changing the `daprd` outputs of the CLI to match with `daprd`, correct?

Correct. Any changes needed to the app log formatting to make it more readable is good too. Personally, I definitely prefer seeing the log level first. Allows me to quickly scan and see if anything is wrong. The color coding of the `daprd` logs based on log level is very nice as well.
