### ISSUE TITLE
Add Unit Tests for Standalone package

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#485]
## Describe the proposal
Add Unit Tests for Standalone package

Files for which Unit Tests are needed.

1. publish
2. invoke
3. list
4. mtls_config
5. standalone
6. uninstall 
7. stop 
8. common

Story in epic #423 

RELEASE NOTE: NOT APPLICABLE

**Comment by msfussell** [comment]
@mukundansundar - Are you currently working on this?

**Comment by mukundansundar** [comment]
@msfussell I am not currently working on this.
