### ISSUE TITLE
 CLI configuration command needs to show details and remove the specific heading details only from control plane

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#487]
The dapr configuration command only shows a few pieces of relevant info from the control plane. This should only show a list of configurations and no particular settings in columns, since what you want to see from apps is different from the control plane.

If you want to see more details then you should also be able to get the specific configure in yaml format with this command 

dapr get configuration --name nodeappconfig -o yaml 
dapr get configuration -n nodeappconfig -o yaml 

Relates to #526

**Comment by msfussell** [comment]
This is what is shown today 

![image](https://user-images.githubusercontent.com/11199644/99628026-326ca880-29ea-11eb-9ed2-318136976157.png)

**Comment by mukundansundar** [comment]
hide daprsystem, remove mtls, add metrics column.
