### ISSUE TITLE
dapr init error

### ISSUE THREAD

**Issue by dybxin** [dapr/cli#490]
## Ask your question here

error downloading dashboard binary: read tcp 192.168.xxx.xxx:59370->52.216.104.115:443: read: connection reset by peer

**Comment by hackmong** [comment]
how do you solve this problem? I met the same one.

**Comment by dybxin** [comment]
> how do you solve this problem? I met the same one.

this is network connection timeout, suggestion use vpn.

**Comment by hackmong** [comment]
> > how do you solve this problem? I met the same one.
> 
> this is network connection timeout, suggestion use vpn.

OK, thank you.
