### ISSUE TITLE
Do not start App until Daprd is listening on Dapr port

### ISSUE THREAD

**Issue by jigargandhi** [dapr/cli#497]
## Describe the proposal

Right now Daprd started first and App is started parallelly. There is a wait on channel at  https://github.com/dapr/cli/blob/master/cmd/run.go#L178 which does not wait for the Daprd to bind to dapr port. 

As a consequence, daprd might still be waiting for components to be loaded and app might be eager to fetch secrets from daprd. 
Here the call to Daprd might fail because the daprd is not ready (by ready means listening for connections and bound to the port). 

refer to https://github.com/dapr/dapr/pull/2215 for discussion on the PR.

CC: @yaron2 @youngbupark @artursouza

**Comment by yaron2** [comment]
Is this still relavent?

**Comment by jigargandhi** [comment]
Nopes, this might not be relevant now. Hence closing.
