### ISSUE TITLE
Invoke install.ps1 can't specify "Program File" path

### ISSUE THREAD

**Issue by tianvan** [dapr/cli#513]
## Expected Behavior

install successfully

## Actual Behavior

![image](https://user-images.githubusercontent.com/10600430/99072279-ad9b1c80-25ee-11eb-9bbe-390fbd554df5.png)

## Steps to Reproduce the Problem

see below picture

## Release Note

RELEASE NOTE: **Fix** empty spaces in path

**Comment by mukundansundar** [comment]
#514 closes this
