### ISSUE TITLE
run locally, how to stdout json format logs.

### ISSUE THREAD

**Issue by dybxin** [dapr/cli#515]
## In what area(s)?

> /area runtime
> /area docs

## Ask your question here
i noticed that dapr produces structured logs to stdout either as a plain text or JSON formatted. and to enable JSON formatted logs, in k8s need the flowing configuration:
```
helm install dapr dapr/dapr --namespace dapr-system --set global.logAsJson=true
```
and add the flowing to deployment

```
dapr.io/log-as-json: "true"
```
but, how to in locally env.

**Comment by yaron2** [comment]
Fine by me.

**Comment by youngbupark** [comment]
@dybxin We will bring this to 1.0.0-rc.2

**Comment by dybxin** [comment]
@youngbupark @yaron2 thanks a lot !
