### ISSUE TITLE
Support version argument in one line scripts to pull the specific version of dapr cli

### ISSUE THREAD

**Issue by youngbupark** [dapr/cli#516]
## Describe the proposal

This is the issue to support version argument in one line scripts to pull the specific version of dapr cli.

Script location : https://github.com/dapr/cli/tree/master/install

Examples for one liner script to pull 1.0.0-rc.1 cli

```sh
powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex -version 1.0.0-rc.1"

curl -fsSL https://raw.githubusercontent.com/dapr/cli/master/install/install.sh | /bin/bash 1.0.0-rc.1

wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash 1.0.0-rc.1
```

## Release Note

RELEASE NOTE: **ADD** version argument in one line scripts to pull the specific version of dapr cli

**Comment by orizohar** [comment]
Just to confirm - when a user gets the rc.1 version of the CLI when they run "dapr init" it will bring the rc.1 binaries and "dapr init -k" will use the rc.1 helm chart, correct?

**Comment by youngbupark** [comment]
> Just to confirm - when a user gets the rc.1 version of the CLI when they run "dapr init" it will bring the rc.1 binaries and "dapr init -k" will use the rc.1 helm chart, correct?

no `dapr inti -k` will get 0.11.3 unless it specifies `--runtime-version`.
