### ISSUE TITLE
Change dapr init behavior to download the latest daprd binary when cli version has -rc suffix

### ISSUE THREAD

**Issue by youngbupark** [dapr/cli#518]
## Describe the proposal

Current behavior of `dapr init`: Download the latest stable version of daprd (no suffix version)

Proposed behavior of `dapr init`: If cli version has `-rc` suffix, download the latest version regardless of rc. 

## Release Note

RELEASE NOTE: **Change** dapr init behavior to download the latest daprd binary when cli version has -rc suffix

**Comment by wcs1only** [comment]
We don't think we need to do this anymore.
