### ISSUE TITLE
dapr init's `--redis-host` parameter is confusing

### ISSUE THREAD

**Issue by trondhindenes** [dapr/cli#519]
## Ask your question here
There's no good explanation what the "redis-host" parameter is used for, or why it's required (or is it optional? docs don't mention it). For a framework that provides abstraction for a large number of different underlying technologies, it seems very strange that redis gets its own parameter, without properly explaining the rationale for it.

I would ask that:
- dapr cli's command line switches get documented so that its clear if they're required or not
- the "redis-host" parameter gets properly documented so that users can figure out when to use ot and not

**Comment by msfussell** [comment]
This "redis-host" parameter has now been removed in the latest release, since as you pointed out this was strange to have just for redis and not for other components. Hopefully this removal aligns with your expectations in this issue also.

**Comment by trondhindenes** [comment]
nice! Thanks!
