### ISSUE TITLE
Link to docs printed after init is broken

### ISSUE THREAD

**Issue by SebastianSchildt** [dapr/cli#525]
## Expected Behavior

Not a bug in the code per-se but it amnifests int he cli:

dapr init gives broken link to documentation

```
/dapr init
⌛  Making the jump to hyperspace...
↖  Downloading binaries and setting up components... 
Dapr runtime installed to /home/sebastian/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/sebastian/.dapr/bin
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /home/sebastian/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
```

https://aka.ms/dapr-getting-started should bring me to documentation

## Actual Behavior

https://aka.ms/dapr-getting-started  currently redirects to https://github.com/dapr/docs/tree/master/getting-started and that is 404

Either change the shortcut https://docs.dapr.io/ or print this directly after `dapr init`  (it is shorter than the "shortcut")

## Steps to Reproduce the Problem

```
./dapr init
```

## Release Note

RELEASE NOTE: Fixed link to documentation in dapr --init

**Comment by mukundansundar** [comment]
@AaronCrawfis Can the short link be modified to point to the right guide?

**Comment by AaronCrawfis** [comment]
Fixed. Thanks for the heads up!
