### ISSUE TITLE
Audit CLI changes that might be needed for consistency

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#526]
## Describe the proposal
Audit CLI changes that might be needed for consistency

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
# Proposal
1. Breaking changes
   - Fix Consistency 
   ```
    dapr logs -a, --app-id string      The application id for which logs are needed
    dapr invoke -a, --app-id string    The application id to invoke
    dapr run -i, --app-id string                   The id for your application, used for service discovery
   ```
   - Fix consistency 
   ```
   dapr publish -d, --data string     The JSON serialized string (optional)
   dapr invoke -p, --payload string   The JSON payload (optional)
   ```
2. Print consistent help message for -h flag
```
-h, --help         Print this help message  (have consistent help message)
-h, --help      help for dapr
-h, --help               Prints this help message
```
3. Add shorthands

| Proposed shorthand | Flag                                                                                                             |
|--------------------|------------------------------------------------------------------------------------------------------------------|
| dapr \-v                | \-\-version   version for dapr                                                                                   |
| dapr publish \-p                | \-\-pubsub string  The name of the pub/sub component                                                             |
| dapr stop \-a                | \-\-app\-id string   The application id to be stopped                                                            |
| dapr run \-i                | \-\-image string  The image to build the code in \(input is repository/image\)                                   |
| dapr run \-A                | \-\-placement\-host\-address string   The host on which the placement service resides \(default "localhost"\)    |
| dapr run \-m                | \-\-app\-max\-concurrency int  The concurrency level of the application, otherwise is unlimited \(default \-1\)  |

-A: for actors placement service host, (-h and -H are already taken).
4. Specify certain flags only for Kubernetes only
```
 --enable-ha                Enable high availability (HA) mode
  --enable-mtls              Enable mTLS in your cluster (default true)
 -n, --namespace string         The Kubernetes namespace to install Dapr in (default "dapr-system")
--image string                    The image to build the code in (input is repository/image)
```
5. Fix help messages to specify if the commands are only k8s specific. 
```
components     List all Dapr components
configurations List all Dapr configurations
logs           Get Dapr sidecar logs for an application
```
6. Provide proper examples for all commands 
7. Provide option to disable tracing on run, init
9. Output yaml for commands
```
components 
configurations 
``` 
10. Dapr components config from specified path 
11. Validate a given component file
12. Questions:
 - Why publish command alone does not have app-id, but uses list to get app-id? (Potential breaking change if app-id is made mandatory)
 - Add actors, secrets, state commands in CLI ?

**Comment by mukundansundar** [comment]
@yaron2  @msfussell  Please look at the initial audit for CLI.

**Comment by artursouza** [comment]
I don't think there should be short version flag for placement address.

Regarding the questions above:
* Publish should be consistent in the use of app-id flag.
* actor invoke can be handy.
* Validating a component file seems to be a nice to have (P2), IMO.
* It is good to document why Redis gets special treatment.

**Comment by msfussell** [comment]
Looks good. Some feedback
1) For points 4) and 5). Remember we can never say that a Dapr flag is only for Kubernetes only. For example imagine that for Dapr init there was a  -s option that deployed dapr to Service Fabric which was also in HA mode. We need to make sure that flags are NEVER for a single platform like K8s, they have to be for multiple ones.  Saying that -n is clearly for K8s only and that is ok. 
2) dapr run | -i | --image string  The image to build the code in (input is repository/image) - Not clear on what this does exactly. Probably needs a better description, which is also related to point 6.
3) Point 7. Did this ability to disable tracing come from a specific ask?dapr
4) Why is "dapr completion" useful? When is this used?
5) Do not understand point 9. Is this for local development usage?
7)  I presume that we are also going to address https://github.com/dapr/cli/issues/487 since this is painful.

Let's discuss the questions

**Comment by mukundansundar** [comment]
> Looks good. Some feedback
> 
> 1. For points 4) and 5). Remember we can never say that a Dapr flag is only for Kubernetes only. For example imagine that for Dapr init there was a  -s option that deployed dapr to Service Fabric which was also in HA mode. We need to make sure that flags are NEVER for a single platform like K8s, they have to be for multiple ones.  Saying that -n is clearly for K8s only and that is ok.

A bit contradictory answer but if `-n` is ok to be kubernetes specific, then we already have flags that are kubernetes specific. If you meant sub commands should not be kubernetes specific, for now components, configurations are kubernetes specific as they require the `-k` flag every time and work only with kubernetes. Point 9 solves part of the problem making `components` subcommand usable in standalone also. Again a nice a to P2.  

> 2. dapr run | -i | --image string  The image to build the code in (input is repository/image) - Not clear on what this does exactly. Probably needs a better description, which is also related to point 6.

the image flag can be used to specify an image to be run in kubernetes platform when calling dapr run. 

> 3. Point 7. Did this ability to disable tracing come from a specific ask?dapr

This will be useful for local development. A P2 in my opinion.

> 4. Why is "dapr completion" useful? When is this used?

Dapr completion is use for getting tab based completion in shell for dapr CLI. 

> 5. Do not understand point 9. Is this for local development usage?

Yes this will be useful for local development. A P2 in my opinion.

> 6. I presume that we are also going to address #487 since this is painful.

Yes 

> 
> Let's discuss the questions

**Comment by mukundansundar** [comment]
Instead of having redis-host alone as a special component based flag, it would be better to remove it.

**Comment by mukundansundar** [comment]
Closing this issue as all breaking changes made are closed.
