### ISSUE TITLE
Remove --redis-host flag for dapr init

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#540]
## Describe the proposal
Remove --redis-host flag for dapr init

Currently the redis-host flag is used to specify which host redis runs on and defaults to localhost. 
That is used for specifying the field in the component configuration. 
The question is why is redis alone having this field whereas dapr is supports other components as well. 
The proposal here is to remove the redis-host flag and always default to localhost. 
If that is not the case, the user can then specify a component file specifying the right host port where redis can be found. 

Relates to #526 

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
I support removing the flag.

**Comment by youngbupark** [comment]
+1

**Comment by msfussell** [comment]
Before we do this, there is a scenario with dev containers with this issue https://github.com/dapr/cli/issues/418 that we need to discuss. Having dev containers work with dapr init is a scenario here.

**Comment by mukundansundar** [comment]
Had a discussion with @philliphoff on this, as long as the component files `pubsub.yaml` and `statestore.yaml` point to the right network namespaced redis host, removal of this argument will not affect dev containers.
