### ISSUE TITLE
error downloading daprd binary: version not found for 1.0.0-rc.3

### ISSUE THREAD

**Issue by sureshmvp** [dapr/cli#569]
## Expected Behavior

C:\dapr>dapr init --runtime-version=1.0.0-rc.3
Making the jump to hyperspace...
Return URL should be 
https://github.com/dapr/dapr/releases/download/v1.0.0-rc.3/dapr_windows_amd64.zip [IT SHOULD BE dapr_NOT daprd_]

## Actual Behavior

Downloading binaries and setting up components...
error downloading dapr**d** binary: version not found from url: https://github.com/dapr/dapr/releases/download/v1.0.0-rc.3/dapr**d**_windows_amd64.zip

## Steps to Reproduce the Problem

Run "dapr init --runtime-version=1.0.0-rc.3" on dapr command.

## Release Note
Install.ps1 needs to fix to fetch the correct path. 

RELEASE NOTE:

![image](https://user-images.githubusercontent.com/35755657/103124602-e5659d00-464d-11eb-8b3b-0cf1c885c746.png)

**Comment by yaron2** [comment]
The latest version of the Dapr runtime is rc.2, not rc.3.

The CLI and the runtime are versioned independently.

**Comment by sureshmvp** [comment]
fair enough, thank you @yaron2
