### ISSUE TITLE
Make install script work with non-privilege's environments like Azure Cloud Shell 

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#580]
There are environments like Azure Cloud shell https://shell.azure.com/ that do not have sudo priviledges. When using the Linux install script https://v1-rc2.docs.dapr.io/getting-started/install-dapr-cli/ these fail. Currently the user has to do the following to make this work. 

- wget -q https://github.com/dapr/cli/releases/download/v1.0.0-rc.3/dapr_linux_amd64.tar.gz
- chmod o+x dapr_linux_amd64.tar.gz
- tar xf dapr_linux_amd64.tar.gz
- ./dapr

The script should be able to handle non-sudo environments

The same applies to Powershell in the Azure Cloud shell. I should be able to install Dapr in Windows Powershell terminal for Azure Cloud shell

**Comment by berndverst** [comment]
@msfussell perhaps on Linux we can detect if sudo isn't present and then include an error message to instead set the `DAPR_INSTALL_DIR` env variable. What do you think? For example the following works in Azure Cloud Shell:

```
wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | DAPR_INSTALL_DIR="$HOME/clouddrive" /bin/bash -s1.2.0
```

**Comment by berndverst** [comment]
In general the powershell script can be installed on Windows without Admin privileges.

Powershell in CloudShell does not work because the script assumes Windows File Paths, but Cloud Shell returns Linux paths.

I don't think it makes sense to support Powershell in CloudShell specifically. You can see this for yourself like this:

```
$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList 1.2.0, "$HOME/clouddrive"
```

**Comment by berndverst** [comment]
@msfussell @AaronCrawfis @orizohar -- I think this is just a Documentation issue. What do you all thing?

**Comment by AaronCrawfis** [comment]
> @msfussell @AaronCrawfis @orizohar -- I think this is just a Documentation issue. What do you all thing?

For Linux we still need to update our script to work when sudo is not present, not just when it's present but the user is not in the sudoers group.

**Comment by berndverst** [comment]
@AaronCrawfis in Cloud Shell the `sudo` command does not exist. When you provide `DAPR_INSTALL_DIR` then `sudo` is not being used. That's why the command above worked in cloudshell where `sudo` does not exist.

We could just document that as:
"If your user is not in the sudoers group or sudo is not available on your system please specify an installation directory via the `DAPR_INSTALL_DIR` environment variable."

Or something like that.

**Comment by AaronCrawfis** [comment]
@berndverst my preference is for it to "just work". Is there a way to update the script to auto-detect when sudo isn't present on the system and proceed as if it does exist but the user isn't in the sudoers group?

**Comment by berndverst** [comment]
@AaronCrawfis only if we install it to a different location. When sudo isn't available maybe we install to $HOME?

**Comment by AaronCrawfis** [comment]
@berndverst ah I see now the current behavior. Looks like today the script only works in non-sudo environments when an override directory is set. Only the sudo path works when no directory is specified.

My preference is to fix this so both scenarios of no sudo and not in the sudoers group are both handled by the script automatically installing it to $HOME. Thoughts?

**Comment by berndverst** [comment]
@AaronCrawfis As long as you are fine with installing to $HOME when `sudo` fails or does not exist, no problem!

But what if someone simply forgot to run `sudo`? Now suddenly we are installing to $HOME when running `sudo` would have installed to a more desirable location.

**Comment by AaronCrawfis** [comment]
@berndverst great point! My initial thought is to prompt the user, but that will break existing pipelines and the new GitHub Dapr Action. Not a blocker, but something we need to think through.

Maybe the new path is:
- when using sudo always install to /usr/bin
- when running without sudo prompt user with install path (with the default being $HOME), and a note to use sudo to install to /usr/bin
- 
@orizohar @msfussell thoughts?

**Comment by msfussell** [comment]
This last suggestion makes sense to me. Is this possible. However I just tried out the command about in a Cloud shell and it failed with 

PS /home/mark> wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | DAPR_INSTALL_DIR="$HOME/clouddrive" /bin/bash

DAPR_INSTALL_DIR=$HOME/clouddrive: The term 'DAPR_INSTALL_DIR=$HOME/clouddrive' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by orizohar** [comment]
> @berndverst great point! My initial thought is to prompt the user, but that will break existing pipelines and the new GitHub Dapr Action. Not a blocker, but something we need to think through.
> 
> Maybe the new path is:
> 
> * when using sudo always install to /usr/bin
> * when running without sudo prompt user with install path (with the default being $HOME), and a note to use sudo to install to /usr/bin
> 
> @orizohar @msfussell thoughts?

Not a fan of this. I don't know other Linux tools that do different things if called with sudo vs. without sudo. I think documenting that if sudo is not available an arg for an alternative installation dir can be provided is good enough.

**Comment by berndverst** [comment]
@orizohar agreed. One more option: when sudo is not available maybe we could print a custom error that mentions the other install param.

**Comment by AaronCrawfis** [comment]
> @orizohar agreed. One more option: when sudo is not available maybe we could print a custom error that mentions the other install param.

This sounds good to me. Something like "installation failed, but here's a link to tell you how to make it work in a non-sudo environment"

**Comment by berndverst** [comment]
@AaronCrawfis @orizohar take a look and let me know whether this works for you.
