### ISSUE TITLE
dapr init in GH codespace for version 1.0.0-rc.2 changes container names 

### ISSUE THREAD

**Issue by vermegi** [dapr/cli#581]
## Expected Behavior

redis container after dapr init should be named dapr_redis

## Actual Behavior

After calling dapr init --runtime-version 1.0.0-rc.2 the redis container in GH codespaces is called codespaces-compose_dapr_redis_1

## Steps to Reproduce the Problem

1. take dev container at https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dapr-dotnetcore-3.1 as a starting point
2. change dapr version in both Dockerfile and devcontainer.json file to 1.0.0-rc.2. Dockerfile line 28 should be 
&& wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash -s 1.0.0-rc.2\
devcontainer line 28 should be
"postCreateCommand": "dapr init --runtime-version 1.0.0-rc.2",
3. Start a new GitHub codespace based on this dev container
4. Once codespace is running, issue a docker ps command in the terminal. This gives the following output: 

vscode ➜ ~/workspace/dapr-workshop-internal2 (main) $ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                   PORTS               NAMES
4a7f2191d2bd        daprio/dapr:1.0.0-rc.2   "./placement"            7 minutes ago       Up 7 minutes                                 dapr_placement_dapr-dev-container
f5f6ec3b45dd        openzipkin/zipkin        "start-zipkin"           7 minutes ago       Up 7 minutes (healthy)   9410-9411/tcp       dapr_zipkin_dapr-dev-container
ee4e00647191        codespaces-compose_app   "/usr/local/share/do…"   7 minutes ago       Up 7 minutes                                 codespaces-compose_app_1
5e3b1f65a692        redis:latest             "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes             6379/tcp            codespaces-compose_dapr_redis_1

Container names are 'off'. 

This same issue is not present in non-RC dapr version.

**Comment by mukundansundar** [comment]
@vermegi there was a change done in https://github.com/dapr/cli/pull/546 to remove redis-host flag and properly start redis as part of the `dapr init` command when the docker network is set. 
Thus the container name is prefixed with the docker network name. 
But there is a network alias set as `dapr_redis`. Would that be sufficient for your usecase?

cc @msfussell @yaron2

**Comment by vermegi** [comment]
So, if I understand correctly, there is no more REDIS_HOST flag/environment variable. But, when setting the DAPR_NETWORK environment variable, if in the init command you do: 
dapr init --runtime-version 1.0.0-rc.2 --network dapr-dev-container
This will name the dapr with a network prefix, and that should be ok and picked up correctly by your apps. 

 In my case, my application is not able to start correctly, since it is unable to pick up/find the redis container. 

I am starting from the dev container mentioned above, but changing version to 1.0.0-rc.2 both in dockerfile and devcontainer.json file. PostCreateCommand in devcontiner is: 

dapr init --runtime-version 1.0.0-rc.2 --network dapr-dev-container

When I start my Dapr service (I am using the GBB workshop files: OrderService netcore) I get the following output: 

> Executing task: dapr run --app-id order-service --components-path /home/vscode/workspace/dapr-workshop-internal2/components/local --app-port 5100 --dapr-grpc-port 5101 --dapr-http-port 5180 <

WARNING: no application command found.
ℹ️  Starting Dapr with id order-service. HTTP Port: 5180. gRPC Port: 5101
== DAPR == time="2021-01-21T08:40:00.025200079Z" level=info msg="starting Dapr Runtime -- version 1.0.0-rc.2 -- commit 196483d" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.02524048Z" level=info msg="log level set to: info" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.025755791Z" level=info msg="metrics server started on :35859/" app_id=order-service instance=37648a211843 scope=dapr.metrics type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.026361404Z" level=info msg="standalone mode configured" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.026382205Z" level=info msg="app id: order-service" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.026516108Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.026899916Z" level=info msg="local service entry announced: order-service -> 172.18.0.2:34115" app_id=order-service instance=37648a211843 scope=dapr.contrib type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.026923517Z" level=info msg="Initialized name resolution to standalone" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.02755153Z" level=info msg="waiting for all outstanding components to be processed" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.105507532Z" level=warning msg="error initializing pub sub pubsub.redis: redis streams: error connecting to redis at localhost:6379: dial tcp 127.0.0.1:6379: connect: connection refused" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

== DAPR == time="2021-01-21T08:40:00.105561033Z" level=fatal msg="process component ordersub error: redis streams: error connecting to redis at localhost:6379: dial tcp 127.0.0.1:6379: connect: connection refused" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

⚠  Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:5180/v1.0/metadata/cliPID giving up after 5 attempts
✅  You're up and running! Dapr logs will appear here.

           
The last 2 error messages keep on popping up. I tried out several things to make the service find the redis container, but not successful.

**Comment by mukundansundar** [comment]
@vermegi  I am assuming the application is also running the same docker network.

From the logs you pasted, one looks interesting: 
>== DAPR == time="2021-01-21T08:40:00.105507532Z" level=warning msg="error initializing pub sub pubsub.redis: redis streams: error connecting to redis at localhost:6379: dial tcp 127.0.0.1:6379: connect: connection refused" app_id=order-service instance=37648a211843 scope=dapr.runtime type=log ver=1.0.0-rc.2

It should not be trying to connect to localhost:6379.

There is one more change needed to be done in the dapr-dev-container, the dapr CLI version also needs to be updated to 1.0.0-rc.3. With that the configuration files are updated to point to the network alias when a docker network is specified on dapr init. Eg: 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: dapr_redis:6379
  - name: redisPassword
    value: ""
```

It no longer points to localhost:6379 but to dapr_redis:6379. Please see the note here: https://github.com/dapr/cli#launch-dapr-and-your-app
>Note: When in a specific Docker network, the Redis, Zipkin and placement service containers are given specific network aliases, dapr_redis, dapr_zipkin and dapr_placement, respectively. The default configuration files reflect the network alias rather than localhost when a docker network is specified.

Can you check with dapr cli version 1.0.0-rc.3? 
In the dapr-dev-container Dockerfile change line https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dapr-dotnetcore-3.1/.devcontainer/Dockerfile#L28
to be 
```
wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash -s 1.0.0-rc.3
```

**Comment by vermegi** [comment]
Yes! Exellent! All good now: 

> Executing task: dapr run --app-id order-service --components-path /home/vscode/workspace/dapr-workshop-internal2/components/local --app-port 5100 --dapr-grpc-port 5101 --dapr-http-port 5180 <

WARNING: no application command found.
ℹ️  Starting Dapr with id order-service. HTTP Port: 5180. gRPC Port: 5101
INFO[0000] starting Dapr Runtime -- version 1.0.0-rc.2 -- commit 196483d  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] log level set to: info                        app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] metrics server started on :34983/             app_id=order-service instance=a0c2ef4f73c5 scope=dapr.metrics type=log ver=1.0.0-rc.2
INFO[0000] standalone mode configured                    app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] app id: order-service                         app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] local service entry announced: order-service -> 172.18.0.6:33227  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.contrib type=log ver=1.0.0-rc.2
INFO[0000] Initialized name resolution to standalone     app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] waiting for all outstanding components to be processed  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] component loaded. name: ordersub, type: pubsub.redis  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] all outstanding components processed          app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] enabled gRPC tracing middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.grpc.api type=log ver=1.0.0-rc.2
INFO[0000] enabled gRPC metrics middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.grpc.api type=log ver=1.0.0-rc.2
INFO[0000] API gRPC server is running on port 5101       app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] enabled metrics http middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.http type=log ver=1.0.0-rc.2
INFO[0000] enabled tracing http middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.http type=log ver=1.0.0-rc.2
INFO[0000] http server is running on port 5180           app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] enabled gRPC tracing middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.grpc.internal type=log ver=1.0.0-rc.2
INFO[0000] enabled gRPC metrics middleware               app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime.grpc.internal type=log ver=1.0.0-rc.2
INFO[0000] internal gRPC server is running on port 33227  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
INFO[0000] application host: 127.0.0.1. application protocol: http. waiting on port 5100.  This will block until the app is listening on that port.  app_id=order-service instance=a0c2ef4f73c5 scope=dapr.runtime type=log ver=1.0.0-rc.2
✅  You're up and running! Dapr logs will appear here.
