### ISSUE TITLE
Dapr for apple silicon

### ISSUE THREAD

**Issue by lokinfey** [dapr/cli#582]
When dapr publish version for apple silicon ?

**Comment by wcs1only** [comment]
We don't currently have the build infrastructure to produce native arm64 binaries for MacOS, but we have confirmed that dapr CLI works under rosetta2 (see the note about M1 macs in our getting started guide):

https://docs.dapr.io/getting-started/install-dapr-cli/#tabs-2-macos

**Comment by wcs1only** [comment]
Supported in v1.5.0
