### ISSUE TITLE
`radis:latest` and `openzipkin/zipkin` are NOT removed by `dapr uninstall --all`

### ISSUE THREAD

**Issue by horihiro** [dapr/cli#608]
## Ask your question here
After executing `dapr uninstall --all`, docker image `daprio/dapr:latest` is removed successfully, but `radis:latest` and `openzipkin/zipkin` are **NOT** removed from my environment.

Is this expected behavior?

![image](https://user-images.githubusercontent.com/4566555/108782734-7950d800-75af-11eb-9190-93858adf2110.png)

**Comment by mukundansundar** [comment]
@horihiro This is expected, unless the container name is specifically `dapr_redis` or `dapr_zipkin`, it will not be removed on dapr uninstall.

**Comment by horihiro** [comment]
Thanks.
Containers which names are `dapr_redis` and `dapr_zipkin` are removed successfully by `dapr uninstall --all`.
But container **images** `redis` and `openzipkin/zipkin` ,which were installed by `dapr init`, are not removed, only `daprio/dapr` is removed.

**Comment by mukundansundar** [comment]
@horihiro Only the running container and container instances are removed. The images will not be removed by `dapr uninstall`. That is the default behavior.

**Comment by horihiro** [comment]
Thank you!
