### ISSUE TITLE
Show more information for components when using -o wide

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/cli#610]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Show more information for components when using -o wide to give operators more information about the resources without going to a specific resource first.

> kubectl get components -o wide

## Release Note

RELEASE NOTE: **ADD** Show more component info when using `-o wide` in Kubernetes

**Comment by tomkerkhove** [comment]
I think `type` would be the most obvious one, optionally version as well.

Metadata for every component would be nice, but too flexible I'm afraid

**Comment by artursouza** [comment]
I am OK to add `type` and `version` for now. Those are good ones to start with. Feel free to send a PR for this. Comment with `/assign` if you plan to work on this.

**Comment by tomkerkhove** [comment]
Bumping

**Comment by mukundansundar** [comment]
@tomkerkhove are you interested in sending a PR for this?

**Comment by tomkerkhove** [comment]
I don't have Go experience but if you have some guidance/docs then I'm happy to give it a try
