### ISSUE TITLE
enhance, flexible dapr api configuration and direct port mapping service.

### ISSUE THREAD

**Issue by Edward-Roshan** [dapr/cli#614]
## Describe the proposal

we use ```dapr invoke --app-id some_app --method some_method --payload "something" --verb```. It's not flexible enough to apply dapr api in production. Is there anyway make it more flexible or easily in any situation. Or you could just provide a service. Let us easily to direct mapping port from back to front with tcp/udp  protocols?

**Comment by yaron2** [comment]
In production it's advised you call the Dapr APIs directly or using an SDK. The CLI methods are mostly for development purposes.

**Comment by Edward-Roshan** [comment]
Great. I mean I want to know If I run some applications like ElasticSearch, Hadoop Cluster or Kafka under the dapr runtime. Can we directly mapping inner port to out side of dapr runtime?

**Comment by Edward-Roshan** [comment]
I am sorry that i bother you. Probably I need take some time to learn k8s more. I find I could use port-forward to forward any inner port from pod to cluster for ClusterIP service. Or create new service with NodePort or LoadBalance to expose port to out side. Thanks. Let me close issue.
