### ISSUE TITLE
how to install dapr runtime offline

### ISSUE THREAD

**Issue by darren-wang** [dapr/cli#626]
Hi, we need to install dapr offline, we can now install dapr CLI offline already according to dapr CLI's install script, however, how could we install dapr runtime offline, just like exec `dapr init -k`?

I think this is a rather import issue cause many real prod envs can not access internet directly, hope get some answer.

**Comment by yaron2** [comment]
If you don't have internet access directly, it means you'll need to host Dapr docker images on your own on-premises registry.

You would essentially need to push images to your own local registry, and can then use the Dapr Helm Chart to modify the values to point to your image.

**Comment by newbe36524** [comment]
@darren-wang  I and my partners are trying to make this done. please join us to handle it if you are interested #640

**Comment by darren-wang** [comment]
> 
> 
> @darren-wang I and my partners are trying to make this done. please join us to handle it if you are interested #640

of course, corporate users need this work.
