### ISSUE TITLE
How to run app in docker instead of process on selfhost?

### ISSUE THREAD

**Issue by yamajik** [dapr/cli#627]
How to run app in docker instead of process on selfhost?

**Comment by yaron2** [comment]
See here: https://github.com/dapr/samples/tree/master/hello-docker-compose

**Comment by yamajik** [comment]
> See here: https://github.com/dapr/samples/tree/master/hello-docker-compose

Any plan for adding feature to run cases (process|docker|kubernets) over Dapr CLI?

**Comment by mukundansundar** [comment]
For now there are no plans.
