### ISSUE TITLE
go get as mod failed

### ISSUE THREAD

**Issue by yamajik** [dapr/cli#635]
><((("> go get github.com/dapr/cli@latest
go get: github.com/dapr/cli@v0.2.0-alpha.2 updating to
        github.com/dapr/cli@v1.0.1 requires
        github.com/dapr/dapr@v1.0.0-rc.1.0.20201217002310-310e670d987b requires
        github.com/dapr/components-contrib@v1.0.0-rc2.0.20201216184327-a03a96c28267 requires
        github.com/dapr/dapr@v0.4.1-0.20200228055659-71892bc0111e requires
        github.com/dapr/components-contrib@v0.0.0-20200219164914-5b75f4d0fbc6 requires
        k8s.io/client@v0.0.0-00010101000000-000000000000: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/majik/go/pkg/mod/cache/vcs/1873572271fcf325ad32062ccf6aee165fdb6b2229b714b40050d6bf3d599824: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/kubernetes/client/' not found
><((("> go version
go version go1.16.2 darwin/amd64

**Comment by mukundansundar** [comment]
@yaron2 Can you take a look at this?
