### ISSUE TITLE
dapr start app error need to stop the running dapr process

### ISSUE THREAD

**Issue by marviniter** [dapr/cli#645]
## Expected Behavior
dapr run app err need to stop the running daprd process

## Actual Behavior
dapr run  to start app with not found command cause "exec: "-": executable file not found in $PATH" error then exit but the daprd proccess is running and dapr cli can not find and stop it, need kill the daprd process by cmd.

## Steps to Reproduce the Problem
dapr run --app-id testpubsub  --dapr-http-port 3500 - --components-path ./components/
```
ℹ️  Dapr sidecar is up and running.
❌  exec: "-": executable file not found in $PATH
```
but the daprd is still running.

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
closed by #646
