### ISSUE TITLE
Install script threw an exception on Windows 10

### ISSUE THREAD

**Issue by harryvu** [dapr/cli#650]
I followed the instruction from Dapr Docs to install Dapr CLI, but it threw an exception below:

PS C:\dapr> powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"
Installing Dapr...
Creating c:\dapr directory
Downloading https://api.github.com/repos/dapr/cli/releases/assets/33351938 ...
Extracting c:\dapr\dapr_windows_amd64.zip...
Exception 0xc0000005 0x0 0x7ff9da390fff 0x24674bc0000
PC=0x24674bc0000

runtime: unknown pc 0x24674bc0000
stack: frame={sp:0xe8ce3fe520, fp:0x0} stack=[0x0,0xe8ce3ffc00)

I am on Windows 10 Pro, Build 19042.867, .net core 3.1. Has anyone experience the same issue and how to fix it? Thank you.

**Comment by mukundansundar** [comment]
Hi @harryvu This seems like an exception was thrown while the Zip file was extracted. Can you try if possible on some other windows version if possible?
