### ISSUE TITLE
Dapr uninstall -k does not remove the CRDs

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#656]
## Expected Behavior

`dapr uninstall -k` remove the CRDs

## Actual Behavior
```
$ dapr uninstall -k
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully
$ kubectl get crds
NAME                     CREATED AT
components.dapr.io       2021-03-31T01:24:00Z
configurations.dapr.io   2021-03-31T01:24:00Z
subscriptions.dapr.io    2021-03-31T01:24:01Z
```

## Steps to Reproduce the Problem

- install dapr using `dapr init -k`. 
- run `kubectl get crds` 
- run `dapr uninstall -k` 
- run `kubectl get crds` 
the crds still exist. 

## Release Note

RELEASE NOTE: **RESOLVED** `dapr uninstall -k` does not remove CRDs

**Comment by yaron2** [comment]
Closing this as removing CRDs also removes any components, configurations and subscription CRs from the cluster.

**Comment by wcs1only** [comment]
Can we at least add a flag or something?

**Comment by mukundansundar** [comment]
Adding an `--all` flag.
