### ISSUE TITLE
`dapr upgrade -k` in some cases does not replace/update CRDs

### ISSUE THREAD

**Issue by pkedy** [dapr/cli#657]
## Expected Behavior

When appropriate (or maybe always) run the equivalent of a `kubectl replace` for each CRD.

Related to #656

## Actual Behavior

The Dapr CLI currently does not do anything to upgrade CRDs during a Kubernetes upgrade.

## Steps to Reproduce the Problem

* install dapr using dapr init -k.
* run kubectl get crds
* run dapr uprade -k
* run kubectl get crds
* the crds are not updated

## Release Note

RELEASE NOTE: **RESOLVED** dapr upgrade -k does not replace/update CRDs

**Comment by mukundansundar** [comment]
@pkedy dapr upgrade does update the CRDs .... https://github.com/dapr/cli/blob/master/pkg/kubernetes/upgrade.go#L138-L147

Should it be that it should replace the CRDs if there are issues and such?

**Comment by pkedy** [comment]
@mukundansundar Based on our convo this morning, I thought that the CRDs were applied only on an init. This changes things. :)

Since `kubectl apply` basically does a replace/patch if it already exists, in theory this is unnecessary. Obviously more investigation is needed.

**Comment by yaron2** [comment]
After testing, I can confirm CRDs are applied and updated on upgrade. Closing this.
