### ISSUE TITLE
Upgrade Go Linter

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#670]
## Describe the proposal
Upgrade Go Linter to 1.39.0. Ideal to be done in sync with other dapr repos if possible. 

Remove `only-new-issues: true` flag from golangci-lint in workflow file.

## Release Note

RELEASE NOTE:

**Comment by tanvigour** [comment]
Hi Long, do you think the changes https://github.com/dapr/dapr/pull/3594 might affect the linter upgrade?

**Comment by daixiang0** [comment]
yep, since now `dapr/cli` use different config from `dapr/dapr`.
