### ISSUE TITLE
Come up with a workaround for github API rate limiting.

### ISSUE THREAD

**Issue by wcs1only** [dapr/cli#677]
## Expected Behavior

The CLI uses the github releases API on a `dapr init`. We expect this API to be available, and we fail when it isn't.  

## Actual Behavior

The github releases API has a rate limit of 60 requests per hour per IP address for unauthenticated requests:

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

## Steps to Reproduce the Problem
```
# Warning, this will lock you out of the unauthenticated github API for up to an hour
% for req in `seq 1 60`; do curl -s https://api.github.com/repos/dapr/dashboard/releases ; done && dapr init
% dapr init
⌛  Making the jump to hyperspace...
❌  Downloading binaries and setting up components...
❌  cannot get the latest release version: https://api.github.com/repos/dapr/dashboard/releases - 403 Forbidden
```

## Release Note

RELEASE NOTE: **FIX** Workaround for github releases API ratelimiting

**Comment by TomorJM** [comment]
Is it necessary?

**Comment by wcs1only** [comment]
> Is it necessary?

Our test automation is hitting this somewhat regularly. It is reasonable to assume that others will as well.

**Comment by mukundansundar** [comment]
> > > Is it necessary?
> > 
> > 
> > Our test automation is hitting this somewhat regularly. It is reasonable to assume that others will as well.
> 
> Can we fix that for our tests by using a github token? It does not close this issue but I think it is a good first step and others can also use the same trick if they run into the same problem.

In that. scenario ... the self-hosted tests in darwin cannot be run as a PR check ... it needs to be run on a master merge and on schedule only ...

**Comment by wcs1only** [comment]
Even with #700 which improves the situation in our CI/CD pipeline we're still getting issues like dapr/dapr#3390.

We've had several proposals on how to fix this:
1. We can put this API behind a CDN
I did the math on this and there might still be issues here. The upstream API has the following cache control header set:
```
cache-control: public, max-age=60, s-maxage=60
```
This means we'd need 100% request deduplication to stay under the 60/hour limit. This is cutting it really close. We'd probably have to have the CDN add a GITHUB_TOKEN header or something similar.
2. We can cache the version locally on a users machine (and have an initial cache populated by our CLI install script). If the call to the release API fails, we could fall back to the local cached version and print a warning.

We could also do both these things, if need be.

**Comment by wcs1only** [comment]
So there was an obvious second place to fall back on. https://dapr.github.io/helm-charts/index.yaml has everything we need, and is already behind a CDN.
