### ISSUE TITLE
Please try to support offline initialization configuration

### ISSUE THREAD

**Issue by zfchai** [dapr/cli#690]
## dapr init  --runtime-version=1.1.0
Making the jump to hyperspace...
Downloading binaries and setting up components...
error downloading daprd binary: Get "https://github.com/dapr/dapr/releases/download/v1.1.0/daprd_windows_amd64.zip": dial tcp 192.30.255.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

## Please try to support offline initialization configuration
1. The extension command declares the url download address，example ：dapr init  --runtime-version=1.1.0 --url=https://xxx.xxx.xxx
2. Download required resource components offline and specify path initialization settings，example：dapr init  --runtime-version=1.1.0 --path=d:\dapr
3. Required resource components Docker containerization

# The purpose of this idea is to solve the problem that the initialization process will fail due to the current local network restrictions.

**Comment by newbe36524** [comment]
@zfchai  I and my partners are trying to make this done. please join us to handle it if you are interested #640

**Comment by mukundansundar** [comment]
Planning to be released as a preview feature in 1.7 release. 
closing this as #640 is closed.
