### ISSUE TITLE
Dapr should not error when init is run again

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/cli#693]
## Describe the proposal

I am trying to build a pipeline for an app that uses Dapr. Each time the pipeline is run Dapr init is called. I have to do this because the AKS cluster is installed with Bicep. So it might already be there or it might not. But when I run the pipeline a second time my logs show an error.

```
←  Deploying the Dapr control plane to your cluster... 
↖  Deploying the Dapr control plane to your cluster... 
↑  Deploying the Dapr control plane to your cluster... 
↗  Deploying the Dapr control plane to your cluster... 
→  Deploying the Dapr control plane to your cluster... 
↘  Deploying the Dapr control plane to your cluster... 
↓  Deploying the Dapr control plane to your cluster... 
❌  Deploying the Dapr control plane to your cluster...
❌  cannot re-use a name that is still in use
```

Dapr, should not complain if it is already initialized in the target cluster. Should just be a no-op. Dapr also pollutes the logs with the `Deploying the Dapr control plane to your cluster...` message. On the first run, it is hundreds of lines. 

## Release Note

Dapr CLI 1.1.0
Runtime 1.0.0

RELEASE NOTE:

**Comment by mukundansundar** [comment]
This can be done but it will be a behaviour change. A couple of things can be done here 
1. Dapr pollutes logs --- add a `--no-spinner` option to not display spinner. 
2. Dapr init error --- by default Helm client does error out if you try to install with same name and that is what is reflected here. A `--silent/-q` option can be introduced which does not exit on error. 
//cc @yaron2 thoughts?
