### ISSUE TITLE
dapr cli hangs after a successful dapr init

### ISSUE THREAD

**Issue by mcain12** [dapr/cli#707]
upgrading to latest release.  I ran a dapr uninstall --all then reinstalled successfully, ran dapr init successfully. after that all dapr commands just hang.

**Comment by yaron2** [comment]
Transferred issue to correct repo.

**Comment by mcain12** [comment]
So I have verified that the Cisco Umbrella agent is not running on my machine...

**Comment by wcs1only** [comment]
I created an issue in our upstream dependency. Will see if I can get some traction with the upstream team.
