### ISSUE TITLE
Error - Docker Pull rate limiting.

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#726]
CLI GitHub Workflow / CI runs encounter Docker Pull rate limits.

## Expected Behavior

No issues on pulling new Docker container

## Actual Behavior

{"time":"2021-05-25T15:15:33.488371Z","status":"failure","msg":"Unable to find image 'daprio/dapr:1.1.1' locally\ndocker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.\nSee 'docker run --help'.\n"}

https://github.com/dapr/cli/runs/2666586343?check_suite_focus=true#step:5:180

## Steps to Reproduce the Problem

Known Docker Pull limit

## Release Note

RELEASE NOTE: Default `dapr init` to use GitHub container registry and have Docker Hub as a fallback

**Comment by daixiang0** [comment]
I think there are some solutions:
1. add docker user token
2. download image into cache, while need to update when image upgrade

@dapr/maintainers-cli WDYT?

**Comment by artursouza** [comment]
@daixiang0 LGTM. We can officially document that `docker login` is the way to workaround Docker rate limiting.

**Comment by mukundansundar** [comment]
Based on the previous comments this is more of a documentation issue now.

**Comment by paulyuk** [comment]
Let's fix this for real.  The images we need are now in GHCR per https://github.com/dapr/dapr/pull/4365

I'll PR the fix.

**Comment by paulyuk** [comment]
I spoke to @mukundansundar and @pravinpushkar and recognize now there is a lot more too it and they are already working on it.  The work likely spans to dapr v1.8.  I will contribute to them versus PR myself.

**Comment by paulyuk** [comment]
I do suggest P1 because the rate limiting problem is becoming a real problem for our tests and github actions.
