### ISSUE TITLE
`dapr list` ignores `--log-as-json`

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#727]
## Expected Behavior

When running `dapr list --log-as-json`, I expect the output to be in JSON format.

## Actual Behavior

The output is in the default table format.

## Steps to Reproduce the Problem

```bash
% dapr --version
CLI version: 1.2.0-rc.2 
Runtime version: 1.2.0-rc.3

% dapr list --help
List all Dapr instances. Supported platforms: Kubernetes and self-hosted

Usage:
  dapr list [flags]

Examples:

# List Dapr instances in self-hosted mode
dapr list

# List Dapr instances in Kubernetes mode
dapr list -k


Flags:
  -h, --help         Print this help message
  -k, --kubernetes   List all Dapr pods in a Kubernetes cluster

Global Flags:
      --log-as-json   Log output in JSON format

% dapr list --log-as-json
  APP ID              HTTP PORT  GRPC PORT  APP PORT  COMMAND  AGE  CREATED              PID    
  Ninjabronze-Reaper  54536      54537      0                  4m   2021-05-25 10:36.29  28261
```

**Comment by mukundansundar** [comment]
@philliphoff I believe the idea was that `--log-as-json` was for logs from daprd and the application not a change in the output format.

cc @pkedy

**Comment by philliphoff** [comment]
Sure, though in that case I'd argue that it's still a bug to show the option under the `list` command.  :-)

That said, an "output as JSON" option for `list` would be helpful in allowing other tools to wrap it.  For example, the VS Code extension currently has logic to extract running Dapr applications from the local process list.  That's exactly what `dapr list` does!  It'd be nice to eliminate that implementation in order reuse the Dapr CLI's implementation, but its current format makes parsing, while possible, more complicated than necessary.

**Comment by mukundansundar** [comment]
opened a new issue listing this requirement https://github.com/dapr/cli/issues/728

**Comment by mukundansundar** [comment]
bug still present
