### ISSUE TITLE
Format output of `dapr --version` as JSON.

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#737]
## Describe the proposal

`dapr --version` currently returns:

```
$  dapr --version
CLI version: 1.2.0-rc.2 
Runtime version: 1.2.0
```

For easier and more robust consumption by tools, it would be better if formatted as JSON (or possibly YAML):

```
$ dapr --version --output json
{
  "cli": "1.2.0-rc.2",
  "runtime": "1.2.0"
}
```

**Comment by anhldbk** [comment]
@philliphoff Currently we have a global flag:

```text
Global Flags:
      --log-as-json   Log output in JSON format
```

Some sub commands do not fully support that flag.

@yaron2 Do you think we need to implement such feature?

**Comment by yaron2** [comment]
It'd be good if we have a global `--output` flag to be applicable to all subcommands that support it. `log-as-json` controls the log format that comes from `daprd`, not the output of the CLI, and so these are very different commands.

**Comment by fanfanbj** [comment]
Now, --version as flag in dapr command. 
I think we can change it to sub command. 
For example:
dapr version --output json.

@yaron2 Do you think we need to implement like that?

**Comment by beiwei30** [comment]
@fanfanbj you should follow [anhldbk](https://github.com/dapr/cli/issues/737#issuecomment-887586384)'s idea to implement.

**Comment by beiwei30** [comment]
> Format output of dapr --version as JSON. #878

my fault, I've noticed that you've already followed yaron2's suggestion.
