### ISSUE TITLE
Add ability for Dapr CLI to add/get secrets from secret store component

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/cli#742]
## Describe the proposal

Dapr CLI should have a command like `dapr secrets` to add/put secrets from a secret store component. Something like:

`dapr secrets add  --data '{"connectionString":"343ab342c34a2"}'`
`dapr secrets add  --data-file ./mysecrets.json`
`dapr secrets get  --key "connectionString"`

With https://github.com/dapr/dapr/issues/3301 the set secret command should work with any secret component.

Without a POST API, the CLI set command add and get commands should interact with the local JSON file created by https://github.com/dapr/cli/issues/741

## Release Note

RELEASE NOTE: **ADD** new `secrets` command to get/set secrets from a local JSON secret store

**Comment by AaronCrawfis** [comment]
Pairs with #741 to improve secrets management for Dapr

**Comment by wcs1only** [comment]
I like this idea, but I think it should probably be write only. We add the CLI to simplify adding secrets, that can then only be read by the Dapr secrets API.

**Comment by AaronCrawfis** [comment]
Depends on https://github.com/dapr/dapr/issues/3301

**Comment by AaronCrawfis** [comment]
> I like this idea, but I think it should probably be write only. We add the CLI to simplify adding secrets, that can then only be read by the Dapr secrets API.

I actually think adding the ability to get secrets from the CLI would be a useful inner loop feature. Component scoping can allow CLI access to be disabled in production scenarios

**Comment by philliphoff** [comment]
Also a `dapr secrets list` which returns the known keys (which can then be retrieved using `dapr secrets get`.  It's often useful for developers (and their tools) to be able see values *as their application sees them* rather than have to dig through the the various backing stores to uncover them.

**Comment by AaronCrawfis** [comment]
Mockup for local file
![image](https://user-images.githubusercontent.com/54363786/123138137-908ebd80-d409-11eb-8237-7d606642d06c.png)

**Comment by AaronCrawfis** [comment]
Mockup for any secret store
![image](https://user-images.githubusercontent.com/54363786/123138236-a603e780-d409-11eb-963b-32edbd1fed02.png)

**Comment by AaronCrawfis** [comment]
Based on feedback from this morning it sounds like `dapr user-secrets` is the preferred command to indicate this is for local development only.
