### ISSUE TITLE
`dapr dashboard` reports confusing error when already running.

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#743]
## Expected Behavior

Running `dapr dashboard` when a dashboard is already running should either start another dashboard on a random port or simply output where the existing dashboard is running.  (Personally I'd vote for the former; what difference does it really make if more than one instance of the dashboard is running?)

## Actual Behavior

Running `dapr dashboard` when a dashboard is already running both reports that a dashboard is running on a port as well as an error about the dashboard not being found (and asks if Dapr is installed).

## Steps to Reproduce the Problem

In terminal window A:

```bash
$ dapr dashboard
Dapr Dashboard running on http://localhost:8080
```

In terminal window B:

```bash
$ dapr dashboard            
Dapr Dashboard running on http://localhost:8080
❌  Dapr dashboard not found. Is Dapr installed?
```

Note that this behavior only exists when one dashboard is using the default port (i.e. `8080`).

**Comment by mukundansundar** [comment]
@philliphoff This needs a fix here https://github.com/dapr/cli/blob/19131133e97aaef13fdcaeb75689ddf3f5359423/cmd/dashboard.go#L159-L162

It does not distinguish between errors in these lines.

**Comment by ShaileshSurya** [comment]
@mukundansundar is this open for contribution?

**Comment by wcs1only** [comment]
> @mukundansundar is this open for contribution?

Absolutely, If you'd like to submit a PR let us know and we'll assign this to you.

**Comment by ShaileshSurya** [comment]
@wcs1only Please assign this to me.

**Comment by mukundansundar** [comment]
@ShaileshSurya have assigned it to you

**Comment by mukundansundar** [comment]
@ShaileshSurya is there any progress on this?
