### ISSUE TITLE
dapr init failed.

### ISSUE THREAD

**Issue by hackmong** [dapr/cli#747]
when I run dapr init, It shows that:

 cannot get the latest release version: Get "https://api.github.com/repos/dapr/dapr/releases": read tcp 192.168.136.21:43104->192.30.255.116:443: read: connection reset by peer

how can I solve this?

**Comment by daixiang0** [comment]
use proxy server.

**Comment by wcs1only** [comment]
I have created a PR to fall back to an alternative source for the latest release version. It may help with this issue.

In the mean time, you can use the following to manually specify the latest version to unblock yourself:
```
dapr init --dashboard-version=0.6.0 --runtime-version=1.2.2
```

**Comment by berndverst** [comment]
Related to  https://github.com/dapr/cli/issues/740

FYI: Seems to only affect Chinese users so far (at least 3 or 4 known affected users)

**Comment by daixiang0** [comment]
It is a network issue I think, it would be totally fixed after we support offline deployment, which is a good feature from my side.

**Comment by marjorienorm** [comment]
I'm a US-based user and dad the same error when I was connected directly to my corporate network.  I had to connect via and external wi-fi with VPN to get it to work.
