### ISSUE TITLE
dapr init 404 Not Found

### ISSUE THREAD

**Issue by lgbin879** [dapr/cli#755]
$ bin > dapr init
⌛  Making the jump to hyperspace...
❌  Downloading binaries and setting up components...
❌  cannot get the latest release version: https://api.github.com/repos/dapr/dashboard/releases - 404 Not Found

$ bin > dapr --version
CLI version: 1.2.0
Runtime version: n/a

$ bin > uname -a
Linux computende4 5.10.27-051027-generic #202103310028 SMP Thu Apr 1 02:16:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wcs1only** [comment]
Also, you should be able to workaround this by manually specifying the version:
```
dapr init --dashboard-version=0.6.0 --runtime-version=1.2.2 
```

**Comment by lgbin879** [comment]
> Also, you should be able to workaround this by manually specifying the version:
> 
> ```
> dapr init --dashboard-version=0.6.0 --runtime-version=1.2.2 
> ```

thanks, it works.
it might be the firewall issue, could you apply this url to be modification ?
https://api.github.com/repos/dapr/dashboard/releases

**Comment by wcs1only** [comment]
I've created a PR to fall back on a secondary source of truth for the release version. It may help this case.
