### ISSUE TITLE
dapr init failed

### ISSUE THREAD

**Issue by zhangqing132155** [dapr/cli#774]
## Ask your question here
I'v got a problem when i running 'dapr init'.It seems to be a problem about TLS or HTTPS,how can i solve it?Or  there is another way in self-hosted mode?
Even the container is running successfully,but i doubt that there must be some unknown problems,because  the process has exceptions.

## Local Environment
Win10 19042.1110
Docker 20.10.7

## Running information
![image](https://user-images.githubusercontent.com/22491348/128150605-d0ecd636-7078-4b89-abbc-87efc039b4ad.png)
![image](https://user-images.githubusercontent.com/22491348/128150438-54ce2e9b-f165-41bc-8014-95c387b19bb2.png)
![image](https://user-images.githubusercontent.com/22491348/128150527-12a24cd8-cce8-4872-87c5-779e9663b013.png)

**Comment by zhangqing132155** [comment]
I can visit the 'https://api.github.com/repos/dapr/dapr/releases/dashboard_windows_amd64.zip' via web browser!

**Comment by tanvigour** [comment]
Try using vpn : https://github.com/dapr/cli/issues/490

**Comment by zhangqing132155** [comment]
> Try using vpn : #490

Thks,but this reference doesn't show how can i use vpn,any instructions?

**Comment by zhangqing132155** [comment]
> Try using vpn : #490

Thks,but this reference doesn't show how can i use vpn,any instructions?

**Comment by zhangqing132155** [comment]
> > Try using vpn : #490
> 
> Thks,but this reference doesn't show how can i use vpn,any instructions?

I used alesocks,it works!Thx!
