### ISSUE TITLE
Error when install dapr on a specific namespace then uninstall and install into another namespace

### ISSUE THREAD

**Issue by thanhlq** [dapr/cli#783]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.3.0

## Expected Behavior

Reinstallation of dapr should work

## Actual Behavior

  Deploying the Dapr control plane to your cluster...
❌  rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "dapr-operator-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "cc-service": current value is "cc-infra"
./k8s-1-deploy-infra.sh: line 44: SERVICE: command not found
❌  No status returned. Is Dapr initialized in your cluster?

## Steps to Reproduce the Problem

(GKE cluster, kubernetes 1.20)

dapr init --wait -k -n cc-infra
dapr uninstall -k
dapr init --wait -k -n cc-service

**Comment by yaron2** [comment]
Moving to CLI repo

**Comment by CodeMonkeyLeet** [comment]
@thanhlq Can you confirm that dapr is actually uninstalled in the second step? When I use those repro instructions, the CLI returns an error: it defaults to the `dapr-system` namespace, so can't find the dapr instance to uninstall. Instead, this sequence of commands works for me and permits reinstall of the dapr control plane successfully:

```bash
dapr init --wait -k -n cc-infra
dapr uninstall -k -n cc-infra
dapr init --wait -k -n cc-service
```

@mukundansundar, on a related note, given that dapr can infer the namespace it is installed in and dapr currently only supports a single control plane per cluster, it seems like `dapr uninstall -k` could support inferring the namespace of the current dapr install (just as `dapr status -k` doesn't require an explicit namespace specification).

**Comment by thanhlq** [comment]
Yes, it seems in the second step: dapr is unstall but with an error message (sayings dapr runtime is not found for uninstalling... I don't remember exactly)

**Comment by CodeMonkeyLeet** [comment]
That error meant that dapr was not actually uninstalled, which is why the reinstall is blocked. You can check this with the  `dapr status -k` command before reinstalling:

```zsh
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr init --wait -k -n cc-infra
⌛  Making the jump to hyperspace...
ℹ️  Note: To install Dapr using Helm, see here: https://docs.dapr.io/getting-started/install-dapr-kubernetes/#install-with-helm-advanced

✅  Deploying the Dapr control plane to your cluster...
✅  Success! Dapr has been installed to namespace cc-infra. To verify, run `dapr status -k' in your terminal. To get started, go here: https://aka.ms/dapr-getting-started
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr uninstall -k
ℹ️  Removing Dapr from your cluster...
❌  Error removing Dapr: uninstall: Release not loaded: dapr: release: not found
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr status -k
  NAME                   NAMESPACE  HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED              
  dapr-operator          cc-infra   True     Running  1         1.3.0    44s  2021-08-20 21:19.00  
  dapr-placement-server  cc-infra   True     Running  1         1.3.0    43s  2021-08-20 21:19.01  
  dapr-dashboard         cc-infra   True     Running  1         0.7.0    44s  2021-08-20 21:19.00  
  dapr-sentry            cc-infra   True     Running  1         1.3.0    44s  2021-08-20 21:19.00  
  dapr-sidecar-injector  cc-infra   True     Running  1         1.3.0    44s  2021-08-20 21:19.00  
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr uninstall -k -n cc-infra
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr status -k
❌  No status returned. Is Dapr initialized in your cluster?
codespace ➜ /workspaces/quickstarts (master ✗) $ dapr init --wait -k -n cc-services
⌛  Making the jump to hyperspace...
ℹ️  Note: To install Dapr using Helm, see here: https://docs.dapr.io/getting-started/install-dapr-kubernetes/#install-with-helm-advanced

✅  Deploying the Dapr control plane to your cluster...
✅  Success! Dapr has been installed to namespace cc-services. To verify, run `dapr status -k' in your terminal. To get started, go here: https://aka.ms/dapr-getting-started
```

**Comment by mukundansundar** [comment]
@thanhlq Is this issue resolved?
