### ISSUE TITLE
Fix Flaky Test: tests/e2e/upgrade TestUpgradePathNonHAModeMTLSDisabled

### ISSUE THREAD

**Issue by berndverst** [dapr/cli#794]
## Expected Behavior

`tests/e2e/upgrade TestUpgradePathNonHAModeMTLSDisabled` should pass consistently

## Actual Behavior

`tests/e2e/upgrade TestUpgradePathNonHAModeMTLSDisabled` is flaky and fails arbitrarily for different versions of Kind (regardless of HA mode). There is no consistent failure for specific Kind versions.

## Steps to Reproduce the Problem

Run the upgrade path test workflow

## Release Note

RELEASE NOTE:

**Comment by anhldbk** [comment]
@berndverst I've got the similar error for TestUpgradePathHAModeMTLSDisabled

<img width="1552" alt="Screen Shot 2021-11-13 at 09 09 01" src="https://user-images.githubusercontent.com/3270746/141601958-8e009c3d-7ac0-43ea-a3c4-267f0342d37b.png">
