### ISSUE TITLE
Expose port 8080 in Placement Service when running `dapr init`

### ISSUE THREAD

**Issue by fbridger** [dapr/cli#800]
## Describe the feature
Currently, when running `dapr init` the Placement Service (docker container) is not exposing port :8080 where the Healthz server is listening.

It is only exposing port 6050 ➔ 50005/tcp

I would like to request that `dapr init` also expose port 8080 potentially in 6051 (6051 ➔ 8080/tcp)

**Comment by mukundansundar** [comment]
@fbridger Could you give some idea on the use case for this change?

**Comment by fbridger** [comment]
When developing Dapr applications locally, I would like to be able to hit the HEALTH endpoint and also the METRIC endpoint.

Currently, this is not possible because the only PORT exposed by the Placement container is the gRPC port 50005.

Makes sense?

**Comment by mukundansundar** [comment]
@yaron2 Any thoughts on this?

**Comment by mukundansundar** [comment]
@yaron2 Any thoughts on this?

**Comment by mukundansundar** [comment]
@fbridger Would you be interested in contributing a PR for this?

**Comment by fbridger** [comment]
Hi @mukundansundar, how would I be able to contribute?

**Comment by kelvinnguyen2310** [comment]
hi @fbridger can you GET to http://localhost:58080/placement/state with latest Dapr now?
