### ISSUE TITLE
dapr init -k , doesn't works in China / restricted network

### ISSUE THREAD

**Issue by geekgao** [dapr/cli#808]
In general, when I execute ` dapr init -k  ` The default docker image from `docker.io/daprio/dapr:1.4.3` cannot get response.

I used socks5 proxy. Again the same error. But I can get the image from commandline` docker pull ` directly. Where can I reset image source with Dapr simply? 

Detail:

> Events:
>   Type     Reason                 Age                From               Message
>   
>   Normal   Scheduled              72s                default-scheduler  Successfully assigned dapr-system/dapr-placement-server-0 to 10.0.0.106
>   Normal   SuccessfulMountVolume  72s                kubelet            Successfully mounted volumes for pod "dapr-placement-server-0_dapr-system(eebdd764-8ed6-470b-bbf2-1e77dfa5ef31)"
>   Warning  FailedPullImage        25s                kubelet            Failed to pull image "docker.io/daprio/dapr:1.4.3": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
>   Warning  FailedCreate           25s                kubelet            Error: ErrImagePull
>   Warning  BackOffPullImage       24s                kubelet            Back-off pulling image "docker.io/daprio/dapr:1.4.3"
>   Warning  FailedCreate           24s                kubelet            Error: ImagePullBackOff
>   Normal   Pulling                11s (x2 over 71s)  kubelet            Pulling image "docker.io/daprio/dapr:1.4.3" 

----
Curl could get responsed(means docker with proxy is ok .):
```
root@soop-dev2:~# curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by msfussell** [comment]
@geekgao  - Is this consistent, in that it fails every time you use the dapr init command? I ask since there was a docker.io site availability incident yesterday.
