### ISSUE TITLE
"dapr status -k" and "kubectl get deploy -n dapr-system" give different results for Dapr system services

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#809]
## Expected Behavior

Inconsistent output from CLIs command and expects these to be the same. See screen shot below

## Actual Behavior
![Screenshot 2021-10-14 092623](https://user-images.githubusercontent.com/11199644/137358604-1d346efd-5df6-4cff-8613-78767419016a.png)

## Steps to Reproduce the Problem

Run both commands and compare the difference. They should be the same.

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@msfussell this is the expected output. Placement server is deployed as a StatefulSet so when querying for Deployments alone it will not be displayed. The dapr CLI command on the other hand queries all dapr control plane related services and displays them.

**Comment by mukundansundar** [comment]
@msfussell Can this issue be closed ?

**Comment by mukundansundar** [comment]
@msfussell Can this issue be closed?

**Comment by msfussell** [comment]
Yes, this can be closed.
