### ISSUE TITLE
Run: auto validate if --app-port is usable

### ISSUE THREAD

**Issue by anhldbk** [dapr/cli#813]
## Describe the proposal

If `--app-port` is set & not usable (for example: other application has already occupied the port), applications will fail

We should check before running child applications instead.

**Comment by anhldbk** [comment]
@yaron2 @mukundansundar WDYT?

**Comment by yaron2** [comment]
-app-port is the port the app is listening on, in which case if the user's app tries to listen on this port, it should fail. I recommend we keep it like that and let whatever server the user is handling to report the error.

**Comment by anhldbk** [comment]
Thanks @yaron2. Close this issue now.
