### ISSUE TITLE
Chinese output garbled 

### ISSUE THREAD

**Issue by saber-wang** [dapr/cli#815]
## Expected Behavior

Normal output Chinese log 

windows 11 dapr slim

![image](https://user-images.githubusercontent.com/45062099/138639065-e0f6f686-c15d-43de-a25b-cc627c763b39.png)

**Comment by Eriice** [comment]
This is not caused by dapr.cli. Add the following code in Program.cs.
```
var builder = WebApplication.CreateBuilder(args);
...
Console.OutputEncoding = System.Text.Encoding.UTF8;
...
```

**Comment by saber-wang** [comment]
@Eriice thanks
