### ISSUE TITLE
"invoke API is not ready" Possible solution proposals

### ISSUE THREAD

**Issue by geekgao** [dapr/cli#836]
## Ask your question here
"invoke API is not ready" when run invoke client with "`--app-port`" or dapr run application

## Solution
Remove the parameter  “`--app-port`". 

I suggest that this could be reflected in the documentation.

**Comment by mukundansundar** [comment]
@geekgao The `--app-port` parameter as of now is not mandatory. If it is not needed, it need not be given .... Could you explain more on what your use case is and what problem you are facing?

**Comment by mukundansundar** [comment]
@geekgao could you provide more details on your use case that is causing this issue?

**Comment by geekgao** [comment]
> @geekgao could you provide more details on your use case that is causing this issue?

My fault.
