### ISSUE TITLE
Add a --metadata flag to dapr publish

### ISSUE THREAD

**Issue by guyzyl** [dapr/cli#842]
## Describe the proposal
When publishing a message using the Dapr CLI by using `dapr publish`, it is automatically wrapped as a `CloudEvent`.
Add a `--metadata` flag to the `dapr publish` command to allow custom metadata, enabling the publich `rawPayload` option as a result.

## Release Note

RELEASE NOTE: **ADD** support for custom metadata in `dapr publish` using the new `--metadata` flag.

**Comment by yaron2** [comment]
Would you be open to adding this?

**Comment by guyzyl** [comment]
@yaron2 yes, that was the plan 🙂
Wanted to make sure the proposal is acceptable before starting to work on it.

**Comment by mukundansundar** [comment]
@guyzyl Assigned the issue to you

**Comment by mukundansundar** [comment]
@guyzyl assigning this issue to you.

**Comment by mukundansundar** [comment]
@guyzyl Are you still working in this issue?

**Comment by guyzyl** [comment]
@mukundansundar not atm, I unassigned myself from this issue.
