### ISSUE TITLE
Proposal: Support `invoke` cmd on kubernetes mode

### ISSUE THREAD

**Issue by imneov** [dapr/cli#848]
## Describe the proposal

We should add the `invoke` cmd on kubernetes mode.

As an example we can add kubernetes mode to `dapr invoke` use `-k` flag :

```
./dapr invoke --app-id core --method "v1/plugins/dm/entities?id=device123&owner=admin&type=device&source=dm "--verb PUT -d '{"status": "start","temp": 123}' -k
{"id":"device123","configs":{},"properties":{"status":"start","temp":123}}
✅  App invoked successfully
```

## Release Note

RELEASE NOTE:
- [ ] support got `pod` from kubernetes
- [ ] call pod use kubernetes RESTClient with proxy mode
- [ ] support `-k` flag to invoke cmd

**Comment by mukundansundar** [comment]
related to #436

**Comment by mukundansundar** [comment]
This is not yet complete. Triaged for 1.11

**Comment by imneov** [comment]
>This is not yet complete. Triaged for 1.11

@mukundansundar Excuse me, what leftovers do I still need to complete?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
