### ISSUE TITLE
the zipkin container with the latest darp has the log4j, version is 2.13.3,this version is bug,when to update it ?

### ISSUE THREAD

**Issue by haobiaosheng** [dapr/cli#858]
darp init

and will start a zipkin container in host

exec into the zipkin container, in /ziplin/BOOT-INF/lib/log4j-core-2.13.3.jar this path, the log4j version has bug, when tu update the zipkin image version with the latest Dapr version.

**Comment by mukundansundar** [comment]
@haobiaosheng 
Dapr CLI does not directly depend on a particular version of the Zipkin. 
Dapr CLI already uses only the latest version of the openzipkin docker image. See code snippet, https://github.com/dapr/cli/blob/master/pkg/standalone/standalone.go#L279.

As long as the latest image is released by Zipkin, that will be pulled if it is not available locally.

**Comment by mukundansundar** [comment]
@haobiaosheng is this issue resolved? Can this issue be closed if so?

**Comment by haobiaosheng** [comment]
ok, the issue can be closed, I will close it today.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dapr/cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dapr/cli] the zipkin container with the latest darp has the log4j, version is 2.13.3,this version is bug,when to update it ? (Issue #858)





 
@haobiaosheng is this issue resolved? Can this issue be closed if so?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mukundansundar** [comment]
> ok, the issue can be closed, I will close it today.
> […](#)

closing the issue
