### ISSUE TITLE
The port number of the dashboard supports automatic selection.

### ISSUE THREAD

**Issue by imneov** [dapr/cli#863]
## Describe the proposal

The port of the dashboard should support automatic selection. When the `--port` flag is set to `0`, a free port will be randomly found to start the dashboard to ensure that there will be no port conflicts.

## Release Note

RELEASE NOTE:

- [x]  the `--port` flag could be set to `0`,  In this case, dashboard will server on a random port which is free.

**Comment by imneov** [comment]
We can update  `portforward.LocalPort` use `fw.GetPorts()` when `portforward` is `Ready`.

```

failure := make(chan error)
go func() {
	if err := fw.ForwardPorts(); err != nil {
		failure <- err
	}
}()

select {
// if `pf.run()` succeeds, block until terminated
case <-pf.ReadyCh:
	ports, err := fw.GetPorts()
	if err == nil {
		pf.LocalPort = int(ports[0].Local)
		pf.RemotePort = int(ports[0].Remote)
	}
// if failure, causing a receive `<-failure` and returns the error
case err := <-failure:
	return err
}
```

**Comment by shubham1172** [comment]
@mukundansundar can you please open this issue again? There is an associated PR to close it.
