### ISSUE TITLE
why dapr invoke no --headers flag

### ISSUE THREAD

**Issue by uptutu** [dapr/cli#868]
## Ask your question here
I am try to invoke a my service by dapr and my service need an "Authorization" header. 

I wondered why dapr didn't offer this flag. Not even in Go SDK. (But i saw set header function in C# SDK)

Is this an official intention or a lack of functionality?

**Comment by mukundansundar** [comment]
@uptutu For the Go SDK please do create a feature request for that. 
For the CLI, it is intended as a way to interface with Dapr and improve dev experience. If this is a feature that is required, please do create a feature request and we will take a look into it.

@yaron2 any thoughts on this issue?
