### ISSUE TITLE
dapr annotate command

### ISSUE THREAD

**Issue by jjcollinge** [dapr/cli#870]
## Describe the proposal
Caveat that this is very much inspired by `linkerd inject` but I think it'd be useful to also have a `dapr inject` command that injects the annotations on to a Kubernetes deployment manifest for you. The manifest can be read from stdin (so it can be piped `kubectl get deploy -o yaml | dapr inject | kubectl apply -f -`, read from disk `dapr inject <dir> | kubectl apply -f -` or fetched from a remote URI `dapr inject http://example.com/deploy.yml | kubectl apply -f -`. In order to write the annotations the command will need to have all the different configurations options available as flags.

This could in theory be extended to do the full sidecar injection too as an alternative to using the sidecar injector. This might be useful for users who want to fully vet artifacts before deployment.

For more details, please see the attached PR #873 

## Release Note
RELEASE NOTE: **ADD** Dapr inject CLI command.

**Comment by mukundansundar** [comment]
@yaron2 Please add your thoughts on this ...

**Comment by yaron2** [comment]
I approve this, triaging to 1.7. Left a question on the PR itself.

**Comment by jjcollinge** [comment]
`dapr inject` moved to `dapr annotate` as it's a more accurate term for what this command is doing. In the future we may consider adding a `dapr inject` that builds on this command to perform a full sidecar injection.
