### ISSUE TITLE
dapr init  daprd_linux_amd64.tar.gz : unexpected EOF

### ISSUE THREAD

**Issue by 84819760** [dapr/cli#871]
dapr init
⌛  Making the jump to hyperspace...
ℹ️  Installing runtime version 1.5.1
❌  Downloading binaries and setting up components...
❌  error downloading daprd binary: Get "https://github.com/dapr/dapr/releases/download/v1.5.1/daprd_linux_amd64.tar.gz": unexpected EOF

After trying several times, the same error occurs. Is there any other way?

**Comment by mukundansundar** [comment]
@84819760 Do you have network restrictions that might cause this?
