### ISSUE TITLE
Unable to initialize

### ISSUE THREAD

**Issue by 84819760** [dapr/cli#877]
dapr init
⌛ Making the jump to hyperspace...
ℹ️ Installing runtime version 1.5.1
❌ Downloading binaries and setting up components...
❌ error downloading daprd binary: Get "https://github.com/dapr/dapr/releases/download/v1.5.1/daprd_linux_amd64.tar.gz": unexpected EOF

Tried for 7 days and failed to initialize. Is there any other way?

**Comment by yaron2** [comment]
Issue moved.

**Comment by mukundansundar** [comment]
related to #640. closing this issue in-lieu of that.
