### ISSUE TITLE
Allow exporting of private key / root password for auto-generated TLS certificate bundle

### ISSUE THREAD

**Issue by berndverst** [dapr/cli#891]
## Describe the proposal

In order to avoid downtime per #807 we need to be able to export the private key / root password for the auto-generated TLS certificate bundle. In the future this password needs to be specified or used when generated new certificates. Only certificates signed with the same private key can be used in a zero downtime upgrade.

**Comment by berndverst** [comment]
I think the idea is that the CLI generates the private root key locally already. So what this is asking is to make that available to you for reuse later - and if you do have it already you should be able to specify it to sign new certificates in the future. Does that make sense?

I'm not sure whether in the kubernetes case the certificates are generated on the server / within the sentry service instead, but perhaps there could be an option for this to be done locally and then passed to the helmchart (I know this is possible). If done locally it could make the private key available (or again allow you to specify the private key to use)

**Comment by pravinpushkar** [comment]
Summary based on the discussion - 
1. It would make more sense to provide a way to save the private key while doing `dapr init` itself.
a.  Need to explore the feasibility with current `dapr init` behavior.
2. In case of external certificates, it is up to operator/user to save the private key. We can document about this.

**Comment by pravinpushkar** [comment]
After exploring current `dapr init` implementation, following is my observation - 
1. `dapr init` completely depends on sentry service for generating private key and certificates. So, the private key is not available locally for it be saved for later use(exported).
2. Helm parameter options does not support `private key`(see [supported options](https://github.com/dapr/dapr/tree/master/charts/dapr#dapr-sentry-options)). So it does not seem feasible to create a private key and then pass it to `helm install` during `dapr init`.

**Comment by mukundansundar** [comment]
@pravinpushkar Is the conclusion that this feature is not feasible with the current implementation? Or is it that it is not feasible at all?

**Comment by pravinpushkar** [comment]
@mukundansundar 
With the current design it is not feasible to store the private key  -
1. In dapr init, private key is generated in sentry service, so we need a way to store the private key- May be recent Volume mount feature could be useful here (?)
2.  If we want to create private key in cli and then pass it along to helm install, then we need to make change in cli and helm charts. IMO it will make the init process complex in cli.

**Comment by pravinpushkar** [comment]
From the discussions above it is clear that storing private key can be tricky and may involve lot more changes which might complicate the current init behaviour in CLI.

So, I am closing this for now. Please let me know and feel free to re-open if you think otherwise.
@mukundansundar @berndverst @yaron2 @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
I agree. I think this needs to be fixed in the runtime and not the CLI
