### ISSUE TITLE
Renew or Replace auto-generated TLS certificates using the CLI

### ISSUE THREAD

**Issue by berndverst** [dapr/cli#892]
This is a request for a CLI command to easily renew / replace auto-generated Dapr TLS certificates.

`dapr upgrade --renew-certificates`
`dapr upgrade -k --renew-certificates`

This would generate new certificates and:
1. Update the Dapr Trust Bundle Secret
2. Restart the Dapr Sentry Service
3. Restart the rest of the Dapr Control Plane

Additionally, there needs to be an option to specify a private key / root password to be used for certificate generation.

`dapr upgrade --renew-certificates --certificate-password-file myprivatekey.pass`

The contents of this private key file would need to be used to sign the new auto-generated TLS certificates.

**Comment by pravinpushkar** [comment]
For kubrenetes, we will have below 3 options - 

```
1. dapr upgrade -k --renew-certificates
2. dapr upgrade -k --renew-certificates --certificate-password-file myprivatekey.pass
3. dapr upgrade -k --certificate-authority-root-certificate <ca.crt> --issuer-private-key<issuer.key> --issuer-public-certificate<issuer.crt> 
```
@berndverst @mukundansundar

**Comment by pravinpushkar** [comment]
I think it would be better to use subcommand for renew certificate. It will be easier to organize code this way.

```
~ ❯ ./dist/linux_amd64/release/dapr upgrade renew-certificate -h
Rotates Dapr root certificate of your kubernetes cluster

Usage:
  dapr upgrade renew-certificate [flags]

Examples:

# Generates new root and issuer certificates for kubernetest cluster
dapr upgrade renew-certificate -k

# Uses existing private root.key to generate new root and issuer certificates for kubernetest cluster
dapr upgrade renew-certificate -k --certificate-password-file myprivatekey.key

# Rotates certificate of your kubernetes cluster with provided ca.cert, issuer.crt and issuer.key file path
dapr upgrade renew-certificate -k --ca-root-certificate <ca.crt> --issuer-private-key<issuer.key> --issuer-public-certificate<issuer.crt>

# See more at: https://docs.dapr.io/getting-started/


Flags:
  -h, --help         help for renew-certificate
  -k, --kubernetes   Upgrades/Renews root certificate of Dapr in a Kubernetes cluster

Global Flags:
      --log-as-json   Log output in JSON format
```

**Comment by mukundansundar** [comment]
@pravinpushkar I agree, a subcommand is better to a flag in this scenario. 
I can see both pros and cons with this subcommand being under the `upgrade` command. We already have a `mtls` why not use that? 
I can see the point that with it being in the `upgrade` command it provides a consistent user experience during upgrade process. At the same time the command being part of `dapr mtls` will provide a single command which deals with all mtls related issues. There is also a related issue of #891 where this approach might be useful. 

My question here is should Cert renewal be combined with upgrade scenario? Wouldn't it be better to renew certificates independent of whether the Dapr version is upgrade or not ? In that scenario I think this would be better under the `dapr mtls` command. 

Also one other question, does the `renew-certificate` automatically rotate the certificate too? Should it only generate the cert and then a later command is issued to rotate it? 

Also will there be a flag to set the `not-after` (validity) field to a custom value as desired by the user?

**Comment by pravinpushkar** [comment]
@mukundansundar 
My thoughts on few of the items above  - 

> Wouldn't it be better to renew certificates independent of whether the Dapr version is upgrade or not ?

Agree. `renew-certificate` is going to be independent of version upgrade. We will maintain same configurations (mtls, ha, version etc) and only certificates will updated.

> Also one other question, does the renew-certificate automatically rotate the certificate too? Should it only generate the cert and then a later command is issued to rotate it?

I think there are 3 things to do here - 
1. Update the certificate in kubernetes secret
2.  Restart the dapr system services
3. Display an information to user to restart the application deployments

> Also will there be a flag to set the not-after (validity) field to a custom value as desired by the user?

Agree. I think it will be a good addition.

**Comment by pravinpushkar** [comment]
### Proposed command  - `renew-certificate`
### Flags:
```
      --ca-root-certificate string         The root certificate file
      --certificate-password-file string   The root.key file which is used to generate root certificate
  -h, --help                               help for renew-certificate
      --issuer-private-key string          The issuer certificate private key
      --issuer-public-certificate string   The issuer certificate
  -k, --kubernetes                         Renews root certificate of Dapr in a Kubernetes cluster
      --restart                            Restart Dapr control plane services
      --timeout uint                       The timeout for the certificate renewal (default 300)
      --valid-until uint                   Max days before certificate expires (default 365)
```
### Subcommand to ? `dapr mtls` or `dapr upgrade` or standalone 

### The below discussion assumes it to be a subcommand to `mtls`

### To provide support for these commands we can take one of the below approches -

### Approach 1 - Using Helm ( Current PR uses this approach):

1. `dapr mtls renew-cert -k`:
    a) This command will generate fresh root and issuer certificates.
    b) Use `helm.NewUpgrade(...)` to create a new `upgradeClient` with provided certificates and all existing configurations.
    c) Depending on the restart flag, restart control plane services.

2. `dapr mtls renew-cert -k --certificate-password-file myprivatekey.key`:
    a) This command will behave similar to above except it is will use provided `private root key file` to generate the certificates.

3.  `dapr mtls renew-cert -k --ca-root-certificate <ca.crt> --issuer-private-key<issuer.key> --issuer-public-certificate<issuer.crt>`
    a) This command will use the provided certificate files.
    b) Use `helm.NewUpgrade(...)` to create a new `upgradeClient` with provided certificates and all existing configurations.
    c) Depending on the restart flag, restart control plane services.

#### Pros:
    a) Unified approach for all 3 commands
    b) More control w.r.t different flags like `validity` for new certificate
#### Cons:
    a) Certificate generation logic has to be included
    b) dependent on helm

### Approach 2 - Modifying the `trust-bundle` directly (This approach is not verified yet) 

1. `dapr mtls renew-cert -k`:
    a) Accept an input file similar to this - [click here](https://docs.dapr.io/operations/security/mtls/#dapr-generated-self-signed-certificates)
    b) Let `sentry` handle the certificate creation
    c) Depending on the restart flag, restart control plane services.

2. `dapr mtls renew-cert -k --certificate-password-file myprivatekey.key`
    a) For this we again need to have the certificate generation logic as described in approach 1.
    b) Parse the current trust-bundle and replace the certificates values in base64 encoded format.
    c) Restart sentry and other control plane services. 

3.  `dapr mtls renew-cert -k --ca-root-certificate <ca.crt> --issuer-private-key<issuer.key> --issuer-public-certificate<issuer.crt>`
    a) This command will behave similar to above one except that it will use the provided certificates.

#### Pros:
    a) Not dependent on helm
    b) Might behave faster than helm approach
#### Cons:
    a) No control over validity of new certificates

cc @yaron2 @mukundansundar

**Comment by pravinpushkar** [comment]
### Manual verification steps taken for above implementation (Both on windows and linux)- 

#### Without apps running - 
1. Run `dapr init -k` -> initialize dapr with default certificates
2. Run `dapr status -k` ->  Check for no certificate expiring warning
3. Run `dapr mtls renew-certificate -k --valid-until 15 --restart` 
4. Repeat step 2. Notice there will be certificate expiry warning printed.
5. Run `dapr mtls renew-certificate -k --private-key "file_path_of_cur_deployed_cert" --valid-until 5`
6. Run `kubectl logs --selector=app=dapr-sentry --namespace dapr-system`.  Confirm that sentry is able to read the current certificate with expiry of 5 days.
7. Run ` dapr mtls renew-certificate -k --ca-root-certificate <> --issuer-private-key <> --issuer-public-certificate <> --restart`
8. Repeat step 2 and 6 and verify the certificate has been updated.

#### With apps running
1. Run `dapr init -k` -> initialize dapr with default certificates
2. Run `dapr status -k` ->  Check for no certificate expiring warning
3. Use `hello-kubernetes` app from quickstarts repository.
4. Run `dapr mtls renew-certificate -k --valid-until 0 --restart`  - Simulating expired certificate behavior
5.  Run `kubectl logs --selector=app=dapr-sentry --namespace dapr-system`.  Confirm that sentry is able to read the current certificate with expiry of 0 days.
6. Restart app deployments to pick up new cert immediately- check pods unhealthy and check `daprd` log to confirm it has picked up expired cert
7. Update new cert with some validity using same private key, don't restart -  verify sentry logs that certificate expiry is updated.
8. Restart app deployments to pick new certs.
9. Verify app pods healthy and daprd logs with no error about certificate expiry.
