### ISSUE TITLE
--log-as-json through cli is not working

### ISSUE THREAD

**Issue by s-aliasgar** [dapr/cli#897]
When adding --log-as-json to the dapr run command, only a few log statements are generated in json format
[services-dapr.log](https://github.com/dapr/cli/files/8085584/services-dapr.log)

**Comment by mukundansundar** [comment]
@s-aliasgar It seems that when the log-as-json flag is enabled, it is not passed to the `daprd` command that is run. 
Would you be interested in contributing a fix for this?

**Comment by s-aliasgar** [comment]
@mukundansundar I am a java developer and do not have much hands-on experience with go, hence won't be able to contribute in fixing this.

**Comment by ChaosInTheCRD** [comment]
It seems as though this issue is still present for the `dapr status` command. It might be worth reopening this issue or creating a new one 😊

CLI version: 1.10.0
Runtime version: 1.10.7 

```bash
➜ dapr status --log-as-json -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED              
  dapr-placement-server  dapr-system  True     Running  1         1.10.7   4m   2023-05-29 18:14.21  
  dapr-sidecar-injector  dapr-system  True     Running  1         1.10.7   4m   2023-05-29 18:14.21  
  dapr-dashboard         dapr-system  True     Running  1         0.12.0   4m   2023-05-29 18:14.21  
  dapr-sentry            dapr-system  True     Running  1         1.10.7   4m   2023-05-29 18:14.21  
  dapr-operator          dapr-system  True     Running  1         1.10.7   4m   2023-05-29 18:14.21  
```
