### ISSUE TITLE
Do you want to upload the source code to the service product online?self-hosted

### ISSUE THREAD

**Issue by 107295472** [dapr/cli#913]
## Do you want to upload the source code to the service product online?
Release version doesn't work
dapr run --app-id=accountservice --app-port=8050 --dapr-http-port=3500  --placement-host-address="localhost:50005" -- dotnet host.dll

**Comment by 107295472** [comment]
@mukundansundar  ver 1.6 ,http://localhost:3500/v1.0/invoke/accountservice/method/accountusecase/AccountLogin 
can't request ，dapr run --app-id=accountservice --app-port=8050 --dapr-http-port=3500 --placement-host-address="localhost:50005" -- dotnet run    ok

**Comment by 107295472** [comment]
I want to use self hosted  ,But you must use dotnet run. This is the source code. It can't be done online. It needs to be compiled.

**Comment by mukundansundar** [comment]
@107295472 Please see examples on how to use `.NET` along with `dapr` and the `dapr cli`. Please let me know if that answers your question ... or please clarify a bit more on the error that you are seeing as well as your question.

**Comment by 107295472** [comment]
Do you also use dotnet rum online?
