### ISSUE TITLE
Change E2E KinD k8s versions to mirror dapr/dapr KinD-e2e 

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#914]
## Describe the proposal
See the following file for the versions used and change the kind e2e files in CLI repo to use the same k8s versions and SHA.
https://github.com/dapr/dapr/blob/master/.github/workflows/kind-e2e.yaml#L65-L84

## Release Note

RELEASE NOTE:

**Comment by sourikghosh** [comment]
can I work on this ?

**Comment by mukundansundar** [comment]
sure @sourikghosh Please feel free to comment `/assign` to assign the work to yourself.
