### ISSUE TITLE
dapr init --image-repository being able to pull images from different registries

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#921]
## Describe the issue
`dapr init --image-repository <url>`  being able to pull images from private ghcr, dockerhub or any other private registry. Currently it pulls images only if the images are published under similar path structure like on Dapr Github container registry.

Goal -  Provide more generic approach to use any private registry.

Current behavior example -
private registry can be - `docker.io/<username>` or any other value like `ghcr.io/<some_username>`. User can not just have docker.io or ghcr.io or ghcr.io/dapr. Last one is to avoid conflict with existing dapr Github container registry.
and expectation is, this user will have images under his registry like below -
```
dapr/dapr:<version|tag>
dapr/3rdparty/zipkin
dapr/3rdparty/rejon
```
## Release Note

RELEASE NOTE:

**Comment by pravinpushkar** [comment]
cc @mukundansundar

**Comment by mukundansundar** [comment]
@pravinpushkar From the PR https://github.com/dapr/cli/pull/888, 

The image will be pulled as `<repository>/<image-name>`. If that is the case why do you need to override prefix path ... Why can't the `--image-repository` flag be specified for both repo and the other path?

**Comment by pravinpushkar** [comment]
Updated Subject and description.

**Comment by mukundansundar** [comment]
@pravinpushkar I think this issue has been resolved correct?

**Comment by pravinpushkar** [comment]
@mukundansundar We can close this issue as we have standardized the image paths needed for private registries.

On whether we need fully customizable paths or not, I think we can observe the community feedback on `--image-registry` usage and then take a call.
