### ISSUE TITLE
Specific workflows can be skipped during PR check for changes in non impacting assets

### ISSUE THREAD

**Issue by surenderssm** [dapr/cli#925]
Currently every PR raised triggers all the gated workflows. 
For examples change in `.md` file should not require us to run e2e workflows.

## Steps to Reproduce the Problem

- Raise a PR with change in `.md` file
- Sample PR : https://github.com/dapr/cli/pull/924

## Proposal

- [Leverage Excluding path](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) feature of GitHub workflow
- For example following changes in workflow will ensure it do not run on any changes in files under `docs`
```shell
on:
  push:
    paths-ignore:
      - 'docs/**'
```

## Release Note

RELEASE NOTE:

**Comment by hueifeng** [comment]
Can we consider adding the following?

```
  push:
    paths-ignore:
    - "**.md"
  pull_request:
    paths-ignore:
    - "**.md"
```

I found this a few e2e yaml files [kind_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/kind_e2e.yaml)、[self_hosted_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/self_hosted_e2e.yaml)、[upgrade_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/upgrade_e2e.yaml), are there any other files need to be added?？

**Comment by mukundansundar** [comment]
> Can we consider adding the following?
> 
> ```
>   push:
>     paths-ignore:
>     - "**.md"
>   pull_request:
>     paths-ignore:
>     - "**.md"
> ```
> 
> I found this a few e2e yaml files [kind_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/kind_e2e.yaml)、[self_hosted_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/self_hosted_e2e.yaml)、[upgrade_e2e.yaml](https://github.com/dapr/cli/blob/master/.github/workflows/upgrade_e2e.yaml), are there any other files need to be added?

@hueifeng The list looks good. 

Please feel free to assign this issue to yourself ....
