### ISSUE TITLE
Automate e2e CLI validation for Windows

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#932]
## Describe the proposal

Currently, the e2e pipeline is not run for Windows. It needs manual validation before each release.

https://github.com/dapr/cli/blob/a1348603081a2ace4d6355ebf19471e60eb8c319/.github/workflows/self_hosted_e2e.yaml#L42-L51

With this issue, add a Windows entry as well.

RELEASE NOTE: Automate CLI validation in Windows via `--slim` installation

**Comment by mukundansundar** [comment]
Keep in mind that we have to come up with a solution where in windows runners can use linux containers. See https://github.com/dapr/docs/issues/162

**Comment by shubham1172** [comment]
For reference, GH actions do not support container ops on Windows runner yet https://github.com/actions/runner/issues/904
