### ISSUE TITLE
dapr init pulling from dockerhub even if private registry is supplied

### ISSUE THREAD

**Issue by shivamkm07** [dapr/cli#939]
## Expected Behavior

dapr init --image-registry <private-registry> pulls from private-registry always, irrespective of environment variables.

## Actual Behavior

If default image registry is set to ghcr, and the corresponding image is not there in  ghcr, it would pull from dockerhub even if --image-registry flag is supplied.

## Steps to Reproduce the Problem

export DAPR_DEFAULT_IMAGE_REGISTRY="ghcr"
dapr init --image-registry <private_registry>

It would give logs like this:
- - -
⌛ Making the jump to hyperspace...
⚠ Flag --image-registry is a preview feature and is subject to change. It is only available from CLI version 1.7 onwards.
ℹ️ Container images will be pulled from Dapr GitHub container registry
ℹ️ Installing runtime version 1.6.1
→ Downloading binaries and setting up components... ℹ️ Placement image not found in Github container registry, pulling it from Docker Hub
↙ Downloading binaries and setting up components...
Dapr runtime installed to /home/pravinpushkar/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
export PATH=$PATH:/home/pravinpushkar/.dapr/bin
✅ Downloading binaries and setting up components...
✅ Downloaded binaries and completed components set up.
ℹ️ daprd binary has been installed to /home/pravinpushkar/.dapr/bin.
ℹ️ dapr_placement container is running.
ℹ️ dapr_redis container is running.
ℹ️ dapr_zipkin container is running.
ℹ️ Use `docker ps` to check running containers.
✅ Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
- - -

## Release Note

RELEASE NOTE: **FIX** Bug in CLI when pulling from private registry

**Comment by mukundansundar** [comment]
closed by #940
