### ISSUE TITLE
Cert renewal flags can create unwanted behavior if executed in wrong way

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#941]
## Expected Behavior

a. `dapr mtls renew-certificate -k --ca-root-certificate <ca.crt> --issuer-private-key <issuer.key> --issuer-public-certificate <issuer.crt>`

b. `dapr mtls renew-certificate -k --private-key myprivatekey.key`

1) The flags of the two commands should not be allowed to mix. 
2) ~restarting the control plane services in command `b` should not be allowed.~
## Actual Behavior

1) if this command is executed `dapr mtls renew-certificate -k --ca-root-certificate <ca.crt> --private-key private.key` , then according to the current implementation it chooses to execute `dapr mtls renew-certificate -k --private-key myprivatekey.key` since all 3 required parameters are not found for the 1st command.

2) ~if `--restart ` flag is provided with `dapr mtls renew-certificate -k --private-key myprivatekey.key`  then it restarts the control plane services.~

## Steps to Reproduce the Problem
Run this command - 
`dapr mtls renew-certificate -k --ca-root-certificate <ca.crt> --private-key private.key` 

Notice, since it did not find all 3 certs, it is trying to generate new cert using the provided private key.

## Release Note

RELEASE NOTE: **FIX** bug in CLI while using incorrect flags with `dapr mtls renew-certificate` command

**Comment by mukundansundar** [comment]
closed by #947
