### ISSUE TITLE
E2E - Self hosted workflow broken in MacOS/Darwin runner 

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#965]
Fix broken E2E self hosted action with MacOS/Darwin. 

See https://github.com/dapr/cli/actions/runs/2186053453.

The dependent action in the E2E workflow does not seem to be working correctly which in turn fails this workflow.

This has been broken for the past 7 days. 

## Release Note

RELEASE NOTE: NOT APPLICABLE

**Comment by pravinpushkar** [comment]
This might be useful - https://github.com/dapr/quickstarts/pull/649/files

**Comment by shubham1172** [comment]
Same issue https://github.com/docker-practice/actions-setup-docker/issues/16

**Comment by shubham1172** [comment]
With v1.0.9 https://github.com/dapr/cli/runs/6072922915?check_suite_focus=true
With v1.0.8 https://github.com/dapr/cli/runs/6073371177?check_suite_focus=true

In the one run, 1.0.8 seems to be working fine. Should we rerun it to be sure that it does not cause intermittent failures?
