### ISSUE TITLE
New env variable `DAPR_UDS_GRPC_PATH` when using `--unix-domain-socket`

### ISSUE THREAD

**Issue by berndverst** [dapr/cli#969]
## Describe the proposal

Today the CLI can start Dapr using the unix domain socket mechanism. The flag `--unix-domain-socket` provides a path prefix $UDSPREFIX with the remainder of the full path being `/dapr-$APPID-grpc.socket` for grpc and similar for http.

When using the Python SDK it is impossible to programmatically determine what the full UDS path is. With the help of the proposed `DAPR_UDS_GRPC_PATH` and `DAPR_UDS_HTTP_PATH` environment variables the Python client could automatically use UDS when these variables are set.

**Comment by daixiang0** [comment]
Why can python SDK not programmatically determine it? Is there something limited?

**Comment by mukundansundar** [comment]
@berndverst This cannot be in CLI alone, it needs to be set for any daprd enabled application. UDS support was added for k8s as well (https://github.com/dapr/dapr/pull/4348) so it needs to be set as an environment variable when k8s annotation is also set. CLI can pass for the self-hosted mode.
