### ISSUE TITLE
.dapr folder not installed

### ISSUE THREAD

**Issue by spottedmahn** [dapr/cli#979]
I'm on step 5 of the guide: [Step 5: Verify components directory has been initialized](https://docs.dapr.io/getting-started/install-dapr-selfhost/#step-5-verify-components-directory-has-been-initialized) & I'm not seeing that folder:

>$ ls ~/.dapr
ls: cannot access '/home/mdepouw/.dapr': No such file or directory

---

I've tried this guide previously so I old bits installed so I ran an `uninstall` first:

> sudo dapr uninstall
ℹ️  Removing Dapr from your machine...
ℹ️  Removing directory: /root/.dapr/bin
ℹ️  Removing container: dapr_placement
✅  Dapr has been removed successfully

> sudo dapr init
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
ℹ️  Installing runtime version 1.7.1
↘  Downloading binaries and setting up components...
Dapr runtime installed to /root/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/root/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /root/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

running on Ubuntu in WSL

**Comment by spottedmahn** [comment]
I just tried this & it failed:
>$ dapr run --app-id myapp --dapr-http-port 3500
WARNING: no application command found.
❌  stat /home/mdepouw/.dapr/components: no such file or directory

So I re-ran w/ `sudo` and it succeeded.  The `.dapr` folder must somewhere then, right?

>$ sudo dapr run --app-id myapp --dapr-http-port 3500
WARNING: no application command found.
ℹ️  Starting Dapr with id myapp. HTTP Port: 3500. gRPC Port: 34727

**Comment by pravinpushkar** [comment]
@spottedmahn Can you please check inside the root directory for .dapr folder. 
Also did you try `dapr init` without sudo and check for above directory.

**Comment by shubham1172** [comment]
Since you are using `sudo` while `init`, it installs `.dapr` in `/root/`.

```bash
sudo dapr uninstall --all # to clean dapr's root installation
dapr init # will create a .dapr folder in /home/$USERNAME

dapr run --app-id myapp # finally test running dapr with your user
```

**Comment by spottedmahn** [comment]
>Also did you try `dapr init` without sudo and check for above directory

I did (& I should have mentioned that).  I'm running w/ `sudo` b/c WSL can't communicate w/ my Windows Docker unless I do 🤷‍♂️.

This problem is probably fall-out from that problem ❄⚾(snowball).  I'll have to tackle that issue apparently, thanks for your help!
